// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AccountsDialog: typeof import('./src/components/AccountsDialog.vue')['default']
    AccountsTable: typeof import('./src/components/AccountsTable.vue')['default']
    AppAbout: typeof import('./src/views/app/AppAbout.vue')['default']
    AppAboutDialog: typeof import('./src/views/app/AppAboutDialog.vue')['default']
    AppAddPageDialog: typeof import('./src/views/app/AppAddPageDialog.vue')['default']
    AppHeader: typeof import('./src/views/app/AppHeader.vue')['default']
    AppMenu: typeof import('./src/views/app/AppMenu.vue')['default']
    AppStartup: typeof import('./src/views/AppStartup.vue')['default']
    AppView: typeof import('./src/views/app/AppView.vue')['default']
    DashboardView: typeof import('./src/views/DashboardView.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    LoginView: typeof import('./src/views/LoginView.vue')['default']
  }
}

export { }
