// Code generated by capnpc-go. DO NOT EDIT.

package svc

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
)

type ThingEvent capnp.Struct

// ThingEvent_TypeID is the unique identifier for the type ThingEvent.
const ThingEvent_TypeID = 0xbb3d38b87fbdfa31

func NewThingEvent(s *capnp.Segment) (ThingEvent, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return ThingEvent(st), err
}

func NewRootThingEvent(s *capnp.Segment) (ThingEvent, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return ThingEvent(st), err
}

func ReadRootThingEvent(msg *capnp.Message) (ThingEvent, error) {
	root, err := msg.Root()
	return ThingEvent(root.Struct()), err
}

func (s ThingEvent) String() string {
	str, _ := text.Marshal(0xbb3d38b87fbdfa31, capnp.Struct(s))
	return str
}

func (s ThingEvent) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ThingEvent) DecodeFromPtr(p capnp.Ptr) ThingEvent {
	return ThingEvent(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ThingEvent) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ThingEvent) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ThingEvent) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ThingEvent) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ThingEvent) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ThingEvent) HasName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ThingEvent) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ThingEvent) SetName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ThingEvent) ValueJSON() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ThingEvent) HasValueJSON() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ThingEvent) ValueJSONBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ThingEvent) SetValueJSON(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s ThingEvent) Timestamp() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s ThingEvent) HasTimestamp() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s ThingEvent) TimestampBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s ThingEvent) SetTimestamp(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

// ThingEvent_List is a list of ThingEvent.
type ThingEvent_List = capnp.StructList[ThingEvent]

// NewThingEvent creates a new list of ThingEvent.
func NewThingEvent_List(s *capnp.Segment, sz int32) (ThingEvent_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3}, sz)
	return capnp.StructList[ThingEvent](l), err
}

// ThingEvent_Future is a wrapper for a ThingEvent promised by a client call.
type ThingEvent_Future struct{ *capnp.Future }

func (p ThingEvent_Future) Struct() (ThingEvent, error) {
	s, err := p.Future.Struct()
	return ThingEvent(s), err
}

type EventHistoryStore capnp.Client

// EventHistoryStore_TypeID is the unique identifier for the type EventHistoryStore.
const EventHistoryStore_TypeID = 0xaf10cc0a7654d951

func (c EventHistoryStore) GetEventHistory(ctx context.Context, params func(EventHistoryStore_getEventHistory_Params) error) (EventHistoryStore_getEventHistory_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xaf10cc0a7654d951,
			MethodID:      0,
			InterfaceName: "svc/EventHistory.capnp:EventHistoryStore",
			MethodName:    "getEventHistory",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(EventHistoryStore_getEventHistory_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return EventHistoryStore_getEventHistory_Results_Future{Future: ans.Future()}, release
}
func (c EventHistoryStore) AddEvent(ctx context.Context, params func(EventHistoryStore_addEvent_Params) error) (EventHistoryStore_addEvent_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xaf10cc0a7654d951,
			MethodID:      1,
			InterfaceName: "svc/EventHistory.capnp:EventHistoryStore",
			MethodName:    "addEvent",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 2}
		s.PlaceArgs = func(s capnp.Struct) error { return params(EventHistoryStore_addEvent_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return EventHistoryStore_addEvent_Results_Future{Future: ans.Future()}, release
}

func (c EventHistoryStore) AddRef() EventHistoryStore {
	return EventHistoryStore(capnp.Client(c).AddRef())
}

func (c EventHistoryStore) Release() {
	capnp.Client(c).Release()
}

func (c EventHistoryStore) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (EventHistoryStore) DecodeFromPtr(p capnp.Ptr) EventHistoryStore {
	return EventHistoryStore(capnp.Client{}.DecodeFromPtr(p))
}

func (c EventHistoryStore) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// A EventHistoryStore_Server is a EventHistoryStore with a local implementation.
type EventHistoryStore_Server interface {
	GetEventHistory(context.Context, EventHistoryStore_getEventHistory) error

	AddEvent(context.Context, EventHistoryStore_addEvent) error
}

// EventHistoryStore_NewServer creates a new Server from an implementation of EventHistoryStore_Server.
func EventHistoryStore_NewServer(s EventHistoryStore_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(EventHistoryStore_Methods(nil, s), s, c)
}

// EventHistoryStore_ServerToClient creates a new Client from an implementation of EventHistoryStore_Server.
// The caller is responsible for calling Release on the returned Client.
func EventHistoryStore_ServerToClient(s EventHistoryStore_Server) EventHistoryStore {
	return EventHistoryStore(capnp.NewClient(EventHistoryStore_NewServer(s)))
}

// EventHistoryStore_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func EventHistoryStore_Methods(methods []server.Method, s EventHistoryStore_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xaf10cc0a7654d951,
			MethodID:      0,
			InterfaceName: "svc/EventHistory.capnp:EventHistoryStore",
			MethodName:    "getEventHistory",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.GetEventHistory(ctx, EventHistoryStore_getEventHistory{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xaf10cc0a7654d951,
			MethodID:      1,
			InterfaceName: "svc/EventHistory.capnp:EventHistoryStore",
			MethodName:    "addEvent",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.AddEvent(ctx, EventHistoryStore_addEvent{call})
		},
	})

	return methods
}

// EventHistoryStore_getEventHistory holds the state for a server call to EventHistoryStore.getEventHistory.
// See server.Call for documentation.
type EventHistoryStore_getEventHistory struct {
	*server.Call
}

// Args returns the call's arguments.
func (c EventHistoryStore_getEventHistory) Args() EventHistoryStore_getEventHistory_Params {
	return EventHistoryStore_getEventHistory_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c EventHistoryStore_getEventHistory) AllocResults() (EventHistoryStore_getEventHistory_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return EventHistoryStore_getEventHistory_Results(r), err
}

// EventHistoryStore_addEvent holds the state for a server call to EventHistoryStore.addEvent.
// See server.Call for documentation.
type EventHistoryStore_addEvent struct {
	*server.Call
}

// Args returns the call's arguments.
func (c EventHistoryStore_addEvent) Args() EventHistoryStore_addEvent_Params {
	return EventHistoryStore_addEvent_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c EventHistoryStore_addEvent) AllocResults() (EventHistoryStore_addEvent_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return EventHistoryStore_addEvent_Results(r), err
}

// EventHistoryStore_List is a list of EventHistoryStore.
type EventHistoryStore_List = capnp.CapList[EventHistoryStore]

// NewEventHistoryStore creates a new list of EventHistoryStore.
func NewEventHistoryStore_List(s *capnp.Segment, sz int32) (EventHistoryStore_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[EventHistoryStore](l), err
}

type EventHistoryStore_getEventHistory_Params capnp.Struct

// EventHistoryStore_getEventHistory_Params_TypeID is the unique identifier for the type EventHistoryStore_getEventHistory_Params.
const EventHistoryStore_getEventHistory_Params_TypeID = 0xdb6ff184a818a77c

func NewEventHistoryStore_getEventHistory_Params(s *capnp.Segment) (EventHistoryStore_getEventHistory_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return EventHistoryStore_getEventHistory_Params(st), err
}

func NewRootEventHistoryStore_getEventHistory_Params(s *capnp.Segment) (EventHistoryStore_getEventHistory_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return EventHistoryStore_getEventHistory_Params(st), err
}

func ReadRootEventHistoryStore_getEventHistory_Params(msg *capnp.Message) (EventHistoryStore_getEventHistory_Params, error) {
	root, err := msg.Root()
	return EventHistoryStore_getEventHistory_Params(root.Struct()), err
}

func (s EventHistoryStore_getEventHistory_Params) String() string {
	str, _ := text.Marshal(0xdb6ff184a818a77c, capnp.Struct(s))
	return str
}

func (s EventHistoryStore_getEventHistory_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EventHistoryStore_getEventHistory_Params) DecodeFromPtr(p capnp.Ptr) EventHistoryStore_getEventHistory_Params {
	return EventHistoryStore_getEventHistory_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EventHistoryStore_getEventHistory_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EventHistoryStore_getEventHistory_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EventHistoryStore_getEventHistory_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EventHistoryStore_getEventHistory_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EventHistoryStore_getEventHistory_Params) ThingID() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s EventHistoryStore_getEventHistory_Params) HasThingID() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s EventHistoryStore_getEventHistory_Params) ThingIDBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s EventHistoryStore_getEventHistory_Params) SetThingID(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// EventHistoryStore_getEventHistory_Params_List is a list of EventHistoryStore_getEventHistory_Params.
type EventHistoryStore_getEventHistory_Params_List = capnp.StructList[EventHistoryStore_getEventHistory_Params]

// NewEventHistoryStore_getEventHistory_Params creates a new list of EventHistoryStore_getEventHistory_Params.
func NewEventHistoryStore_getEventHistory_Params_List(s *capnp.Segment, sz int32) (EventHistoryStore_getEventHistory_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[EventHistoryStore_getEventHistory_Params](l), err
}

// EventHistoryStore_getEventHistory_Params_Future is a wrapper for a EventHistoryStore_getEventHistory_Params promised by a client call.
type EventHistoryStore_getEventHistory_Params_Future struct{ *capnp.Future }

func (p EventHistoryStore_getEventHistory_Params_Future) Struct() (EventHistoryStore_getEventHistory_Params, error) {
	s, err := p.Future.Struct()
	return EventHistoryStore_getEventHistory_Params(s), err
}

type EventHistoryStore_getEventHistory_Results capnp.Struct

// EventHistoryStore_getEventHistory_Results_TypeID is the unique identifier for the type EventHistoryStore_getEventHistory_Results.
const EventHistoryStore_getEventHistory_Results_TypeID = 0x90131f0fcef4f59d

func NewEventHistoryStore_getEventHistory_Results(s *capnp.Segment) (EventHistoryStore_getEventHistory_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return EventHistoryStore_getEventHistory_Results(st), err
}

func NewRootEventHistoryStore_getEventHistory_Results(s *capnp.Segment) (EventHistoryStore_getEventHistory_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return EventHistoryStore_getEventHistory_Results(st), err
}

func ReadRootEventHistoryStore_getEventHistory_Results(msg *capnp.Message) (EventHistoryStore_getEventHistory_Results, error) {
	root, err := msg.Root()
	return EventHistoryStore_getEventHistory_Results(root.Struct()), err
}

func (s EventHistoryStore_getEventHistory_Results) String() string {
	str, _ := text.Marshal(0x90131f0fcef4f59d, capnp.Struct(s))
	return str
}

func (s EventHistoryStore_getEventHistory_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EventHistoryStore_getEventHistory_Results) DecodeFromPtr(p capnp.Ptr) EventHistoryStore_getEventHistory_Results {
	return EventHistoryStore_getEventHistory_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EventHistoryStore_getEventHistory_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EventHistoryStore_getEventHistory_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EventHistoryStore_getEventHistory_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EventHistoryStore_getEventHistory_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EventHistoryStore_getEventHistory_Results) Events() (ThingEvent_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return ThingEvent_List(p.List()), err
}

func (s EventHistoryStore_getEventHistory_Results) HasEvents() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s EventHistoryStore_getEventHistory_Results) SetEvents(v ThingEvent_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewEvents sets the events field to a newly
// allocated ThingEvent_List, preferring placement in s's segment.
func (s EventHistoryStore_getEventHistory_Results) NewEvents(n int32) (ThingEvent_List, error) {
	l, err := NewThingEvent_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return ThingEvent_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// EventHistoryStore_getEventHistory_Results_List is a list of EventHistoryStore_getEventHistory_Results.
type EventHistoryStore_getEventHistory_Results_List = capnp.StructList[EventHistoryStore_getEventHistory_Results]

// NewEventHistoryStore_getEventHistory_Results creates a new list of EventHistoryStore_getEventHistory_Results.
func NewEventHistoryStore_getEventHistory_Results_List(s *capnp.Segment, sz int32) (EventHistoryStore_getEventHistory_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[EventHistoryStore_getEventHistory_Results](l), err
}

// EventHistoryStore_getEventHistory_Results_Future is a wrapper for a EventHistoryStore_getEventHistory_Results promised by a client call.
type EventHistoryStore_getEventHistory_Results_Future struct{ *capnp.Future }

func (p EventHistoryStore_getEventHistory_Results_Future) Struct() (EventHistoryStore_getEventHistory_Results, error) {
	s, err := p.Future.Struct()
	return EventHistoryStore_getEventHistory_Results(s), err
}

type EventHistoryStore_addEvent_Params capnp.Struct

// EventHistoryStore_addEvent_Params_TypeID is the unique identifier for the type EventHistoryStore_addEvent_Params.
const EventHistoryStore_addEvent_Params_TypeID = 0xc51a746e926da7f3

func NewEventHistoryStore_addEvent_Params(s *capnp.Segment) (EventHistoryStore_addEvent_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return EventHistoryStore_addEvent_Params(st), err
}

func NewRootEventHistoryStore_addEvent_Params(s *capnp.Segment) (EventHistoryStore_addEvent_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return EventHistoryStore_addEvent_Params(st), err
}

func ReadRootEventHistoryStore_addEvent_Params(msg *capnp.Message) (EventHistoryStore_addEvent_Params, error) {
	root, err := msg.Root()
	return EventHistoryStore_addEvent_Params(root.Struct()), err
}

func (s EventHistoryStore_addEvent_Params) String() string {
	str, _ := text.Marshal(0xc51a746e926da7f3, capnp.Struct(s))
	return str
}

func (s EventHistoryStore_addEvent_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EventHistoryStore_addEvent_Params) DecodeFromPtr(p capnp.Ptr) EventHistoryStore_addEvent_Params {
	return EventHistoryStore_addEvent_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EventHistoryStore_addEvent_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EventHistoryStore_addEvent_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EventHistoryStore_addEvent_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EventHistoryStore_addEvent_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EventHistoryStore_addEvent_Params) ThingID() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s EventHistoryStore_addEvent_Params) HasThingID() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s EventHistoryStore_addEvent_Params) ThingIDBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s EventHistoryStore_addEvent_Params) SetThingID(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s EventHistoryStore_addEvent_Params) Event() (ThingEvent, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return ThingEvent(p.Struct()), err
}

func (s EventHistoryStore_addEvent_Params) HasEvent() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s EventHistoryStore_addEvent_Params) SetEvent(v ThingEvent) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewEvent sets the event field to a newly
// allocated ThingEvent struct, preferring placement in s's segment.
func (s EventHistoryStore_addEvent_Params) NewEvent() (ThingEvent, error) {
	ss, err := NewThingEvent(capnp.Struct(s).Segment())
	if err != nil {
		return ThingEvent{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

// EventHistoryStore_addEvent_Params_List is a list of EventHistoryStore_addEvent_Params.
type EventHistoryStore_addEvent_Params_List = capnp.StructList[EventHistoryStore_addEvent_Params]

// NewEventHistoryStore_addEvent_Params creates a new list of EventHistoryStore_addEvent_Params.
func NewEventHistoryStore_addEvent_Params_List(s *capnp.Segment, sz int32) (EventHistoryStore_addEvent_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[EventHistoryStore_addEvent_Params](l), err
}

// EventHistoryStore_addEvent_Params_Future is a wrapper for a EventHistoryStore_addEvent_Params promised by a client call.
type EventHistoryStore_addEvent_Params_Future struct{ *capnp.Future }

func (p EventHistoryStore_addEvent_Params_Future) Struct() (EventHistoryStore_addEvent_Params, error) {
	s, err := p.Future.Struct()
	return EventHistoryStore_addEvent_Params(s), err
}

func (p EventHistoryStore_addEvent_Params_Future) Event() ThingEvent_Future {
	return ThingEvent_Future{Future: p.Future.Field(1, nil)}
}

type EventHistoryStore_addEvent_Results capnp.Struct

// EventHistoryStore_addEvent_Results_TypeID is the unique identifier for the type EventHistoryStore_addEvent_Results.
const EventHistoryStore_addEvent_Results_TypeID = 0x8a0b42d5f36d756e

func NewEventHistoryStore_addEvent_Results(s *capnp.Segment) (EventHistoryStore_addEvent_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return EventHistoryStore_addEvent_Results(st), err
}

func NewRootEventHistoryStore_addEvent_Results(s *capnp.Segment) (EventHistoryStore_addEvent_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return EventHistoryStore_addEvent_Results(st), err
}

func ReadRootEventHistoryStore_addEvent_Results(msg *capnp.Message) (EventHistoryStore_addEvent_Results, error) {
	root, err := msg.Root()
	return EventHistoryStore_addEvent_Results(root.Struct()), err
}

func (s EventHistoryStore_addEvent_Results) String() string {
	str, _ := text.Marshal(0x8a0b42d5f36d756e, capnp.Struct(s))
	return str
}

func (s EventHistoryStore_addEvent_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EventHistoryStore_addEvent_Results) DecodeFromPtr(p capnp.Ptr) EventHistoryStore_addEvent_Results {
	return EventHistoryStore_addEvent_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EventHistoryStore_addEvent_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EventHistoryStore_addEvent_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EventHistoryStore_addEvent_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EventHistoryStore_addEvent_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// EventHistoryStore_addEvent_Results_List is a list of EventHistoryStore_addEvent_Results.
type EventHistoryStore_addEvent_Results_List = capnp.StructList[EventHistoryStore_addEvent_Results]

// NewEventHistoryStore_addEvent_Results creates a new list of EventHistoryStore_addEvent_Results.
func NewEventHistoryStore_addEvent_Results_List(s *capnp.Segment, sz int32) (EventHistoryStore_addEvent_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[EventHistoryStore_addEvent_Results](l), err
}

// EventHistoryStore_addEvent_Results_Future is a wrapper for a EventHistoryStore_addEvent_Results promised by a client call.
type EventHistoryStore_addEvent_Results_Future struct{ *capnp.Future }

func (p EventHistoryStore_addEvent_Results_Future) Struct() (EventHistoryStore_addEvent_Results, error) {
	s, err := p.Future.Struct()
	return EventHistoryStore_addEvent_Results(s), err
}

const schema_f1bd301f7c12caab = "x\xda\x9c\x92\xcfk\x13_\x14\xc5\xcfyo\xd2\x94~" +
	"\xdbo;\x9dJE\x90n\xb2h\x84\xd4\xc4\xb8\xd0B" +
	"I\x08\x06\x9a \x9a\xd7f\xa9\x8b\xa1\x1dj\xa03\x09" +
	"\x99I\x8aP(\x88 \xb8\x12\xc1\xa5\x0bW\x15D\xba" +
	"\x15\xa4K7E\\\x08.\x8a\xf8't\x11\xaa\x1b7" +
	"#/f&\xa1.\x8an\xcf\xfd\xf5\xb9\xf7\xdcl\x86" +
	"E#7\xb5#!\xd4bb,\xf4:\xee\xe9\x97\xd2" +
	"\x7fOa\xa6\x09\x18I \xff\x8a\x9f\x09#|\xf9\xe3" +
	"\xfb\xa7\xe9\x05\xeb\xd9\xefH\x82:\xf4\x82\x13\x02\xb4\xde" +
	"\xb2\x00\x86\xea\xb8\xde\x9d\xf88s\x00s^\x86o\x8e" +
	"fw\x17\xb2\x87=\x80\xf9o\xac\xd2\xea\xe9\x02\xeb\x84" +
	"O\xac\xb2H\x02a\xee\xe7\xe1\xde\xbb\x1b+\xefa\xce" +
	"s\x98\x9d\x90\xbamF\xcc\xd2Z\xd1i\xd6Mq\x00" +
	"\x86\xa7\xfb\xees/\xb8\xf4a0[G\xf2\xc7\xe2\x88" +
	"\xa0u\"v\xc0pw\xff\xe2\xeb\xc7\xbd\xe6\xd7Q\xb8" +
	"\x8a\x14\x1a\xee\xbe, \x13\xfa\xdd\x8d\xab\xe5\xae\xe3\x8d" +
	"\x05\xab\x0d?h\xb6\x1f.m\xd8-\xaf\xb5\xac\xb5H" +
	"Z\x0f\x9amg\xc9\xde\xdc\xec\x8b\xa95\xc7\xefl\x07" +
	"\xf4\xe3\xda\xe4\xb9\xb5[N0*\x0eZ\xf8\x802\xa4" +
	"\x01\x18\x04\xcc\xa9e@\x8dK\xaa\x94`\xc1\xd1\xd9>" +
	"\xff\x07k\x92\x9c\x19^\x05\xd4b<\xda8o4P" +
	"#\xd5\xb8L\x00\xf11\x18Yf\xe6\x1eA\x98\xe9$" +
	"\x87\x97dd\xb4y\xb9\x0aa^H\x86\x11;\x07m" +
	"Qd\x18\xdd\x02@\x915\x0ey\xe4\x19\x9e\xfa\x83\x86" +
	"\xb7\xa5\x03\x0c4\xc7d\xbcm\xf9\x0a\xa0\x8a\x92\xea\xb6" +
	"\xa0I\xceQ\x8b\x955@\xadJ\xaa\xba\xa0)\xc4\x1c" +
	"\x05`*-\xd6$\xd5=\xc1i\xcfv\x1dNBp" +
	"\x12\x0c\xbb\xf6v\xc7\xa9\xae\xdf\x05\xef\xc4Z\xd0p\x1d" +
	"?\xb0]\xb0\x15k\xff\xe0q\xcdn\xdb\xae\xdf7$" +
	"\"N\x97\x00\x95\x92T\xd9\x11\xe2\xcc5@-J\xaa" +
	"\xeb\x82{\x81^\xb6r+\x9a\xbb\xd07\xf1\x8cy3" +
	"#<\x7f\xff7\x03\xac\xd1\xaf)\x0d\xbef\xeeO\x80" +
	"_\x01\x00\x00\xff\xff\xeb\x92\x0c\xf7"

func init() {
	schemas.Register(schema_f1bd301f7c12caab,
		0x8a0b42d5f36d756e,
		0x90131f0fcef4f59d,
		0xaf10cc0a7654d951,
		0xbb3d38b87fbdfa31,
		0xc51a746e926da7f3,
		0xdb6ff184a818a77c)
}
