// Code generated by capnpc-go. DO NOT EDIT.

package svc

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
)

type ClientCapabilities capnp.Struct

// ClientCapabilities_TypeID is the unique identifier for the type ClientCapabilities.
const ClientCapabilities_TypeID = 0xf625f2c3c988ee07

func NewClientCapabilities(s *capnp.Segment) (ClientCapabilities, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return ClientCapabilities(st), err
}

func NewRootClientCapabilities(s *capnp.Segment) (ClientCapabilities, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return ClientCapabilities(st), err
}

func ReadRootClientCapabilities(msg *capnp.Message) (ClientCapabilities, error) {
	root, err := msg.Root()
	return ClientCapabilities(root.Struct()), err
}

func (s ClientCapabilities) String() string {
	str, _ := text.Marshal(0xf625f2c3c988ee07, capnp.Struct(s))
	return str
}

func (s ClientCapabilities) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ClientCapabilities) DecodeFromPtr(p capnp.Ptr) ClientCapabilities {
	return ClientCapabilities(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ClientCapabilities) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ClientCapabilities) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ClientCapabilities) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ClientCapabilities) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ClientCapabilities) Directory() ThingDirectory {
	p, _ := capnp.Struct(s).Ptr(0)
	return ThingDirectory(p.Interface().Client())
}

func (s ClientCapabilities) HasDirectory() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ClientCapabilities) SetDirectory(v ThingDirectory) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().AddCap(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(0, in.ToPtr())
}

func (s ClientCapabilities) EventHistory() EventHistoryStore {
	p, _ := capnp.Struct(s).Ptr(1)
	return EventHistoryStore(p.Interface().Client())
}

func (s ClientCapabilities) HasEventHistory() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ClientCapabilities) SetEventHistory(v EventHistoryStore) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(1, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().AddCap(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(1, in.ToPtr())
}

func (s ClientCapabilities) PropertyStore() PropertyStore {
	p, _ := capnp.Struct(s).Ptr(2)
	return PropertyStore(p.Interface().Client())
}

func (s ClientCapabilities) HasPropertyStore() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s ClientCapabilities) SetPropertyStore(v PropertyStore) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(2, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().AddCap(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(2, in.ToPtr())
}

func (s ClientCapabilities) Provisioning() ProvisioningService {
	p, _ := capnp.Struct(s).Ptr(3)
	return ProvisioningService(p.Interface().Client())
}

func (s ClientCapabilities) HasProvisioning() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s ClientCapabilities) SetProvisioning(v ProvisioningService) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(3, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().AddCap(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(3, in.ToPtr())
}

// ClientCapabilities_List is a list of ClientCapabilities.
type ClientCapabilities_List = capnp.StructList[ClientCapabilities]

// NewClientCapabilities creates a new list of ClientCapabilities.
func NewClientCapabilities_List(s *capnp.Segment, sz int32) (ClientCapabilities_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4}, sz)
	return capnp.StructList[ClientCapabilities](l), err
}

// ClientCapabilities_Future is a wrapper for a ClientCapabilities promised by a client call.
type ClientCapabilities_Future struct{ *capnp.Future }

func (p ClientCapabilities_Future) Struct() (ClientCapabilities, error) {
	s, err := p.Future.Struct()
	return ClientCapabilities(s), err
}

func (p ClientCapabilities_Future) Directory() ThingDirectory {
	return ThingDirectory(p.Future.Field(0, nil).Client())
}

func (p ClientCapabilities_Future) EventHistory() EventHistoryStore {
	return EventHistoryStore(p.Future.Field(1, nil).Client())
}

func (p ClientCapabilities_Future) PropertyStore() PropertyStore {
	return PropertyStore(p.Future.Field(2, nil).Client())
}

func (p ClientCapabilities_Future) Provisioning() ProvisioningService {
	return ProvisioningService(p.Future.Field(3, nil).Client())
}

type Gateway capnp.Client

// Gateway_TypeID is the unique identifier for the type Gateway.
const Gateway_TypeID = 0x928a26cd0a89a930

func (c Gateway) Login(ctx context.Context, params func(Gateway_login_Params) error) (Gateway_login_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x928a26cd0a89a930,
			MethodID:      0,
			InterfaceName: "svc/Gateway.capnp:Gateway",
			MethodName:    "login",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 2}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Gateway_login_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Gateway_login_Results_Future{Future: ans.Future()}, release
}
func (c Gateway) Capabilities(ctx context.Context, params func(Gateway_capabilities_Params) error) (Gateway_capabilities_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x928a26cd0a89a930,
			MethodID:      1,
			InterfaceName: "svc/Gateway.capnp:Gateway",
			MethodName:    "capabilities",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Gateway_capabilities_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Gateway_capabilities_Results_Future{Future: ans.Future()}, release
}

func (c Gateway) AddRef() Gateway {
	return Gateway(capnp.Client(c).AddRef())
}

func (c Gateway) Release() {
	capnp.Client(c).Release()
}

func (c Gateway) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Gateway) DecodeFromPtr(p capnp.Ptr) Gateway {
	return Gateway(capnp.Client{}.DecodeFromPtr(p))
}

func (c Gateway) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// A Gateway_Server is a Gateway with a local implementation.
type Gateway_Server interface {
	Login(context.Context, Gateway_login) error

	Capabilities(context.Context, Gateway_capabilities) error
}

// Gateway_NewServer creates a new Server from an implementation of Gateway_Server.
func Gateway_NewServer(s Gateway_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Gateway_Methods(nil, s), s, c)
}

// Gateway_ServerToClient creates a new Client from an implementation of Gateway_Server.
// The caller is responsible for calling Release on the returned Client.
func Gateway_ServerToClient(s Gateway_Server) Gateway {
	return Gateway(capnp.NewClient(Gateway_NewServer(s)))
}

// Gateway_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Gateway_Methods(methods []server.Method, s Gateway_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x928a26cd0a89a930,
			MethodID:      0,
			InterfaceName: "svc/Gateway.capnp:Gateway",
			MethodName:    "login",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Login(ctx, Gateway_login{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x928a26cd0a89a930,
			MethodID:      1,
			InterfaceName: "svc/Gateway.capnp:Gateway",
			MethodName:    "capabilities",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Capabilities(ctx, Gateway_capabilities{call})
		},
	})

	return methods
}

// Gateway_login holds the state for a server call to Gateway.login.
// See server.Call for documentation.
type Gateway_login struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Gateway_login) Args() Gateway_login_Params {
	return Gateway_login_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Gateway_login) AllocResults() (Gateway_login_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Gateway_login_Results(r), err
}

// Gateway_capabilities holds the state for a server call to Gateway.capabilities.
// See server.Call for documentation.
type Gateway_capabilities struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Gateway_capabilities) Args() Gateway_capabilities_Params {
	return Gateway_capabilities_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Gateway_capabilities) AllocResults() (Gateway_capabilities_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Gateway_capabilities_Results(r), err
}

// Gateway_List is a list of Gateway.
type Gateway_List = capnp.CapList[Gateway]

// NewGateway creates a new list of Gateway.
func NewGateway_List(s *capnp.Segment, sz int32) (Gateway_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Gateway](l), err
}

type Gateway_login_Params capnp.Struct

// Gateway_login_Params_TypeID is the unique identifier for the type Gateway_login_Params.
const Gateway_login_Params_TypeID = 0xb3dc61f56f39dbdd

func NewGateway_login_Params(s *capnp.Segment) (Gateway_login_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Gateway_login_Params(st), err
}

func NewRootGateway_login_Params(s *capnp.Segment) (Gateway_login_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Gateway_login_Params(st), err
}

func ReadRootGateway_login_Params(msg *capnp.Message) (Gateway_login_Params, error) {
	root, err := msg.Root()
	return Gateway_login_Params(root.Struct()), err
}

func (s Gateway_login_Params) String() string {
	str, _ := text.Marshal(0xb3dc61f56f39dbdd, capnp.Struct(s))
	return str
}

func (s Gateway_login_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Gateway_login_Params) DecodeFromPtr(p capnp.Ptr) Gateway_login_Params {
	return Gateway_login_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Gateway_login_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Gateway_login_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Gateway_login_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Gateway_login_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Gateway_login_Params) ClientID() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Gateway_login_Params) HasClientID() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Gateway_login_Params) ClientIDBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Gateway_login_Params) SetClientID(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Gateway_login_Params) Password() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Gateway_login_Params) HasPassword() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Gateway_login_Params) PasswordBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Gateway_login_Params) SetPassword(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// Gateway_login_Params_List is a list of Gateway_login_Params.
type Gateway_login_Params_List = capnp.StructList[Gateway_login_Params]

// NewGateway_login_Params creates a new list of Gateway_login_Params.
func NewGateway_login_Params_List(s *capnp.Segment, sz int32) (Gateway_login_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[Gateway_login_Params](l), err
}

// Gateway_login_Params_Future is a wrapper for a Gateway_login_Params promised by a client call.
type Gateway_login_Params_Future struct{ *capnp.Future }

func (p Gateway_login_Params_Future) Struct() (Gateway_login_Params, error) {
	s, err := p.Future.Struct()
	return Gateway_login_Params(s), err
}

type Gateway_login_Results capnp.Struct

// Gateway_login_Results_TypeID is the unique identifier for the type Gateway_login_Results.
const Gateway_login_Results_TypeID = 0x9838f96648ca7264

func NewGateway_login_Results(s *capnp.Segment) (Gateway_login_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Gateway_login_Results(st), err
}

func NewRootGateway_login_Results(s *capnp.Segment) (Gateway_login_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Gateway_login_Results(st), err
}

func ReadRootGateway_login_Results(msg *capnp.Message) (Gateway_login_Results, error) {
	root, err := msg.Root()
	return Gateway_login_Results(root.Struct()), err
}

func (s Gateway_login_Results) String() string {
	str, _ := text.Marshal(0x9838f96648ca7264, capnp.Struct(s))
	return str
}

func (s Gateway_login_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Gateway_login_Results) DecodeFromPtr(p capnp.Ptr) Gateway_login_Results {
	return Gateway_login_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Gateway_login_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Gateway_login_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Gateway_login_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Gateway_login_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Gateway_login_Results) ClientCertPEM() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Gateway_login_Results) HasClientCertPEM() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Gateway_login_Results) ClientCertPEMBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Gateway_login_Results) SetClientCertPEM(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// Gateway_login_Results_List is a list of Gateway_login_Results.
type Gateway_login_Results_List = capnp.StructList[Gateway_login_Results]

// NewGateway_login_Results creates a new list of Gateway_login_Results.
func NewGateway_login_Results_List(s *capnp.Segment, sz int32) (Gateway_login_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Gateway_login_Results](l), err
}

// Gateway_login_Results_Future is a wrapper for a Gateway_login_Results promised by a client call.
type Gateway_login_Results_Future struct{ *capnp.Future }

func (p Gateway_login_Results_Future) Struct() (Gateway_login_Results, error) {
	s, err := p.Future.Struct()
	return Gateway_login_Results(s), err
}

type Gateway_capabilities_Params capnp.Struct

// Gateway_capabilities_Params_TypeID is the unique identifier for the type Gateway_capabilities_Params.
const Gateway_capabilities_Params_TypeID = 0x87103ac78ef7acf7

func NewGateway_capabilities_Params(s *capnp.Segment) (Gateway_capabilities_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Gateway_capabilities_Params(st), err
}

func NewRootGateway_capabilities_Params(s *capnp.Segment) (Gateway_capabilities_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Gateway_capabilities_Params(st), err
}

func ReadRootGateway_capabilities_Params(msg *capnp.Message) (Gateway_capabilities_Params, error) {
	root, err := msg.Root()
	return Gateway_capabilities_Params(root.Struct()), err
}

func (s Gateway_capabilities_Params) String() string {
	str, _ := text.Marshal(0x87103ac78ef7acf7, capnp.Struct(s))
	return str
}

func (s Gateway_capabilities_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Gateway_capabilities_Params) DecodeFromPtr(p capnp.Ptr) Gateway_capabilities_Params {
	return Gateway_capabilities_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Gateway_capabilities_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Gateway_capabilities_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Gateway_capabilities_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Gateway_capabilities_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Gateway_capabilities_Params_List is a list of Gateway_capabilities_Params.
type Gateway_capabilities_Params_List = capnp.StructList[Gateway_capabilities_Params]

// NewGateway_capabilities_Params creates a new list of Gateway_capabilities_Params.
func NewGateway_capabilities_Params_List(s *capnp.Segment, sz int32) (Gateway_capabilities_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Gateway_capabilities_Params](l), err
}

// Gateway_capabilities_Params_Future is a wrapper for a Gateway_capabilities_Params promised by a client call.
type Gateway_capabilities_Params_Future struct{ *capnp.Future }

func (p Gateway_capabilities_Params_Future) Struct() (Gateway_capabilities_Params, error) {
	s, err := p.Future.Struct()
	return Gateway_capabilities_Params(s), err
}

type Gateway_capabilities_Results capnp.Struct

// Gateway_capabilities_Results_TypeID is the unique identifier for the type Gateway_capabilities_Results.
const Gateway_capabilities_Results_TypeID = 0xfb8d66387b9cc035

func NewGateway_capabilities_Results(s *capnp.Segment) (Gateway_capabilities_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Gateway_capabilities_Results(st), err
}

func NewRootGateway_capabilities_Results(s *capnp.Segment) (Gateway_capabilities_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Gateway_capabilities_Results(st), err
}

func ReadRootGateway_capabilities_Results(msg *capnp.Message) (Gateway_capabilities_Results, error) {
	root, err := msg.Root()
	return Gateway_capabilities_Results(root.Struct()), err
}

func (s Gateway_capabilities_Results) String() string {
	str, _ := text.Marshal(0xfb8d66387b9cc035, capnp.Struct(s))
	return str
}

func (s Gateway_capabilities_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Gateway_capabilities_Results) DecodeFromPtr(p capnp.Ptr) Gateway_capabilities_Results {
	return Gateway_capabilities_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Gateway_capabilities_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Gateway_capabilities_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Gateway_capabilities_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Gateway_capabilities_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Gateway_capabilities_Results) ClientCap() (ClientCapabilities, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return ClientCapabilities(p.Struct()), err
}

func (s Gateway_capabilities_Results) HasClientCap() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Gateway_capabilities_Results) SetClientCap(v ClientCapabilities) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewClientCap sets the clientCap field to a newly
// allocated ClientCapabilities struct, preferring placement in s's segment.
func (s Gateway_capabilities_Results) NewClientCap() (ClientCapabilities, error) {
	ss, err := NewClientCapabilities(capnp.Struct(s).Segment())
	if err != nil {
		return ClientCapabilities{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Gateway_capabilities_Results_List is a list of Gateway_capabilities_Results.
type Gateway_capabilities_Results_List = capnp.StructList[Gateway_capabilities_Results]

// NewGateway_capabilities_Results creates a new list of Gateway_capabilities_Results.
func NewGateway_capabilities_Results_List(s *capnp.Segment, sz int32) (Gateway_capabilities_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Gateway_capabilities_Results](l), err
}

// Gateway_capabilities_Results_Future is a wrapper for a Gateway_capabilities_Results promised by a client call.
type Gateway_capabilities_Results_Future struct{ *capnp.Future }

func (p Gateway_capabilities_Results_Future) Struct() (Gateway_capabilities_Results, error) {
	s, err := p.Future.Struct()
	return Gateway_capabilities_Results(s), err
}

func (p Gateway_capabilities_Results_Future) ClientCap() ClientCapabilities_Future {
	return ClientCapabilities_Future{Future: p.Future.Field(0, nil)}
}

const schema_dd3a962266ddd0e3 = "x\xda\x8c\x93Oh\x13K\x1c\xc7\xbf\xbf\x99\xcdK7" +
	"mi\xa6\xe9{<E\x88J+VP\x1b\xb5P\x83" +
	"\x90b\x15\xdb\x82\x90I\xf5\xe0Ap\x9bn\xeb\x964" +
	"\xbb\xee\xae\xa9Qo\x0a\xb5B=\x08\x8a\x07\xf1\xe6A" +
	"\x10<\xf4\xe4M\xe9A,\x0a\xa2'\xb5=y\xf0\xa6" +
	" h\x11\x0f#\x936\xdb\xe0?\xbc\xed\x0c\x9f\xfd~" +
	"~\x7fv{\xd2\xbc\xdf\xc8\xb4~l\x07\x93K\xb1\x7f" +
	"\xd4\xca\xfd\x95kO\xb2\xc9\x19\x88\x8d\x04\x18q`\xef" +
	"I\xd3'\x18\xaa\xe7\xdel\xe2\xf9\xb6\xab\xd7!\xda\xb9" +
	"z\xf7by|\xeb\xcd\xec2@\xa9!\xf3e\xea\xb8" +
	"\x19\x07R\xd2\x9cI\xdd\xd5Oj\xcc_\x1c\x1c\xff\xda" +
	"wk5&F:g\xce<H\xa0\xd4\x0d3\x07R" +
	"\xcbo\xf7\xbb\x9f\xad\xa5\xf95\x80i\xe0\xa1\x99\xd5\xc0" +
	"cs\x1a\xa4\xe2\x1f\xae<]\xf8\xd4\xf5\x05\xa2\x9d\xd6" +
	"u\xb1ZE]\x89\x1d\x94\xeaMhe&\xf1\x1e\xa4" +
	"z\x1f\xdd\xbe\xd07>\xf7\xadQ\xf7o\xf3y\x9d\xb6" +
	"\xa59\x07\x05\x85M*\xa8\x14w\x1f\xb1B\xdb\x98\xb6" +
	"\xaa\xbb\x8a\x96W\xf6\xb2\xfa\xb8v\xb2F\x9d\x92\x13:" +
	"v\xd0\x99O[\xbe5\x15D<\xfb\x91\xa7j\x9eH" +
	"6\xf1\x18\x10\xf5A\xf5\x8eEf\x0f\x98\xe8\x8a\x13E" +
	"\xb3\xa4zyb\xc3$\x98\x10\xf1t\xc9\x9dp\xca\xfd" +
	"\xa4\xea^\xb4is?\xe5\x89\xfeTf\xed\xb5\xce\x82" +
	"\x1d\x9c-\x85\x01\xa4\xc1\x0d\xc0 @\xb4\xfa\x80l\xe1" +
	"$\xffg\xa4\x8a%\xc7.\x87\x036\xd2~\x98?|" +
	"\x94Z\xc0\xa8\x05\xeb\xc1\xfcw\xc1\xb9|\xadq\xd9\x14" +
	"\xe5v\x0f\x03r;'\xb9\x8f\x91 \xea }\x99\xd1" +
	"\x97=\x9c\xe4\x81H6t\x08@$\xf2\xac \x98v" +
	"\xfd\xb1\xc6\xbb_\xc8\x07V\xeb\\\x1bAm\x02z\xae" +
	"\xc9\xc8n\x15\x00y\x8a\x93,5\xd8\x9dI@\x9e\xe6" +
	"$CF\x82\xb1\x0eb\x808\xa3\xfb\xf78\xc9\x8b\x8c" +
	"\x04\xe7\x1d\xc4\x01Q\xd5\xe49N\xf22#5\xe6\xf8" +
	"v1t}P\x95\x84\x9a\x1d\x19\x99\xda\xdc\xfb\xdf\x1b" +
	"\x80H\x80\x94]\xb1\xcb\xe1\xa0\x13\xa0-t}\x0d\xc8" +
	"\xd7\xc7*\x89g\xc9\x07u\xc0\xf3]\xcf\xf6\xc3*\xd2" +
	"#\xa1\xeb\xdb$\xd4\xe8\x09\xd1zgax\xb1\x81\xa8" +
	"8\x81\xe3\xa2\xad\xec\x94'H\xa8\x95K\xf3;\x8d\xee" +
	"\xc1Wu\xe0o?\xbfBnu\xbf\x8d\xeb-\xfc\xbc" +
	"^\x0b\xe4Qr\xfd7\x01Q\x12\xf4=\x00\x00\xff\xff" +
	"\xbb\xf5\x12\xed"

func init() {
	schemas.Register(schema_dd3a962266ddd0e3,
		0x87103ac78ef7acf7,
		0x928a26cd0a89a930,
		0x9838f96648ca7264,
		0xb3dc61f56f39dbdd,
		0xf625f2c3c988ee07,
		0xfb8d66387b9cc035)
}
