# State.yaml - configuration file for the state storage.

# backend storage to use. Options are: 'kvstore'
# backend: kvstore

# Name of the database in the backend database. Default 'hubstate'
# Can be changed if two hubs share the same backend
# databaseName: "hubstate"
# databaseURL: "stores/state.json"  # in the stores folder
