// Code generated by capnpc-go. DO NOT EDIT.

package hubapi

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
)

type KeyValueMap capnp.Struct

// KeyValueMap_TypeID is the unique identifier for the type KeyValueMap.
const KeyValueMap_TypeID = 0xf5b8f559366e8d7d

func NewKeyValueMap(s *capnp.Segment) (KeyValueMap, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return KeyValueMap(st), err
}

func NewRootKeyValueMap(s *capnp.Segment) (KeyValueMap, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return KeyValueMap(st), err
}

func ReadRootKeyValueMap(msg *capnp.Message) (KeyValueMap, error) {
	root, err := msg.Root()
	return KeyValueMap(root.Struct()), err
}

func (s KeyValueMap) String() string {
	str, _ := text.Marshal(0xf5b8f559366e8d7d, capnp.Struct(s))
	return str
}

func (s KeyValueMap) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (KeyValueMap) DecodeFromPtr(p capnp.Ptr) KeyValueMap {
	return KeyValueMap(capnp.Struct{}.DecodeFromPtr(p))
}

func (s KeyValueMap) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s KeyValueMap) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s KeyValueMap) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s KeyValueMap) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s KeyValueMap) Entries() (KeyValueMap_Entry_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return KeyValueMap_Entry_List(p.List()), err
}

func (s KeyValueMap) HasEntries() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s KeyValueMap) SetEntries(v KeyValueMap_Entry_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewEntries sets the entries field to a newly
// allocated KeyValueMap_Entry_List, preferring placement in s's segment.
func (s KeyValueMap) NewEntries(n int32) (KeyValueMap_Entry_List, error) {
	l, err := NewKeyValueMap_Entry_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return KeyValueMap_Entry_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// KeyValueMap_List is a list of KeyValueMap.
type KeyValueMap_List = capnp.StructList[KeyValueMap]

// NewKeyValueMap creates a new list of KeyValueMap.
func NewKeyValueMap_List(s *capnp.Segment, sz int32) (KeyValueMap_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[KeyValueMap](l), err
}

// KeyValueMap_Future is a wrapper for a KeyValueMap promised by a client call.
type KeyValueMap_Future struct{ *capnp.Future }

func (p KeyValueMap_Future) Struct() (KeyValueMap, error) {
	s, err := p.Future.Struct()
	return KeyValueMap(s), err
}

type KeyValueMap_Entry capnp.Struct

// KeyValueMap_Entry_TypeID is the unique identifier for the type KeyValueMap_Entry.
const KeyValueMap_Entry_TypeID = 0xd929beeebbbcb3a1

func NewKeyValueMap_Entry(s *capnp.Segment) (KeyValueMap_Entry, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return KeyValueMap_Entry(st), err
}

func NewRootKeyValueMap_Entry(s *capnp.Segment) (KeyValueMap_Entry, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return KeyValueMap_Entry(st), err
}

func ReadRootKeyValueMap_Entry(msg *capnp.Message) (KeyValueMap_Entry, error) {
	root, err := msg.Root()
	return KeyValueMap_Entry(root.Struct()), err
}

func (s KeyValueMap_Entry) String() string {
	str, _ := text.Marshal(0xd929beeebbbcb3a1, capnp.Struct(s))
	return str
}

func (s KeyValueMap_Entry) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (KeyValueMap_Entry) DecodeFromPtr(p capnp.Ptr) KeyValueMap_Entry {
	return KeyValueMap_Entry(capnp.Struct{}.DecodeFromPtr(p))
}

func (s KeyValueMap_Entry) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s KeyValueMap_Entry) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s KeyValueMap_Entry) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s KeyValueMap_Entry) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s KeyValueMap_Entry) Key() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s KeyValueMap_Entry) HasKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s KeyValueMap_Entry) KeyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s KeyValueMap_Entry) SetKey(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s KeyValueMap_Entry) Value() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s KeyValueMap_Entry) HasValue() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s KeyValueMap_Entry) SetValue(v []byte) error {
	return capnp.Struct(s).SetData(1, v)
}

// KeyValueMap_Entry_List is a list of KeyValueMap_Entry.
type KeyValueMap_Entry_List = capnp.StructList[KeyValueMap_Entry]

// NewKeyValueMap_Entry creates a new list of KeyValueMap_Entry.
func NewKeyValueMap_Entry_List(s *capnp.Segment, sz int32) (KeyValueMap_Entry_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[KeyValueMap_Entry](l), err
}

// KeyValueMap_Entry_Future is a wrapper for a KeyValueMap_Entry promised by a client call.
type KeyValueMap_Entry_Future struct{ *capnp.Future }

func (p KeyValueMap_Entry_Future) Struct() (KeyValueMap_Entry, error) {
	s, err := p.Future.Struct()
	return KeyValueMap_Entry(s), err
}

type CapBucketCursor capnp.Client

// CapBucketCursor_TypeID is the unique identifier for the type CapBucketCursor.
const CapBucketCursor_TypeID = 0xa11bc07e0c80620f

func (c CapBucketCursor) First(ctx context.Context, params func(CapBucketCursor_first_Params) error) (CapBucketCursor_first_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xa11bc07e0c80620f,
			MethodID:      0,
			InterfaceName: "hubapi/Bucket.capnp:CapBucketCursor",
			MethodName:    "first",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CapBucketCursor_first_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CapBucketCursor_first_Results_Future{Future: ans.Future()}, release
}
func (c CapBucketCursor) Last(ctx context.Context, params func(CapBucketCursor_last_Params) error) (CapBucketCursor_last_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xa11bc07e0c80620f,
			MethodID:      1,
			InterfaceName: "hubapi/Bucket.capnp:CapBucketCursor",
			MethodName:    "last",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CapBucketCursor_last_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CapBucketCursor_last_Results_Future{Future: ans.Future()}, release
}
func (c CapBucketCursor) Next(ctx context.Context, params func(CapBucketCursor_next_Params) error) (CapBucketCursor_next_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xa11bc07e0c80620f,
			MethodID:      2,
			InterfaceName: "hubapi/Bucket.capnp:CapBucketCursor",
			MethodName:    "next",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CapBucketCursor_next_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CapBucketCursor_next_Results_Future{Future: ans.Future()}, release
}
func (c CapBucketCursor) NextN(ctx context.Context, params func(CapBucketCursor_nextN_Params) error) (CapBucketCursor_nextN_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xa11bc07e0c80620f,
			MethodID:      3,
			InterfaceName: "hubapi/Bucket.capnp:CapBucketCursor",
			MethodName:    "nextN",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CapBucketCursor_nextN_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CapBucketCursor_nextN_Results_Future{Future: ans.Future()}, release
}
func (c CapBucketCursor) Prev(ctx context.Context, params func(CapBucketCursor_prev_Params) error) (CapBucketCursor_prev_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xa11bc07e0c80620f,
			MethodID:      4,
			InterfaceName: "hubapi/Bucket.capnp:CapBucketCursor",
			MethodName:    "prev",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CapBucketCursor_prev_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CapBucketCursor_prev_Results_Future{Future: ans.Future()}, release
}
func (c CapBucketCursor) PrevN(ctx context.Context, params func(CapBucketCursor_prevN_Params) error) (CapBucketCursor_prevN_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xa11bc07e0c80620f,
			MethodID:      5,
			InterfaceName: "hubapi/Bucket.capnp:CapBucketCursor",
			MethodName:    "prevN",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CapBucketCursor_prevN_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CapBucketCursor_prevN_Results_Future{Future: ans.Future()}, release
}
func (c CapBucketCursor) Seek(ctx context.Context, params func(CapBucketCursor_seek_Params) error) (CapBucketCursor_seek_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xa11bc07e0c80620f,
			MethodID:      6,
			InterfaceName: "hubapi/Bucket.capnp:CapBucketCursor",
			MethodName:    "seek",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CapBucketCursor_seek_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CapBucketCursor_seek_Results_Future{Future: ans.Future()}, release
}

func (c CapBucketCursor) AddRef() CapBucketCursor {
	return CapBucketCursor(capnp.Client(c).AddRef())
}

func (c CapBucketCursor) Release() {
	capnp.Client(c).Release()
}

func (c CapBucketCursor) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (CapBucketCursor) DecodeFromPtr(p capnp.Ptr) CapBucketCursor {
	return CapBucketCursor(capnp.Client{}.DecodeFromPtr(p))
}

func (c CapBucketCursor) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// A CapBucketCursor_Server is a CapBucketCursor with a local implementation.
type CapBucketCursor_Server interface {
	First(context.Context, CapBucketCursor_first) error

	Last(context.Context, CapBucketCursor_last) error

	Next(context.Context, CapBucketCursor_next) error

	NextN(context.Context, CapBucketCursor_nextN) error

	Prev(context.Context, CapBucketCursor_prev) error

	PrevN(context.Context, CapBucketCursor_prevN) error

	Seek(context.Context, CapBucketCursor_seek) error
}

// CapBucketCursor_NewServer creates a new Server from an implementation of CapBucketCursor_Server.
func CapBucketCursor_NewServer(s CapBucketCursor_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(CapBucketCursor_Methods(nil, s), s, c)
}

// CapBucketCursor_ServerToClient creates a new Client from an implementation of CapBucketCursor_Server.
// The caller is responsible for calling Release on the returned Client.
func CapBucketCursor_ServerToClient(s CapBucketCursor_Server) CapBucketCursor {
	return CapBucketCursor(capnp.NewClient(CapBucketCursor_NewServer(s)))
}

// CapBucketCursor_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func CapBucketCursor_Methods(methods []server.Method, s CapBucketCursor_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 7)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xa11bc07e0c80620f,
			MethodID:      0,
			InterfaceName: "hubapi/Bucket.capnp:CapBucketCursor",
			MethodName:    "first",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.First(ctx, CapBucketCursor_first{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xa11bc07e0c80620f,
			MethodID:      1,
			InterfaceName: "hubapi/Bucket.capnp:CapBucketCursor",
			MethodName:    "last",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Last(ctx, CapBucketCursor_last{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xa11bc07e0c80620f,
			MethodID:      2,
			InterfaceName: "hubapi/Bucket.capnp:CapBucketCursor",
			MethodName:    "next",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Next(ctx, CapBucketCursor_next{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xa11bc07e0c80620f,
			MethodID:      3,
			InterfaceName: "hubapi/Bucket.capnp:CapBucketCursor",
			MethodName:    "nextN",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.NextN(ctx, CapBucketCursor_nextN{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xa11bc07e0c80620f,
			MethodID:      4,
			InterfaceName: "hubapi/Bucket.capnp:CapBucketCursor",
			MethodName:    "prev",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Prev(ctx, CapBucketCursor_prev{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xa11bc07e0c80620f,
			MethodID:      5,
			InterfaceName: "hubapi/Bucket.capnp:CapBucketCursor",
			MethodName:    "prevN",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.PrevN(ctx, CapBucketCursor_prevN{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xa11bc07e0c80620f,
			MethodID:      6,
			InterfaceName: "hubapi/Bucket.capnp:CapBucketCursor",
			MethodName:    "seek",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Seek(ctx, CapBucketCursor_seek{call})
		},
	})

	return methods
}

// CapBucketCursor_first holds the state for a server call to CapBucketCursor.first.
// See server.Call for documentation.
type CapBucketCursor_first struct {
	*server.Call
}

// Args returns the call's arguments.
func (c CapBucketCursor_first) Args() CapBucketCursor_first_Params {
	return CapBucketCursor_first_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c CapBucketCursor_first) AllocResults() (CapBucketCursor_first_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CapBucketCursor_first_Results(r), err
}

// CapBucketCursor_last holds the state for a server call to CapBucketCursor.last.
// See server.Call for documentation.
type CapBucketCursor_last struct {
	*server.Call
}

// Args returns the call's arguments.
func (c CapBucketCursor_last) Args() CapBucketCursor_last_Params {
	return CapBucketCursor_last_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c CapBucketCursor_last) AllocResults() (CapBucketCursor_last_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CapBucketCursor_last_Results(r), err
}

// CapBucketCursor_next holds the state for a server call to CapBucketCursor.next.
// See server.Call for documentation.
type CapBucketCursor_next struct {
	*server.Call
}

// Args returns the call's arguments.
func (c CapBucketCursor_next) Args() CapBucketCursor_next_Params {
	return CapBucketCursor_next_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c CapBucketCursor_next) AllocResults() (CapBucketCursor_next_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CapBucketCursor_next_Results(r), err
}

// CapBucketCursor_nextN holds the state for a server call to CapBucketCursor.nextN.
// See server.Call for documentation.
type CapBucketCursor_nextN struct {
	*server.Call
}

// Args returns the call's arguments.
func (c CapBucketCursor_nextN) Args() CapBucketCursor_nextN_Params {
	return CapBucketCursor_nextN_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c CapBucketCursor_nextN) AllocResults() (CapBucketCursor_nextN_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return CapBucketCursor_nextN_Results(r), err
}

// CapBucketCursor_prev holds the state for a server call to CapBucketCursor.prev.
// See server.Call for documentation.
type CapBucketCursor_prev struct {
	*server.Call
}

// Args returns the call's arguments.
func (c CapBucketCursor_prev) Args() CapBucketCursor_prev_Params {
	return CapBucketCursor_prev_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c CapBucketCursor_prev) AllocResults() (CapBucketCursor_prev_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CapBucketCursor_prev_Results(r), err
}

// CapBucketCursor_prevN holds the state for a server call to CapBucketCursor.prevN.
// See server.Call for documentation.
type CapBucketCursor_prevN struct {
	*server.Call
}

// Args returns the call's arguments.
func (c CapBucketCursor_prevN) Args() CapBucketCursor_prevN_Params {
	return CapBucketCursor_prevN_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c CapBucketCursor_prevN) AllocResults() (CapBucketCursor_prevN_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return CapBucketCursor_prevN_Results(r), err
}

// CapBucketCursor_seek holds the state for a server call to CapBucketCursor.seek.
// See server.Call for documentation.
type CapBucketCursor_seek struct {
	*server.Call
}

// Args returns the call's arguments.
func (c CapBucketCursor_seek) Args() CapBucketCursor_seek_Params {
	return CapBucketCursor_seek_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c CapBucketCursor_seek) AllocResults() (CapBucketCursor_seek_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CapBucketCursor_seek_Results(r), err
}

// CapBucketCursor_List is a list of CapBucketCursor.
type CapBucketCursor_List = capnp.CapList[CapBucketCursor]

// NewCapBucketCursor creates a new list of CapBucketCursor.
func NewCapBucketCursor_List(s *capnp.Segment, sz int32) (CapBucketCursor_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[CapBucketCursor](l), err
}

type CapBucketCursor_first_Params capnp.Struct

// CapBucketCursor_first_Params_TypeID is the unique identifier for the type CapBucketCursor_first_Params.
const CapBucketCursor_first_Params_TypeID = 0xa68d3c040a138fc4

func NewCapBucketCursor_first_Params(s *capnp.Segment) (CapBucketCursor_first_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CapBucketCursor_first_Params(st), err
}

func NewRootCapBucketCursor_first_Params(s *capnp.Segment) (CapBucketCursor_first_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CapBucketCursor_first_Params(st), err
}

func ReadRootCapBucketCursor_first_Params(msg *capnp.Message) (CapBucketCursor_first_Params, error) {
	root, err := msg.Root()
	return CapBucketCursor_first_Params(root.Struct()), err
}

func (s CapBucketCursor_first_Params) String() string {
	str, _ := text.Marshal(0xa68d3c040a138fc4, capnp.Struct(s))
	return str
}

func (s CapBucketCursor_first_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapBucketCursor_first_Params) DecodeFromPtr(p capnp.Ptr) CapBucketCursor_first_Params {
	return CapBucketCursor_first_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapBucketCursor_first_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapBucketCursor_first_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapBucketCursor_first_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapBucketCursor_first_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CapBucketCursor_first_Params_List is a list of CapBucketCursor_first_Params.
type CapBucketCursor_first_Params_List = capnp.StructList[CapBucketCursor_first_Params]

// NewCapBucketCursor_first_Params creates a new list of CapBucketCursor_first_Params.
func NewCapBucketCursor_first_Params_List(s *capnp.Segment, sz int32) (CapBucketCursor_first_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CapBucketCursor_first_Params](l), err
}

// CapBucketCursor_first_Params_Future is a wrapper for a CapBucketCursor_first_Params promised by a client call.
type CapBucketCursor_first_Params_Future struct{ *capnp.Future }

func (p CapBucketCursor_first_Params_Future) Struct() (CapBucketCursor_first_Params, error) {
	s, err := p.Future.Struct()
	return CapBucketCursor_first_Params(s), err
}

type CapBucketCursor_first_Results capnp.Struct

// CapBucketCursor_first_Results_TypeID is the unique identifier for the type CapBucketCursor_first_Results.
const CapBucketCursor_first_Results_TypeID = 0x92163fe8dfbba335

func NewCapBucketCursor_first_Results(s *capnp.Segment) (CapBucketCursor_first_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CapBucketCursor_first_Results(st), err
}

func NewRootCapBucketCursor_first_Results(s *capnp.Segment) (CapBucketCursor_first_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CapBucketCursor_first_Results(st), err
}

func ReadRootCapBucketCursor_first_Results(msg *capnp.Message) (CapBucketCursor_first_Results, error) {
	root, err := msg.Root()
	return CapBucketCursor_first_Results(root.Struct()), err
}

func (s CapBucketCursor_first_Results) String() string {
	str, _ := text.Marshal(0x92163fe8dfbba335, capnp.Struct(s))
	return str
}

func (s CapBucketCursor_first_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapBucketCursor_first_Results) DecodeFromPtr(p capnp.Ptr) CapBucketCursor_first_Results {
	return CapBucketCursor_first_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapBucketCursor_first_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapBucketCursor_first_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapBucketCursor_first_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapBucketCursor_first_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapBucketCursor_first_Results) Key() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CapBucketCursor_first_Results) HasKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CapBucketCursor_first_Results) KeyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CapBucketCursor_first_Results) SetKey(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s CapBucketCursor_first_Results) Value() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s CapBucketCursor_first_Results) HasValue() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s CapBucketCursor_first_Results) SetValue(v []byte) error {
	return capnp.Struct(s).SetData(1, v)
}

// CapBucketCursor_first_Results_List is a list of CapBucketCursor_first_Results.
type CapBucketCursor_first_Results_List = capnp.StructList[CapBucketCursor_first_Results]

// NewCapBucketCursor_first_Results creates a new list of CapBucketCursor_first_Results.
func NewCapBucketCursor_first_Results_List(s *capnp.Segment, sz int32) (CapBucketCursor_first_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[CapBucketCursor_first_Results](l), err
}

// CapBucketCursor_first_Results_Future is a wrapper for a CapBucketCursor_first_Results promised by a client call.
type CapBucketCursor_first_Results_Future struct{ *capnp.Future }

func (p CapBucketCursor_first_Results_Future) Struct() (CapBucketCursor_first_Results, error) {
	s, err := p.Future.Struct()
	return CapBucketCursor_first_Results(s), err
}

type CapBucketCursor_last_Params capnp.Struct

// CapBucketCursor_last_Params_TypeID is the unique identifier for the type CapBucketCursor_last_Params.
const CapBucketCursor_last_Params_TypeID = 0x85be05195246e76a

func NewCapBucketCursor_last_Params(s *capnp.Segment) (CapBucketCursor_last_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CapBucketCursor_last_Params(st), err
}

func NewRootCapBucketCursor_last_Params(s *capnp.Segment) (CapBucketCursor_last_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CapBucketCursor_last_Params(st), err
}

func ReadRootCapBucketCursor_last_Params(msg *capnp.Message) (CapBucketCursor_last_Params, error) {
	root, err := msg.Root()
	return CapBucketCursor_last_Params(root.Struct()), err
}

func (s CapBucketCursor_last_Params) String() string {
	str, _ := text.Marshal(0x85be05195246e76a, capnp.Struct(s))
	return str
}

func (s CapBucketCursor_last_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapBucketCursor_last_Params) DecodeFromPtr(p capnp.Ptr) CapBucketCursor_last_Params {
	return CapBucketCursor_last_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapBucketCursor_last_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapBucketCursor_last_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapBucketCursor_last_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapBucketCursor_last_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CapBucketCursor_last_Params_List is a list of CapBucketCursor_last_Params.
type CapBucketCursor_last_Params_List = capnp.StructList[CapBucketCursor_last_Params]

// NewCapBucketCursor_last_Params creates a new list of CapBucketCursor_last_Params.
func NewCapBucketCursor_last_Params_List(s *capnp.Segment, sz int32) (CapBucketCursor_last_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CapBucketCursor_last_Params](l), err
}

// CapBucketCursor_last_Params_Future is a wrapper for a CapBucketCursor_last_Params promised by a client call.
type CapBucketCursor_last_Params_Future struct{ *capnp.Future }

func (p CapBucketCursor_last_Params_Future) Struct() (CapBucketCursor_last_Params, error) {
	s, err := p.Future.Struct()
	return CapBucketCursor_last_Params(s), err
}

type CapBucketCursor_last_Results capnp.Struct

// CapBucketCursor_last_Results_TypeID is the unique identifier for the type CapBucketCursor_last_Results.
const CapBucketCursor_last_Results_TypeID = 0xbec9f2412880c3c4

func NewCapBucketCursor_last_Results(s *capnp.Segment) (CapBucketCursor_last_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CapBucketCursor_last_Results(st), err
}

func NewRootCapBucketCursor_last_Results(s *capnp.Segment) (CapBucketCursor_last_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CapBucketCursor_last_Results(st), err
}

func ReadRootCapBucketCursor_last_Results(msg *capnp.Message) (CapBucketCursor_last_Results, error) {
	root, err := msg.Root()
	return CapBucketCursor_last_Results(root.Struct()), err
}

func (s CapBucketCursor_last_Results) String() string {
	str, _ := text.Marshal(0xbec9f2412880c3c4, capnp.Struct(s))
	return str
}

func (s CapBucketCursor_last_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapBucketCursor_last_Results) DecodeFromPtr(p capnp.Ptr) CapBucketCursor_last_Results {
	return CapBucketCursor_last_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapBucketCursor_last_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapBucketCursor_last_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapBucketCursor_last_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapBucketCursor_last_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapBucketCursor_last_Results) Key() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CapBucketCursor_last_Results) HasKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CapBucketCursor_last_Results) KeyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CapBucketCursor_last_Results) SetKey(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s CapBucketCursor_last_Results) Value() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s CapBucketCursor_last_Results) HasValue() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s CapBucketCursor_last_Results) SetValue(v []byte) error {
	return capnp.Struct(s).SetData(1, v)
}

// CapBucketCursor_last_Results_List is a list of CapBucketCursor_last_Results.
type CapBucketCursor_last_Results_List = capnp.StructList[CapBucketCursor_last_Results]

// NewCapBucketCursor_last_Results creates a new list of CapBucketCursor_last_Results.
func NewCapBucketCursor_last_Results_List(s *capnp.Segment, sz int32) (CapBucketCursor_last_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[CapBucketCursor_last_Results](l), err
}

// CapBucketCursor_last_Results_Future is a wrapper for a CapBucketCursor_last_Results promised by a client call.
type CapBucketCursor_last_Results_Future struct{ *capnp.Future }

func (p CapBucketCursor_last_Results_Future) Struct() (CapBucketCursor_last_Results, error) {
	s, err := p.Future.Struct()
	return CapBucketCursor_last_Results(s), err
}

type CapBucketCursor_next_Params capnp.Struct

// CapBucketCursor_next_Params_TypeID is the unique identifier for the type CapBucketCursor_next_Params.
const CapBucketCursor_next_Params_TypeID = 0xe474a76a2f0a28aa

func NewCapBucketCursor_next_Params(s *capnp.Segment) (CapBucketCursor_next_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CapBucketCursor_next_Params(st), err
}

func NewRootCapBucketCursor_next_Params(s *capnp.Segment) (CapBucketCursor_next_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CapBucketCursor_next_Params(st), err
}

func ReadRootCapBucketCursor_next_Params(msg *capnp.Message) (CapBucketCursor_next_Params, error) {
	root, err := msg.Root()
	return CapBucketCursor_next_Params(root.Struct()), err
}

func (s CapBucketCursor_next_Params) String() string {
	str, _ := text.Marshal(0xe474a76a2f0a28aa, capnp.Struct(s))
	return str
}

func (s CapBucketCursor_next_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapBucketCursor_next_Params) DecodeFromPtr(p capnp.Ptr) CapBucketCursor_next_Params {
	return CapBucketCursor_next_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapBucketCursor_next_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapBucketCursor_next_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapBucketCursor_next_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapBucketCursor_next_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CapBucketCursor_next_Params_List is a list of CapBucketCursor_next_Params.
type CapBucketCursor_next_Params_List = capnp.StructList[CapBucketCursor_next_Params]

// NewCapBucketCursor_next_Params creates a new list of CapBucketCursor_next_Params.
func NewCapBucketCursor_next_Params_List(s *capnp.Segment, sz int32) (CapBucketCursor_next_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CapBucketCursor_next_Params](l), err
}

// CapBucketCursor_next_Params_Future is a wrapper for a CapBucketCursor_next_Params promised by a client call.
type CapBucketCursor_next_Params_Future struct{ *capnp.Future }

func (p CapBucketCursor_next_Params_Future) Struct() (CapBucketCursor_next_Params, error) {
	s, err := p.Future.Struct()
	return CapBucketCursor_next_Params(s), err
}

type CapBucketCursor_next_Results capnp.Struct

// CapBucketCursor_next_Results_TypeID is the unique identifier for the type CapBucketCursor_next_Results.
const CapBucketCursor_next_Results_TypeID = 0xf4d0d1cc3d7621b4

func NewCapBucketCursor_next_Results(s *capnp.Segment) (CapBucketCursor_next_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CapBucketCursor_next_Results(st), err
}

func NewRootCapBucketCursor_next_Results(s *capnp.Segment) (CapBucketCursor_next_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CapBucketCursor_next_Results(st), err
}

func ReadRootCapBucketCursor_next_Results(msg *capnp.Message) (CapBucketCursor_next_Results, error) {
	root, err := msg.Root()
	return CapBucketCursor_next_Results(root.Struct()), err
}

func (s CapBucketCursor_next_Results) String() string {
	str, _ := text.Marshal(0xf4d0d1cc3d7621b4, capnp.Struct(s))
	return str
}

func (s CapBucketCursor_next_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapBucketCursor_next_Results) DecodeFromPtr(p capnp.Ptr) CapBucketCursor_next_Results {
	return CapBucketCursor_next_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapBucketCursor_next_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapBucketCursor_next_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapBucketCursor_next_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapBucketCursor_next_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapBucketCursor_next_Results) Key() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CapBucketCursor_next_Results) HasKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CapBucketCursor_next_Results) KeyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CapBucketCursor_next_Results) SetKey(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s CapBucketCursor_next_Results) Value() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s CapBucketCursor_next_Results) HasValue() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s CapBucketCursor_next_Results) SetValue(v []byte) error {
	return capnp.Struct(s).SetData(1, v)
}

// CapBucketCursor_next_Results_List is a list of CapBucketCursor_next_Results.
type CapBucketCursor_next_Results_List = capnp.StructList[CapBucketCursor_next_Results]

// NewCapBucketCursor_next_Results creates a new list of CapBucketCursor_next_Results.
func NewCapBucketCursor_next_Results_List(s *capnp.Segment, sz int32) (CapBucketCursor_next_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[CapBucketCursor_next_Results](l), err
}

// CapBucketCursor_next_Results_Future is a wrapper for a CapBucketCursor_next_Results promised by a client call.
type CapBucketCursor_next_Results_Future struct{ *capnp.Future }

func (p CapBucketCursor_next_Results_Future) Struct() (CapBucketCursor_next_Results, error) {
	s, err := p.Future.Struct()
	return CapBucketCursor_next_Results(s), err
}

type CapBucketCursor_nextN_Params capnp.Struct

// CapBucketCursor_nextN_Params_TypeID is the unique identifier for the type CapBucketCursor_nextN_Params.
const CapBucketCursor_nextN_Params_TypeID = 0xb722198a741d6b09

func NewCapBucketCursor_nextN_Params(s *capnp.Segment) (CapBucketCursor_nextN_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return CapBucketCursor_nextN_Params(st), err
}

func NewRootCapBucketCursor_nextN_Params(s *capnp.Segment) (CapBucketCursor_nextN_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return CapBucketCursor_nextN_Params(st), err
}

func ReadRootCapBucketCursor_nextN_Params(msg *capnp.Message) (CapBucketCursor_nextN_Params, error) {
	root, err := msg.Root()
	return CapBucketCursor_nextN_Params(root.Struct()), err
}

func (s CapBucketCursor_nextN_Params) String() string {
	str, _ := text.Marshal(0xb722198a741d6b09, capnp.Struct(s))
	return str
}

func (s CapBucketCursor_nextN_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapBucketCursor_nextN_Params) DecodeFromPtr(p capnp.Ptr) CapBucketCursor_nextN_Params {
	return CapBucketCursor_nextN_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapBucketCursor_nextN_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapBucketCursor_nextN_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapBucketCursor_nextN_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapBucketCursor_nextN_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapBucketCursor_nextN_Params) Steps() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s CapBucketCursor_nextN_Params) SetSteps(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

// CapBucketCursor_nextN_Params_List is a list of CapBucketCursor_nextN_Params.
type CapBucketCursor_nextN_Params_List = capnp.StructList[CapBucketCursor_nextN_Params]

// NewCapBucketCursor_nextN_Params creates a new list of CapBucketCursor_nextN_Params.
func NewCapBucketCursor_nextN_Params_List(s *capnp.Segment, sz int32) (CapBucketCursor_nextN_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[CapBucketCursor_nextN_Params](l), err
}

// CapBucketCursor_nextN_Params_Future is a wrapper for a CapBucketCursor_nextN_Params promised by a client call.
type CapBucketCursor_nextN_Params_Future struct{ *capnp.Future }

func (p CapBucketCursor_nextN_Params_Future) Struct() (CapBucketCursor_nextN_Params, error) {
	s, err := p.Future.Struct()
	return CapBucketCursor_nextN_Params(s), err
}

type CapBucketCursor_nextN_Results capnp.Struct

// CapBucketCursor_nextN_Results_TypeID is the unique identifier for the type CapBucketCursor_nextN_Results.
const CapBucketCursor_nextN_Results_TypeID = 0x868c48c5a99951cf

func NewCapBucketCursor_nextN_Results(s *capnp.Segment) (CapBucketCursor_nextN_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return CapBucketCursor_nextN_Results(st), err
}

func NewRootCapBucketCursor_nextN_Results(s *capnp.Segment) (CapBucketCursor_nextN_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return CapBucketCursor_nextN_Results(st), err
}

func ReadRootCapBucketCursor_nextN_Results(msg *capnp.Message) (CapBucketCursor_nextN_Results, error) {
	root, err := msg.Root()
	return CapBucketCursor_nextN_Results(root.Struct()), err
}

func (s CapBucketCursor_nextN_Results) String() string {
	str, _ := text.Marshal(0x868c48c5a99951cf, capnp.Struct(s))
	return str
}

func (s CapBucketCursor_nextN_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapBucketCursor_nextN_Results) DecodeFromPtr(p capnp.Ptr) CapBucketCursor_nextN_Results {
	return CapBucketCursor_nextN_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapBucketCursor_nextN_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapBucketCursor_nextN_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapBucketCursor_nextN_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapBucketCursor_nextN_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapBucketCursor_nextN_Results) Docs() (KeyValueMap, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return KeyValueMap(p.Struct()), err
}

func (s CapBucketCursor_nextN_Results) HasDocs() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CapBucketCursor_nextN_Results) SetDocs(v KeyValueMap) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewDocs sets the docs field to a newly
// allocated KeyValueMap struct, preferring placement in s's segment.
func (s CapBucketCursor_nextN_Results) NewDocs() (KeyValueMap, error) {
	ss, err := NewKeyValueMap(capnp.Struct(s).Segment())
	if err != nil {
		return KeyValueMap{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s CapBucketCursor_nextN_Results) EndReached() bool {
	return capnp.Struct(s).Bit(0)
}

func (s CapBucketCursor_nextN_Results) SetEndReached(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

// CapBucketCursor_nextN_Results_List is a list of CapBucketCursor_nextN_Results.
type CapBucketCursor_nextN_Results_List = capnp.StructList[CapBucketCursor_nextN_Results]

// NewCapBucketCursor_nextN_Results creates a new list of CapBucketCursor_nextN_Results.
func NewCapBucketCursor_nextN_Results_List(s *capnp.Segment, sz int32) (CapBucketCursor_nextN_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[CapBucketCursor_nextN_Results](l), err
}

// CapBucketCursor_nextN_Results_Future is a wrapper for a CapBucketCursor_nextN_Results promised by a client call.
type CapBucketCursor_nextN_Results_Future struct{ *capnp.Future }

func (p CapBucketCursor_nextN_Results_Future) Struct() (CapBucketCursor_nextN_Results, error) {
	s, err := p.Future.Struct()
	return CapBucketCursor_nextN_Results(s), err
}

func (p CapBucketCursor_nextN_Results_Future) Docs() KeyValueMap_Future {
	return KeyValueMap_Future{Future: p.Future.Field(0, nil)}
}

type CapBucketCursor_prev_Params capnp.Struct

// CapBucketCursor_prev_Params_TypeID is the unique identifier for the type CapBucketCursor_prev_Params.
const CapBucketCursor_prev_Params_TypeID = 0x81ba0d0702530538

func NewCapBucketCursor_prev_Params(s *capnp.Segment) (CapBucketCursor_prev_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CapBucketCursor_prev_Params(st), err
}

func NewRootCapBucketCursor_prev_Params(s *capnp.Segment) (CapBucketCursor_prev_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CapBucketCursor_prev_Params(st), err
}

func ReadRootCapBucketCursor_prev_Params(msg *capnp.Message) (CapBucketCursor_prev_Params, error) {
	root, err := msg.Root()
	return CapBucketCursor_prev_Params(root.Struct()), err
}

func (s CapBucketCursor_prev_Params) String() string {
	str, _ := text.Marshal(0x81ba0d0702530538, capnp.Struct(s))
	return str
}

func (s CapBucketCursor_prev_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapBucketCursor_prev_Params) DecodeFromPtr(p capnp.Ptr) CapBucketCursor_prev_Params {
	return CapBucketCursor_prev_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapBucketCursor_prev_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapBucketCursor_prev_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapBucketCursor_prev_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapBucketCursor_prev_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CapBucketCursor_prev_Params_List is a list of CapBucketCursor_prev_Params.
type CapBucketCursor_prev_Params_List = capnp.StructList[CapBucketCursor_prev_Params]

// NewCapBucketCursor_prev_Params creates a new list of CapBucketCursor_prev_Params.
func NewCapBucketCursor_prev_Params_List(s *capnp.Segment, sz int32) (CapBucketCursor_prev_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CapBucketCursor_prev_Params](l), err
}

// CapBucketCursor_prev_Params_Future is a wrapper for a CapBucketCursor_prev_Params promised by a client call.
type CapBucketCursor_prev_Params_Future struct{ *capnp.Future }

func (p CapBucketCursor_prev_Params_Future) Struct() (CapBucketCursor_prev_Params, error) {
	s, err := p.Future.Struct()
	return CapBucketCursor_prev_Params(s), err
}

type CapBucketCursor_prev_Results capnp.Struct

// CapBucketCursor_prev_Results_TypeID is the unique identifier for the type CapBucketCursor_prev_Results.
const CapBucketCursor_prev_Results_TypeID = 0x80afad1a89a118e9

func NewCapBucketCursor_prev_Results(s *capnp.Segment) (CapBucketCursor_prev_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CapBucketCursor_prev_Results(st), err
}

func NewRootCapBucketCursor_prev_Results(s *capnp.Segment) (CapBucketCursor_prev_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CapBucketCursor_prev_Results(st), err
}

func ReadRootCapBucketCursor_prev_Results(msg *capnp.Message) (CapBucketCursor_prev_Results, error) {
	root, err := msg.Root()
	return CapBucketCursor_prev_Results(root.Struct()), err
}

func (s CapBucketCursor_prev_Results) String() string {
	str, _ := text.Marshal(0x80afad1a89a118e9, capnp.Struct(s))
	return str
}

func (s CapBucketCursor_prev_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapBucketCursor_prev_Results) DecodeFromPtr(p capnp.Ptr) CapBucketCursor_prev_Results {
	return CapBucketCursor_prev_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapBucketCursor_prev_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapBucketCursor_prev_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapBucketCursor_prev_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapBucketCursor_prev_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapBucketCursor_prev_Results) Key() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CapBucketCursor_prev_Results) HasKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CapBucketCursor_prev_Results) KeyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CapBucketCursor_prev_Results) SetKey(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s CapBucketCursor_prev_Results) Value() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s CapBucketCursor_prev_Results) HasValue() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s CapBucketCursor_prev_Results) SetValue(v []byte) error {
	return capnp.Struct(s).SetData(1, v)
}

// CapBucketCursor_prev_Results_List is a list of CapBucketCursor_prev_Results.
type CapBucketCursor_prev_Results_List = capnp.StructList[CapBucketCursor_prev_Results]

// NewCapBucketCursor_prev_Results creates a new list of CapBucketCursor_prev_Results.
func NewCapBucketCursor_prev_Results_List(s *capnp.Segment, sz int32) (CapBucketCursor_prev_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[CapBucketCursor_prev_Results](l), err
}

// CapBucketCursor_prev_Results_Future is a wrapper for a CapBucketCursor_prev_Results promised by a client call.
type CapBucketCursor_prev_Results_Future struct{ *capnp.Future }

func (p CapBucketCursor_prev_Results_Future) Struct() (CapBucketCursor_prev_Results, error) {
	s, err := p.Future.Struct()
	return CapBucketCursor_prev_Results(s), err
}

type CapBucketCursor_prevN_Params capnp.Struct

// CapBucketCursor_prevN_Params_TypeID is the unique identifier for the type CapBucketCursor_prevN_Params.
const CapBucketCursor_prevN_Params_TypeID = 0xd1d62e51cc686764

func NewCapBucketCursor_prevN_Params(s *capnp.Segment) (CapBucketCursor_prevN_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return CapBucketCursor_prevN_Params(st), err
}

func NewRootCapBucketCursor_prevN_Params(s *capnp.Segment) (CapBucketCursor_prevN_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return CapBucketCursor_prevN_Params(st), err
}

func ReadRootCapBucketCursor_prevN_Params(msg *capnp.Message) (CapBucketCursor_prevN_Params, error) {
	root, err := msg.Root()
	return CapBucketCursor_prevN_Params(root.Struct()), err
}

func (s CapBucketCursor_prevN_Params) String() string {
	str, _ := text.Marshal(0xd1d62e51cc686764, capnp.Struct(s))
	return str
}

func (s CapBucketCursor_prevN_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapBucketCursor_prevN_Params) DecodeFromPtr(p capnp.Ptr) CapBucketCursor_prevN_Params {
	return CapBucketCursor_prevN_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapBucketCursor_prevN_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapBucketCursor_prevN_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapBucketCursor_prevN_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapBucketCursor_prevN_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapBucketCursor_prevN_Params) Steps() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s CapBucketCursor_prevN_Params) SetSteps(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

// CapBucketCursor_prevN_Params_List is a list of CapBucketCursor_prevN_Params.
type CapBucketCursor_prevN_Params_List = capnp.StructList[CapBucketCursor_prevN_Params]

// NewCapBucketCursor_prevN_Params creates a new list of CapBucketCursor_prevN_Params.
func NewCapBucketCursor_prevN_Params_List(s *capnp.Segment, sz int32) (CapBucketCursor_prevN_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[CapBucketCursor_prevN_Params](l), err
}

// CapBucketCursor_prevN_Params_Future is a wrapper for a CapBucketCursor_prevN_Params promised by a client call.
type CapBucketCursor_prevN_Params_Future struct{ *capnp.Future }

func (p CapBucketCursor_prevN_Params_Future) Struct() (CapBucketCursor_prevN_Params, error) {
	s, err := p.Future.Struct()
	return CapBucketCursor_prevN_Params(s), err
}

type CapBucketCursor_prevN_Results capnp.Struct

// CapBucketCursor_prevN_Results_TypeID is the unique identifier for the type CapBucketCursor_prevN_Results.
const CapBucketCursor_prevN_Results_TypeID = 0xd88b83d32b65bc16

func NewCapBucketCursor_prevN_Results(s *capnp.Segment) (CapBucketCursor_prevN_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return CapBucketCursor_prevN_Results(st), err
}

func NewRootCapBucketCursor_prevN_Results(s *capnp.Segment) (CapBucketCursor_prevN_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return CapBucketCursor_prevN_Results(st), err
}

func ReadRootCapBucketCursor_prevN_Results(msg *capnp.Message) (CapBucketCursor_prevN_Results, error) {
	root, err := msg.Root()
	return CapBucketCursor_prevN_Results(root.Struct()), err
}

func (s CapBucketCursor_prevN_Results) String() string {
	str, _ := text.Marshal(0xd88b83d32b65bc16, capnp.Struct(s))
	return str
}

func (s CapBucketCursor_prevN_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapBucketCursor_prevN_Results) DecodeFromPtr(p capnp.Ptr) CapBucketCursor_prevN_Results {
	return CapBucketCursor_prevN_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapBucketCursor_prevN_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapBucketCursor_prevN_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapBucketCursor_prevN_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapBucketCursor_prevN_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapBucketCursor_prevN_Results) Docs() (KeyValueMap, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return KeyValueMap(p.Struct()), err
}

func (s CapBucketCursor_prevN_Results) HasDocs() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CapBucketCursor_prevN_Results) SetDocs(v KeyValueMap) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewDocs sets the docs field to a newly
// allocated KeyValueMap struct, preferring placement in s's segment.
func (s CapBucketCursor_prevN_Results) NewDocs() (KeyValueMap, error) {
	ss, err := NewKeyValueMap(capnp.Struct(s).Segment())
	if err != nil {
		return KeyValueMap{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s CapBucketCursor_prevN_Results) StartReached() bool {
	return capnp.Struct(s).Bit(0)
}

func (s CapBucketCursor_prevN_Results) SetStartReached(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

// CapBucketCursor_prevN_Results_List is a list of CapBucketCursor_prevN_Results.
type CapBucketCursor_prevN_Results_List = capnp.StructList[CapBucketCursor_prevN_Results]

// NewCapBucketCursor_prevN_Results creates a new list of CapBucketCursor_prevN_Results.
func NewCapBucketCursor_prevN_Results_List(s *capnp.Segment, sz int32) (CapBucketCursor_prevN_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[CapBucketCursor_prevN_Results](l), err
}

// CapBucketCursor_prevN_Results_Future is a wrapper for a CapBucketCursor_prevN_Results promised by a client call.
type CapBucketCursor_prevN_Results_Future struct{ *capnp.Future }

func (p CapBucketCursor_prevN_Results_Future) Struct() (CapBucketCursor_prevN_Results, error) {
	s, err := p.Future.Struct()
	return CapBucketCursor_prevN_Results(s), err
}

func (p CapBucketCursor_prevN_Results_Future) Docs() KeyValueMap_Future {
	return KeyValueMap_Future{Future: p.Future.Field(0, nil)}
}

type CapBucketCursor_seek_Params capnp.Struct

// CapBucketCursor_seek_Params_TypeID is the unique identifier for the type CapBucketCursor_seek_Params.
const CapBucketCursor_seek_Params_TypeID = 0xd67f13920d614679

func NewCapBucketCursor_seek_Params(s *capnp.Segment) (CapBucketCursor_seek_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapBucketCursor_seek_Params(st), err
}

func NewRootCapBucketCursor_seek_Params(s *capnp.Segment) (CapBucketCursor_seek_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapBucketCursor_seek_Params(st), err
}

func ReadRootCapBucketCursor_seek_Params(msg *capnp.Message) (CapBucketCursor_seek_Params, error) {
	root, err := msg.Root()
	return CapBucketCursor_seek_Params(root.Struct()), err
}

func (s CapBucketCursor_seek_Params) String() string {
	str, _ := text.Marshal(0xd67f13920d614679, capnp.Struct(s))
	return str
}

func (s CapBucketCursor_seek_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapBucketCursor_seek_Params) DecodeFromPtr(p capnp.Ptr) CapBucketCursor_seek_Params {
	return CapBucketCursor_seek_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapBucketCursor_seek_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapBucketCursor_seek_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapBucketCursor_seek_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapBucketCursor_seek_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapBucketCursor_seek_Params) SearchKey() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CapBucketCursor_seek_Params) HasSearchKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CapBucketCursor_seek_Params) SearchKeyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CapBucketCursor_seek_Params) SetSearchKey(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// CapBucketCursor_seek_Params_List is a list of CapBucketCursor_seek_Params.
type CapBucketCursor_seek_Params_List = capnp.StructList[CapBucketCursor_seek_Params]

// NewCapBucketCursor_seek_Params creates a new list of CapBucketCursor_seek_Params.
func NewCapBucketCursor_seek_Params_List(s *capnp.Segment, sz int32) (CapBucketCursor_seek_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[CapBucketCursor_seek_Params](l), err
}

// CapBucketCursor_seek_Params_Future is a wrapper for a CapBucketCursor_seek_Params promised by a client call.
type CapBucketCursor_seek_Params_Future struct{ *capnp.Future }

func (p CapBucketCursor_seek_Params_Future) Struct() (CapBucketCursor_seek_Params, error) {
	s, err := p.Future.Struct()
	return CapBucketCursor_seek_Params(s), err
}

type CapBucketCursor_seek_Results capnp.Struct

// CapBucketCursor_seek_Results_TypeID is the unique identifier for the type CapBucketCursor_seek_Results.
const CapBucketCursor_seek_Results_TypeID = 0x9279eeebcc13f8a4

func NewCapBucketCursor_seek_Results(s *capnp.Segment) (CapBucketCursor_seek_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CapBucketCursor_seek_Results(st), err
}

func NewRootCapBucketCursor_seek_Results(s *capnp.Segment) (CapBucketCursor_seek_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CapBucketCursor_seek_Results(st), err
}

func ReadRootCapBucketCursor_seek_Results(msg *capnp.Message) (CapBucketCursor_seek_Results, error) {
	root, err := msg.Root()
	return CapBucketCursor_seek_Results(root.Struct()), err
}

func (s CapBucketCursor_seek_Results) String() string {
	str, _ := text.Marshal(0x9279eeebcc13f8a4, capnp.Struct(s))
	return str
}

func (s CapBucketCursor_seek_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapBucketCursor_seek_Results) DecodeFromPtr(p capnp.Ptr) CapBucketCursor_seek_Results {
	return CapBucketCursor_seek_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapBucketCursor_seek_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapBucketCursor_seek_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapBucketCursor_seek_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapBucketCursor_seek_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapBucketCursor_seek_Results) Key() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CapBucketCursor_seek_Results) HasKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CapBucketCursor_seek_Results) KeyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CapBucketCursor_seek_Results) SetKey(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s CapBucketCursor_seek_Results) Value() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s CapBucketCursor_seek_Results) HasValue() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s CapBucketCursor_seek_Results) SetValue(v []byte) error {
	return capnp.Struct(s).SetData(1, v)
}

// CapBucketCursor_seek_Results_List is a list of CapBucketCursor_seek_Results.
type CapBucketCursor_seek_Results_List = capnp.StructList[CapBucketCursor_seek_Results]

// NewCapBucketCursor_seek_Results creates a new list of CapBucketCursor_seek_Results.
func NewCapBucketCursor_seek_Results_List(s *capnp.Segment, sz int32) (CapBucketCursor_seek_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[CapBucketCursor_seek_Results](l), err
}

// CapBucketCursor_seek_Results_Future is a wrapper for a CapBucketCursor_seek_Results promised by a client call.
type CapBucketCursor_seek_Results_Future struct{ *capnp.Future }

func (p CapBucketCursor_seek_Results_Future) Struct() (CapBucketCursor_seek_Results, error) {
	s, err := p.Future.Struct()
	return CapBucketCursor_seek_Results(s), err
}

const schema_893d996fbc85a1c3 = "x\xda\xbcU[h\x1cU\x18\xfe\xbf\xb9\xec\xd9\xd6\xac" +
	"\x9b\xc3\x84\xda\xa8am\xd8\x87\xb4\xda\xb4n\x8d\xb4b" +
	"\xc86\xa5E)\x91\xcc*B}\x9bn\x8en.n" +
	"\xd6\x99\xd9\xe8>\xd4\xc6J\x84D\x8b\x10\xe8C\x1f\x17" +
	"oT(>\xa8hm\x08B[\xa4\x10\xd1 \x14\xf3" +
	"PD\xf0\x8aPP,\xf86r\xce\xeeL&Ps" +
	"\x81\xc4\xa709\xdf\x7f\xfb\xfe\xef\xffv\xff/Z\xde" +
	"x8\xd5\xc7H\xb3\x9f1\x13\xc1\xef;\xeb\xd3\xf7^" +
	"\xfch\x92x\x16D\xa6\xc6\x88\x0eL\xe93 X\xe7" +
	"\xf4\x97\x09\xc1A\xf3i\x8d\xa5\xbex\xad\x010\xe4\xfb" +
	"\x9f\xfa\x19\x90\x11\x8c\xfcz\xac\xd0n\xceO\xc5^n" +
	"6^\xbe\xb1\xcf_\xb8\xf6\xc4[o\x90\x9d\x85\xcc\x0a" +
	"\xf9v]\x9f\x95Y\x97T\xd6\x9ew.\xff\xf0[\xdf" +
	"\x8e\xd9x\xd9C\x86\x02<iH\xc0\xbb\xffX\x0b\x7f" +
	"\xdc\xaa\xad\x00\xbcg\xa8\xbe>U\x80\xf4\xc9\xc9\x96W" +
	"\xbf\xbc\xafN\xbcM\x0f\xae\xd4\xa7\xe6\xc6\xcf\xf7N\x13" +
	"\xe1\x007;a\xed2e@\x87\xf9\x15\xac\x9e\x04#" +
	"\x0a\xae\xbemm7\x1e?\xfb~\xac\xd9\x8e\xc4\x8cl" +
	"v\xdbh\x87?\xd3\xde\xf9Y\xb3Y\xf5\x94J\xa8J" +
	"\x1d\x89>Bp\xf5\xcad\xd7\xe1\xbf\xae\xcf\xc7[\xe9" +
	"m\x00\x06\x12\xb2\x95\xa1\x17J\x0bv\xf7\x8d\xc5x\x86" +
	"\x0b\x0d\xc0%\x95\xa1v\xccI\xcdZ\xa7o43(" +
	":\x96\x12g$\xe0g\x05\xd81'\x1e\xfc\xee\xf57" +
	"\xbf_A\xd86\xa6\xf8hg\xb2F\xfd\xe3\xb9\xcb\xb7" +
	"\xe6w/\x11\x7f\x00\xc1\xa9\xb3\xe5GO\xdc\xfe\xfcv" +
	"\xb3\x99\x1a\xcb\xc1\x9af\x8c\xc8\x9aR\xe0\x0f\xbb\xb6\xef" +
	"\x1b\xf9\xc0\xff)6\xec\x8fLm\xe6\x93]\x13\xbd\x0b" +
	"\x8b\xdf\xfe\x1d\x9f\xe5k\xa6Z\xbd\xa9B\xa3\xd4\xbc\x0d" +
	"\xcb\xb46\x1a:\x94\xd4`\x1dM\xdeCd\x0d$\xfb" +
	"hoP\xaa\x9et*\xc3\xfb\xfa\xcdjqT\xf8\xdd" +
	"E\xa7R\xae<v\xc4\xa9\xf4\xab\xef#U\xd7\x1bw" +
	"\xbb+\xae\x98\xc8\x16\x84W\x1d\xf3=\";\xa9\x1bD" +
	"\x06\x88\xf8\xeeN\";\xab\xc3\xde\xaf\x81\x03mrr" +
	"\xbe7Gdw\xe9\xb0\x1f\xd1\xc0FE\x0d-\xa4\xa1" +
	"\x85\x90\x99p\xc6\xaa\x02)\xd2\x90\"D\x95\xf9\x9a\x95" +
	"\x07\x1d\xd7y\xd1\xa30`5\xfc\x98\xe3\xf9\x1b\xc1\x97" +
	"\xc5+\xfeS\xcd\xd1\xe0\xc5'\xdb\xb3<Y4\xd8s" +
	"D\xf6C:\xec\x83\x1a\xd2C\xe3E\x0f\xad\xcbd\x13" +
	"\xd0J\x08Dy\xa8 \x9cb\x89t1\x04\x90\x06\xc4" +
	"F]\x95\xe4\xe7\x87]\xcf\xbfc+\x9b@\xf2\xaa\x95" +
	"=!F\xb7l\xbd\xfa\x7fUf\xde\xb8;\x08\xd8\xf7" +
	"\xebf\xec\xb8\x11\xda\x0a_\xcc\x91\xc6\xaf1 r)" +
	"\x84g\xcc/\xed!\x8d_d\xd0\xa2;Ax\x16\xbc" +
	".\xdf\xce1\xe8\x91- 43>-s\x9eb0" +
	"\"OD\xe8\x9e\xfc%\x19'\x18\xcc\xc8\x0c\x10\xde4" +
	"?!\xe3\x06\x18\x12\x91\x0f t7~X\xc6\xf5\xb0" +
	"\x8c\xda_\x1ei)\xc1<\xd2RYyd\x94\xc0\xf2" +
	"HK!\xe7\x91\x91\x7f\xe4\xa7\xa4<\x8fAlH\x1b" +
	"M]\xd3\xfab\x1a\xd2\x0ecl#\xdaj*\xa7\x96" +
	"\x0c\xbbMC\xc6\xf3E\xc5C\x924$\xd7+\x17u" +
	"c[%\x975}hKFR\x17\xd0\xcc\x1bO[" +
	" \xb2[t\xd8;5\x04\x9ep\xdcb\xe9\xb8 D" +
	"3l\xa4\xeb\xf5z\xcc\xc8\xda\x1e\xe3\xf9\x8e\xeb\x17\x84" +
	"C\xe9b\xe9\x0e.\xb3\xe2\xe2\x8e\x8b\xda\xb3\x92\xe8\x01" +
	"\xa7\xd2\x9d9Z\xf6\xdd\x9a\xbc\xb9\xcd\xdd\xd9]k\xc9" +
	"p\xa3\x8e\xfc\xff\x98Q\x8c\x1a\xb2\x0d\xc4\x7f\xa0\x91k" +
	"p\x15\xd7B\x7fSbY\x0d\xa7E\xd9w\x87\x85\x87" +
	"\xbb\x09\x83:\xd0\xba\x1cJ\x90\xff\xfc7\x00\x00\xff\xff" +
	"\xf8\xd5\x8bR"

func init() {
	schemas.Register(schema_893d996fbc85a1c3,
		0x80afad1a89a118e9,
		0x81ba0d0702530538,
		0x85be05195246e76a,
		0x868c48c5a99951cf,
		0x92163fe8dfbba335,
		0x9279eeebcc13f8a4,
		0xa11bc07e0c80620f,
		0xa68d3c040a138fc4,
		0xb722198a741d6b09,
		0xbec9f2412880c3c4,
		0xd1d62e51cc686764,
		0xd67f13920d614679,
		0xd88b83d32b65bc16,
		0xd929beeebbbcb3a1,
		0xe474a76a2f0a28aa,
		0xf4d0d1cc3d7621b4,
		0xf5b8f559366e8d7d)
}
