// Code generated by capnpc-go. DO NOT EDIT.

package hubapi

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
)

// Constants defined in CertService.capnp.
const (
	CertServiceName                            = "certservice"
	DefaultCaCertFile                          = "caCert.pem"
	DefaultCaKeyFile                           = "caKey.pem"
	DefaultServiceCertValidityDays             = int32(30)
	DefaultClientCertValidityDays              = int32(30)
	DefaultDeviceCertValidityDays              = int32(30)
	CertService_defaultServiceCertValidityDays = int32(30)
)

type CertService capnp.Client

// CertService_TypeID is the unique identifier for the type CertService.
const CertService_TypeID = 0x8b685cd5f259a3b3

func (c CertService) CreateClientCert(ctx context.Context, params func(CertService_createClientCert_Params) error) (CertService_createClientCert_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x8b685cd5f259a3b3,
			MethodID:      0,
			InterfaceName: "hubapi/CertService.capnp:CertService",
			MethodName:    "createClientCert",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 2}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CertService_createClientCert_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CertService_createClientCert_Results_Future{Future: ans.Future()}, release
}
func (c CertService) CreateDeviceCert(ctx context.Context, params func(CertService_createDeviceCert_Params) error) (CertService_createDeviceCert_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x8b685cd5f259a3b3,
			MethodID:      1,
			InterfaceName: "hubapi/CertService.capnp:CertService",
			MethodName:    "createDeviceCert",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 2}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CertService_createDeviceCert_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CertService_createDeviceCert_Results_Future{Future: ans.Future()}, release
}
func (c CertService) CreateServiceCert(ctx context.Context, params func(CertService_createServiceCert_Params) error) (CertService_createServiceCert_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x8b685cd5f259a3b3,
			MethodID:      2,
			InterfaceName: "hubapi/CertService.capnp:CertService",
			MethodName:    "createServiceCert",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 3}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CertService_createServiceCert_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CertService_createServiceCert_Results_Future{Future: ans.Future()}, release
}

func (c CertService) AddRef() CertService {
	return CertService(capnp.Client(c).AddRef())
}

func (c CertService) Release() {
	capnp.Client(c).Release()
}

func (c CertService) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (CertService) DecodeFromPtr(p capnp.Ptr) CertService {
	return CertService(capnp.Client{}.DecodeFromPtr(p))
}

func (c CertService) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// A CertService_Server is a CertService with a local implementation.
type CertService_Server interface {
	CreateClientCert(context.Context, CertService_createClientCert) error

	CreateDeviceCert(context.Context, CertService_createDeviceCert) error

	CreateServiceCert(context.Context, CertService_createServiceCert) error
}

// CertService_NewServer creates a new Server from an implementation of CertService_Server.
func CertService_NewServer(s CertService_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(CertService_Methods(nil, s), s, c)
}

// CertService_ServerToClient creates a new Client from an implementation of CertService_Server.
// The caller is responsible for calling Release on the returned Client.
func CertService_ServerToClient(s CertService_Server) CertService {
	return CertService(capnp.NewClient(CertService_NewServer(s)))
}

// CertService_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func CertService_Methods(methods []server.Method, s CertService_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 3)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x8b685cd5f259a3b3,
			MethodID:      0,
			InterfaceName: "hubapi/CertService.capnp:CertService",
			MethodName:    "createClientCert",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.CreateClientCert(ctx, CertService_createClientCert{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x8b685cd5f259a3b3,
			MethodID:      1,
			InterfaceName: "hubapi/CertService.capnp:CertService",
			MethodName:    "createDeviceCert",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.CreateDeviceCert(ctx, CertService_createDeviceCert{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x8b685cd5f259a3b3,
			MethodID:      2,
			InterfaceName: "hubapi/CertService.capnp:CertService",
			MethodName:    "createServiceCert",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.CreateServiceCert(ctx, CertService_createServiceCert{call})
		},
	})

	return methods
}

// CertService_createClientCert holds the state for a server call to CertService.createClientCert.
// See server.Call for documentation.
type CertService_createClientCert struct {
	*server.Call
}

// Args returns the call's arguments.
func (c CertService_createClientCert) Args() CertService_createClientCert_Params {
	return CertService_createClientCert_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c CertService_createClientCert) AllocResults() (CertService_createClientCert_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CertService_createClientCert_Results(r), err
}

// CertService_createDeviceCert holds the state for a server call to CertService.createDeviceCert.
// See server.Call for documentation.
type CertService_createDeviceCert struct {
	*server.Call
}

// Args returns the call's arguments.
func (c CertService_createDeviceCert) Args() CertService_createDeviceCert_Params {
	return CertService_createDeviceCert_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c CertService_createDeviceCert) AllocResults() (CertService_createDeviceCert_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CertService_createDeviceCert_Results(r), err
}

// CertService_createServiceCert holds the state for a server call to CertService.createServiceCert.
// See server.Call for documentation.
type CertService_createServiceCert struct {
	*server.Call
}

// Args returns the call's arguments.
func (c CertService_createServiceCert) Args() CertService_createServiceCert_Params {
	return CertService_createServiceCert_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c CertService_createServiceCert) AllocResults() (CertService_createServiceCert_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CertService_createServiceCert_Results(r), err
}

// CertService_List is a list of CertService.
type CertService_List = capnp.CapList[CertService]

// NewCertService creates a new list of CertService.
func NewCertService_List(s *capnp.Segment, sz int32) (CertService_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[CertService](l), err
}

type CertService_createClientCert_Params capnp.Struct

// CertService_createClientCert_Params_TypeID is the unique identifier for the type CertService_createClientCert_Params.
const CertService_createClientCert_Params_TypeID = 0xf01c40f65e7294b7

func NewCertService_createClientCert_Params(s *capnp.Segment) (CertService_createClientCert_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return CertService_createClientCert_Params(st), err
}

func NewRootCertService_createClientCert_Params(s *capnp.Segment) (CertService_createClientCert_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return CertService_createClientCert_Params(st), err
}

func ReadRootCertService_createClientCert_Params(msg *capnp.Message) (CertService_createClientCert_Params, error) {
	root, err := msg.Root()
	return CertService_createClientCert_Params(root.Struct()), err
}

func (s CertService_createClientCert_Params) String() string {
	str, _ := text.Marshal(0xf01c40f65e7294b7, capnp.Struct(s))
	return str
}

func (s CertService_createClientCert_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CertService_createClientCert_Params) DecodeFromPtr(p capnp.Ptr) CertService_createClientCert_Params {
	return CertService_createClientCert_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CertService_createClientCert_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CertService_createClientCert_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CertService_createClientCert_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CertService_createClientCert_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CertService_createClientCert_Params) ClientID() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CertService_createClientCert_Params) HasClientID() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CertService_createClientCert_Params) ClientIDBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CertService_createClientCert_Params) SetClientID(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s CertService_createClientCert_Params) PubKeyPEM() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s CertService_createClientCert_Params) HasPubKeyPEM() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s CertService_createClientCert_Params) PubKeyPEMBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s CertService_createClientCert_Params) SetPubKeyPEM(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s CertService_createClientCert_Params) ValidityDays() int32 {
	return int32(capnp.Struct(s).Uint32(0))
}

func (s CertService_createClientCert_Params) SetValidityDays(v int32) {
	capnp.Struct(s).SetUint32(0, uint32(v))
}

// CertService_createClientCert_Params_List is a list of CertService_createClientCert_Params.
type CertService_createClientCert_Params_List = capnp.StructList[CertService_createClientCert_Params]

// NewCertService_createClientCert_Params creates a new list of CertService_createClientCert_Params.
func NewCertService_createClientCert_Params_List(s *capnp.Segment, sz int32) (CertService_createClientCert_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[CertService_createClientCert_Params](l), err
}

// CertService_createClientCert_Params_Future is a wrapper for a CertService_createClientCert_Params promised by a client call.
type CertService_createClientCert_Params_Future struct{ *capnp.Future }

func (p CertService_createClientCert_Params_Future) Struct() (CertService_createClientCert_Params, error) {
	s, err := p.Future.Struct()
	return CertService_createClientCert_Params(s), err
}

type CertService_createClientCert_Results capnp.Struct

// CertService_createClientCert_Results_TypeID is the unique identifier for the type CertService_createClientCert_Results.
const CertService_createClientCert_Results_TypeID = 0xa2d4945bd89164fa

func NewCertService_createClientCert_Results(s *capnp.Segment) (CertService_createClientCert_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CertService_createClientCert_Results(st), err
}

func NewRootCertService_createClientCert_Results(s *capnp.Segment) (CertService_createClientCert_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CertService_createClientCert_Results(st), err
}

func ReadRootCertService_createClientCert_Results(msg *capnp.Message) (CertService_createClientCert_Results, error) {
	root, err := msg.Root()
	return CertService_createClientCert_Results(root.Struct()), err
}

func (s CertService_createClientCert_Results) String() string {
	str, _ := text.Marshal(0xa2d4945bd89164fa, capnp.Struct(s))
	return str
}

func (s CertService_createClientCert_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CertService_createClientCert_Results) DecodeFromPtr(p capnp.Ptr) CertService_createClientCert_Results {
	return CertService_createClientCert_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CertService_createClientCert_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CertService_createClientCert_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CertService_createClientCert_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CertService_createClientCert_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CertService_createClientCert_Results) CertPEM() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CertService_createClientCert_Results) HasCertPEM() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CertService_createClientCert_Results) CertPEMBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CertService_createClientCert_Results) SetCertPEM(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s CertService_createClientCert_Results) CaCertPEM() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s CertService_createClientCert_Results) HasCaCertPEM() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s CertService_createClientCert_Results) CaCertPEMBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s CertService_createClientCert_Results) SetCaCertPEM(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// CertService_createClientCert_Results_List is a list of CertService_createClientCert_Results.
type CertService_createClientCert_Results_List = capnp.StructList[CertService_createClientCert_Results]

// NewCertService_createClientCert_Results creates a new list of CertService_createClientCert_Results.
func NewCertService_createClientCert_Results_List(s *capnp.Segment, sz int32) (CertService_createClientCert_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[CertService_createClientCert_Results](l), err
}

// CertService_createClientCert_Results_Future is a wrapper for a CertService_createClientCert_Results promised by a client call.
type CertService_createClientCert_Results_Future struct{ *capnp.Future }

func (p CertService_createClientCert_Results_Future) Struct() (CertService_createClientCert_Results, error) {
	s, err := p.Future.Struct()
	return CertService_createClientCert_Results(s), err
}

type CertService_createDeviceCert_Params capnp.Struct

// CertService_createDeviceCert_Params_TypeID is the unique identifier for the type CertService_createDeviceCert_Params.
const CertService_createDeviceCert_Params_TypeID = 0xc6e9af543d3ce973

func NewCertService_createDeviceCert_Params(s *capnp.Segment) (CertService_createDeviceCert_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return CertService_createDeviceCert_Params(st), err
}

func NewRootCertService_createDeviceCert_Params(s *capnp.Segment) (CertService_createDeviceCert_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return CertService_createDeviceCert_Params(st), err
}

func ReadRootCertService_createDeviceCert_Params(msg *capnp.Message) (CertService_createDeviceCert_Params, error) {
	root, err := msg.Root()
	return CertService_createDeviceCert_Params(root.Struct()), err
}

func (s CertService_createDeviceCert_Params) String() string {
	str, _ := text.Marshal(0xc6e9af543d3ce973, capnp.Struct(s))
	return str
}

func (s CertService_createDeviceCert_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CertService_createDeviceCert_Params) DecodeFromPtr(p capnp.Ptr) CertService_createDeviceCert_Params {
	return CertService_createDeviceCert_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CertService_createDeviceCert_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CertService_createDeviceCert_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CertService_createDeviceCert_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CertService_createDeviceCert_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CertService_createDeviceCert_Params) DeviceID() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CertService_createDeviceCert_Params) HasDeviceID() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CertService_createDeviceCert_Params) DeviceIDBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CertService_createDeviceCert_Params) SetDeviceID(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s CertService_createDeviceCert_Params) PubKeyPEM() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s CertService_createDeviceCert_Params) HasPubKeyPEM() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s CertService_createDeviceCert_Params) PubKeyPEMBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s CertService_createDeviceCert_Params) SetPubKeyPEM(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s CertService_createDeviceCert_Params) ValidityDays() int32 {
	return int32(capnp.Struct(s).Uint32(0))
}

func (s CertService_createDeviceCert_Params) SetValidityDays(v int32) {
	capnp.Struct(s).SetUint32(0, uint32(v))
}

// CertService_createDeviceCert_Params_List is a list of CertService_createDeviceCert_Params.
type CertService_createDeviceCert_Params_List = capnp.StructList[CertService_createDeviceCert_Params]

// NewCertService_createDeviceCert_Params creates a new list of CertService_createDeviceCert_Params.
func NewCertService_createDeviceCert_Params_List(s *capnp.Segment, sz int32) (CertService_createDeviceCert_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[CertService_createDeviceCert_Params](l), err
}

// CertService_createDeviceCert_Params_Future is a wrapper for a CertService_createDeviceCert_Params promised by a client call.
type CertService_createDeviceCert_Params_Future struct{ *capnp.Future }

func (p CertService_createDeviceCert_Params_Future) Struct() (CertService_createDeviceCert_Params, error) {
	s, err := p.Future.Struct()
	return CertService_createDeviceCert_Params(s), err
}

type CertService_createDeviceCert_Results capnp.Struct

// CertService_createDeviceCert_Results_TypeID is the unique identifier for the type CertService_createDeviceCert_Results.
const CertService_createDeviceCert_Results_TypeID = 0x89a32f6532d5c18c

func NewCertService_createDeviceCert_Results(s *capnp.Segment) (CertService_createDeviceCert_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CertService_createDeviceCert_Results(st), err
}

func NewRootCertService_createDeviceCert_Results(s *capnp.Segment) (CertService_createDeviceCert_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CertService_createDeviceCert_Results(st), err
}

func ReadRootCertService_createDeviceCert_Results(msg *capnp.Message) (CertService_createDeviceCert_Results, error) {
	root, err := msg.Root()
	return CertService_createDeviceCert_Results(root.Struct()), err
}

func (s CertService_createDeviceCert_Results) String() string {
	str, _ := text.Marshal(0x89a32f6532d5c18c, capnp.Struct(s))
	return str
}

func (s CertService_createDeviceCert_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CertService_createDeviceCert_Results) DecodeFromPtr(p capnp.Ptr) CertService_createDeviceCert_Results {
	return CertService_createDeviceCert_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CertService_createDeviceCert_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CertService_createDeviceCert_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CertService_createDeviceCert_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CertService_createDeviceCert_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CertService_createDeviceCert_Results) CertPEM() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CertService_createDeviceCert_Results) HasCertPEM() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CertService_createDeviceCert_Results) CertPEMBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CertService_createDeviceCert_Results) SetCertPEM(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s CertService_createDeviceCert_Results) CaCertPEM() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s CertService_createDeviceCert_Results) HasCaCertPEM() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s CertService_createDeviceCert_Results) CaCertPEMBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s CertService_createDeviceCert_Results) SetCaCertPEM(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// CertService_createDeviceCert_Results_List is a list of CertService_createDeviceCert_Results.
type CertService_createDeviceCert_Results_List = capnp.StructList[CertService_createDeviceCert_Results]

// NewCertService_createDeviceCert_Results creates a new list of CertService_createDeviceCert_Results.
func NewCertService_createDeviceCert_Results_List(s *capnp.Segment, sz int32) (CertService_createDeviceCert_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[CertService_createDeviceCert_Results](l), err
}

// CertService_createDeviceCert_Results_Future is a wrapper for a CertService_createDeviceCert_Results promised by a client call.
type CertService_createDeviceCert_Results_Future struct{ *capnp.Future }

func (p CertService_createDeviceCert_Results_Future) Struct() (CertService_createDeviceCert_Results, error) {
	s, err := p.Future.Struct()
	return CertService_createDeviceCert_Results(s), err
}

type CertService_createServiceCert_Params capnp.Struct

// CertService_createServiceCert_Params_TypeID is the unique identifier for the type CertService_createServiceCert_Params.
const CertService_createServiceCert_Params_TypeID = 0xe847821c6901e186

func NewCertService_createServiceCert_Params(s *capnp.Segment) (CertService_createServiceCert_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return CertService_createServiceCert_Params(st), err
}

func NewRootCertService_createServiceCert_Params(s *capnp.Segment) (CertService_createServiceCert_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return CertService_createServiceCert_Params(st), err
}

func ReadRootCertService_createServiceCert_Params(msg *capnp.Message) (CertService_createServiceCert_Params, error) {
	root, err := msg.Root()
	return CertService_createServiceCert_Params(root.Struct()), err
}

func (s CertService_createServiceCert_Params) String() string {
	str, _ := text.Marshal(0xe847821c6901e186, capnp.Struct(s))
	return str
}

func (s CertService_createServiceCert_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CertService_createServiceCert_Params) DecodeFromPtr(p capnp.Ptr) CertService_createServiceCert_Params {
	return CertService_createServiceCert_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CertService_createServiceCert_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CertService_createServiceCert_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CertService_createServiceCert_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CertService_createServiceCert_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CertService_createServiceCert_Params) ServiceID() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CertService_createServiceCert_Params) HasServiceID() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CertService_createServiceCert_Params) ServiceIDBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CertService_createServiceCert_Params) SetServiceID(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s CertService_createServiceCert_Params) PubKeyPEM() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s CertService_createServiceCert_Params) HasPubKeyPEM() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s CertService_createServiceCert_Params) PubKeyPEMBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s CertService_createServiceCert_Params) SetPubKeyPEM(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s CertService_createServiceCert_Params) ValidityDays() int32 {
	return int32(capnp.Struct(s).Uint32(0))
}

func (s CertService_createServiceCert_Params) SetValidityDays(v int32) {
	capnp.Struct(s).SetUint32(0, uint32(v))
}

func (s CertService_createServiceCert_Params) Names() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return capnp.TextList(p.List()), err
}

func (s CertService_createServiceCert_Params) HasNames() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s CertService_createServiceCert_Params) SetNames(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(2, v.ToPtr())
}

// NewNames sets the names field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s CertService_createServiceCert_Params) NewNames(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(2, l.ToPtr())
	return l, err
}

// CertService_createServiceCert_Params_List is a list of CertService_createServiceCert_Params.
type CertService_createServiceCert_Params_List = capnp.StructList[CertService_createServiceCert_Params]

// NewCertService_createServiceCert_Params creates a new list of CertService_createServiceCert_Params.
func NewCertService_createServiceCert_Params_List(s *capnp.Segment, sz int32) (CertService_createServiceCert_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3}, sz)
	return capnp.StructList[CertService_createServiceCert_Params](l), err
}

// CertService_createServiceCert_Params_Future is a wrapper for a CertService_createServiceCert_Params promised by a client call.
type CertService_createServiceCert_Params_Future struct{ *capnp.Future }

func (p CertService_createServiceCert_Params_Future) Struct() (CertService_createServiceCert_Params, error) {
	s, err := p.Future.Struct()
	return CertService_createServiceCert_Params(s), err
}

type CertService_createServiceCert_Results capnp.Struct

// CertService_createServiceCert_Results_TypeID is the unique identifier for the type CertService_createServiceCert_Results.
const CertService_createServiceCert_Results_TypeID = 0xc2f0204a72052f9a

func NewCertService_createServiceCert_Results(s *capnp.Segment) (CertService_createServiceCert_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CertService_createServiceCert_Results(st), err
}

func NewRootCertService_createServiceCert_Results(s *capnp.Segment) (CertService_createServiceCert_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CertService_createServiceCert_Results(st), err
}

func ReadRootCertService_createServiceCert_Results(msg *capnp.Message) (CertService_createServiceCert_Results, error) {
	root, err := msg.Root()
	return CertService_createServiceCert_Results(root.Struct()), err
}

func (s CertService_createServiceCert_Results) String() string {
	str, _ := text.Marshal(0xc2f0204a72052f9a, capnp.Struct(s))
	return str
}

func (s CertService_createServiceCert_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CertService_createServiceCert_Results) DecodeFromPtr(p capnp.Ptr) CertService_createServiceCert_Results {
	return CertService_createServiceCert_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CertService_createServiceCert_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CertService_createServiceCert_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CertService_createServiceCert_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CertService_createServiceCert_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CertService_createServiceCert_Results) CertPEM() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CertService_createServiceCert_Results) HasCertPEM() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CertService_createServiceCert_Results) CertPEMBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CertService_createServiceCert_Results) SetCertPEM(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s CertService_createServiceCert_Results) CaCertPEM() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s CertService_createServiceCert_Results) HasCaCertPEM() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s CertService_createServiceCert_Results) CaCertPEMBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s CertService_createServiceCert_Results) SetCaCertPEM(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// CertService_createServiceCert_Results_List is a list of CertService_createServiceCert_Results.
type CertService_createServiceCert_Results_List = capnp.StructList[CertService_createServiceCert_Results]

// NewCertService_createServiceCert_Results creates a new list of CertService_createServiceCert_Results.
func NewCertService_createServiceCert_Results_List(s *capnp.Segment, sz int32) (CertService_createServiceCert_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[CertService_createServiceCert_Results](l), err
}

// CertService_createServiceCert_Results_Future is a wrapper for a CertService_createServiceCert_Results promised by a client call.
type CertService_createServiceCert_Results_Future struct{ *capnp.Future }

func (p CertService_createServiceCert_Results_Future) Struct() (CertService_createServiceCert_Results, error) {
	s, err := p.Future.Struct()
	return CertService_createServiceCert_Results(s), err
}

const schema_cd6ed2180540008c = "x\xda\xb4T]h\x1cU\x14>\xe7\xde\xbb3\"\xb1" +
	"\xf12\x11\xad\x14\xd3j\x16Li\xfe\x9a\xfa\x13i\xe9" +
	"\xd6\xdd\xc465\xb2w7J[E3\xd9\\\xc9\xc8" +
	"\xee\xb2\xce\xccF\x16\x05A\xb0\xd0\x98\x07\x95\xbeX\x1f" +
	"\x84\xd6\x0a\xfa`\xfcy\x10\x04Q\x0b\xea\xcb*\xb4X" +
	"\xc8\x8bh\x1f\x8aF|(A\x04\x83:rg2;" +
	"\xb3[\xbamC\xf38\xe7~\xf3\x9d\xef|\xdf\xb9w" +
	"\xf0$I\xb1\xa1[\x1e\xd0\x80\x88\xfd\x09\xcd[\xf8\xfa" +
	"\xfcN9p\xea\x18\xf0$\x02$\x88\x0e0\x8ct\x05" +
	"\x01\x8d\xdb\xe8\x0b\x80\xde\xa7\xa7\x0e\xaf\x9c\x7fj\xf65" +
	"\xe0\x9b\xe9\xbf\x0b\xa9\xc4\x1d\xe7\xca\xdf\x03\x0eW\xe9v" +
	"4^\xa5\xb7\x03\x18o\xd1\xef\x8c^\xa6\x03x\x1dS" +
	"K\xe4\xdd\xc9\xf9\x13\xc07\xb3\x18\x96\xb3\xcf1@\xe4" +
	"{\x18\xc5\xfc #\x08\xe0\xddy\xee\xbf\x8f.l\xff" +
	"\xf3\x9d\x16\xf46\x85\x1e\xf1\xd1\xbb\x14:\x15\xa0Wg" +
	"\xdeXz\xf2\xf8\x8f'\xe3B\x87\x98/t\x94)\xa1" +
	"\xf7\xe5~\xd6n\x1e\xbe\xe7}\xe0I\x16\xa9\x06\x1c>" +
	"\xcd\xee&\xc67>\xe1W\x8a\xb0\x1e\x10\xce\xbf\xfd\xc1" +
	"\xd8{\xff\xec\xfa\xb8\xa5\xfd\x17l\x1c\x8d\xb3>\xba\xae" +
	"\xd0K\x01\xfa\xc5\xf2\xfd\xf7:\xa7\x9f\xf9\xa4\x05}\x96" +
	"\x1dA\xe3\xa2\x8f\xfeE\xa1\xff\x08\xd0'\x06\x12\xf6\xf8" +
	"\xd6Kg\xe2b/\xb2U%\xf6o_\xac\xb3\xbc{" +
	"\xcf\xe4\xe2\xf2\xb7 \x92\xd8@\x1cN\xfc\xae\x10\xa5\xc4" +
	"\"\xa0W\xff\xb2|\xe8\xa7\xf9\x0f\xeb\xad^j94" +
	"\x92\x9aj\xb8U\xa3\x98\xdf\xa1\xf9\x0d\x8f^@k\xcb" +
	"+\x8f\xfc\x16\xf2Q\xc5\x97\xd4|{F\xb4_\x01\xbd" +
	"\x85\xa3\xc7~\x18_\xd9\xb6\xdc\xc2\xd7\xab\x9fAc\x9f" +
	"\xae\xf8v\xeb\x14\xf3\xfbu\x9f\xef\xb3\xe3\xf6\xd3\x7f\xa5" +
	"\xb6\\j\xd27\xa2\xfb\xfa&\xf4E\xe8\xf3f\xab\xd3" +
	"f\xc5\x1aHk\xd2v\xf3\xd2\x9e\xb3\x0a\xb2\xbf`V" +
	"\xca\x95\x87\xd2\xf1\x8a-MWf\xa4\xfaP\xf5\x9e\x9c" +
	"\xecv\xaaE\xd7\x117Q\x06\xc0\x10\x80\xf7>\x0c " +
	"z(\x8aA\x82\x1c\xb1K5\xe4}9\x00\xb1\x83\xa2" +
	"x\x90\xe0\xcb\x05i\xbb\xd9\xd1\x09\xec\x00\x82\x1d\x80^" +
	"\xc1L\xfb\x15\xc0\xa8\x16\xea\xa1W\xd2\xd3\xa9J\x82a" +
	"|Sp\xd5\x9b\x91\xcf\x9a\xd5\xa2\x9b'\xc1?\x0a\xfc" +
	"\x84Y\xb4f\xac\xbdn-c\xd6\x1c\xd1A\x131C" +
	"0\xdcC.\xe6\x81\xf0\x09\x1d\xa301\xbcL|\x9f" +
	":\xdb\xa3#i\x04\x83\xe1J\xf0\xa17\x81\xf0>\xdd" +
	"\x0b\xacI\x17\xd1\x92eW\xb5\x05H\xa1\x17\x1a\x86\xa1" +
	"\x98X5/1\xd4\x88n\x0a\xb3\x18M\x9d\xb8l\xea" +
	"\xb5\xb9\"\xeb\x9b\xa6\xca\"\"\x03\xc2\xd9]p\x0d$" +
	"\xe9b\xa8\xf1\xea$\xd7\xb2\x0f\x11\xdf\xc6\xef\x83\xdeV" +
	"O\x98~k\xf8n-\xa3_iBv\x19c!\xaa" +
	"<f\x96$\x80\xfa/\x10\x02\x1c\xa7=u\xeeH{" +
	"\x0et\xab \xdb\xf0\x84v\xfb\xe3\x8cY\xb4(\x9b\x88" +
	"\x8e\xac\x0d\xda_\x01*K\xd7\xe5xl\xc0\x9e\xdc^" +
	"\xb9\xb1\x96_\xe7\x93\x905;m\xb3\xa4.Z(g" +
	"t\x1c@d(\x8alL\xce\x84\x92\xf3(Eq\x88" +
	" \x92.$\x00\xfc\xf1\xe7\x00\xc4$E1E\xd0\x9b" +
	"\xf1)\x0fd\x00\xa0!\xa9R\x9d>(k\xcd2\xe7" +
	"\xd6\x12\x86N\xb5\xc4*_dm\xe3m\xc4rP\xd6" +
	"\xc6\xac\"6\xa7\x92\xf3\x0a\xea\xa0\xbf\"\x01\xd7\x1fJ" +
	"\xb6\xdb\xf4M\xb8\xb5a\x82\xa9\xe6\x9d\xa2(\x8a1\x13" +
	",U\x9c\xa5(\xdc\xc8\x84\xe7\x95\x09\x15\x8a\xe2%\x82" +
	"\x9c\x92.\xa4\x00\xbc\xb6\x13@\xb8\x14\xc5\xeb\x04='" +
	"ht\x000\xb3\x0eg\xba\xcbfI:\xb8\x090K" +
	"\x83\xb97\xb5\x0d\xbb\xcd\x9d2k\x0e\xdc\x88W\xe3F" +
	"\xadL\xc1\xa7\\\xef\xca\xfc\x1f\x00\x00\xff\xff\xd06\x93" +
	"\x0d"

func init() {
	schemas.Register(schema_cd6ed2180540008c,
		0x89a32f6532d5c18c,
		0x8b685cd5f259a3b3,
		0x9a8a54a402d8600c,
		0x9ff42ae1b0fed21a,
		0xa2d4945bd89164fa,
		0xa923330a06df5235,
		0xb134fca646aa9b8a,
		0xb25fa57328366e7b,
		0xc2f0204a72052f9a,
		0xc6e9af543d3ce973,
		0xccae8add586ebfcc,
		0xe847821c6901e186,
		0xe921f24ace89868c,
		0xf01c40f65e7294b7)
}
