// Code generated by capnpc-go. DO NOT EDIT.

package hubapi

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
)

type ClientCapabilities capnp.Struct

// ClientCapabilities_TypeID is the unique identifier for the type ClientCapabilities.
const ClientCapabilities_TypeID = 0xf625f2c3c988ee07

func NewClientCapabilities(s *capnp.Segment) (ClientCapabilities, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return ClientCapabilities(st), err
}

func NewRootClientCapabilities(s *capnp.Segment) (ClientCapabilities, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return ClientCapabilities(st), err
}

func ReadRootClientCapabilities(msg *capnp.Message) (ClientCapabilities, error) {
	root, err := msg.Root()
	return ClientCapabilities(root.Struct()), err
}

func (s ClientCapabilities) String() string {
	str, _ := text.Marshal(0xf625f2c3c988ee07, capnp.Struct(s))
	return str
}

func (s ClientCapabilities) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ClientCapabilities) DecodeFromPtr(p capnp.Ptr) ClientCapabilities {
	return ClientCapabilities(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ClientCapabilities) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ClientCapabilities) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ClientCapabilities) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ClientCapabilities) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ClientCapabilities) DirectoryStore() DirectoryStore {
	p, _ := capnp.Struct(s).Ptr(0)
	return DirectoryStore(p.Interface().Client())
}

func (s ClientCapabilities) HasDirectoryStore() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ClientCapabilities) SetDirectoryStore(v DirectoryStore) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().AddCap(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(0, in.ToPtr())
}

func (s ClientCapabilities) HistoryStore() HistoryStore {
	p, _ := capnp.Struct(s).Ptr(1)
	return HistoryStore(p.Interface().Client())
}

func (s ClientCapabilities) HasHistoryStore() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ClientCapabilities) SetHistoryStore(v HistoryStore) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(1, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().AddCap(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(1, in.ToPtr())
}

func (s ClientCapabilities) PropertyStore() PropertyStore {
	p, _ := capnp.Struct(s).Ptr(2)
	return PropertyStore(p.Interface().Client())
}

func (s ClientCapabilities) HasPropertyStore() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s ClientCapabilities) SetPropertyStore(v PropertyStore) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(2, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().AddCap(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(2, in.ToPtr())
}

func (s ClientCapabilities) ProvisioningService() ProvisioningService {
	p, _ := capnp.Struct(s).Ptr(3)
	return ProvisioningService(p.Interface().Client())
}

func (s ClientCapabilities) HasProvisioningService() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s ClientCapabilities) SetProvisioningService(v ProvisioningService) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(3, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().AddCap(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(3, in.ToPtr())
}

// ClientCapabilities_List is a list of ClientCapabilities.
type ClientCapabilities_List = capnp.StructList[ClientCapabilities]

// NewClientCapabilities creates a new list of ClientCapabilities.
func NewClientCapabilities_List(s *capnp.Segment, sz int32) (ClientCapabilities_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4}, sz)
	return capnp.StructList[ClientCapabilities](l), err
}

// ClientCapabilities_Future is a wrapper for a ClientCapabilities promised by a client call.
type ClientCapabilities_Future struct{ *capnp.Future }

func (p ClientCapabilities_Future) Struct() (ClientCapabilities, error) {
	s, err := p.Future.Struct()
	return ClientCapabilities(s), err
}

func (p ClientCapabilities_Future) DirectoryStore() DirectoryStore {
	return DirectoryStore(p.Future.Field(0, nil).Client())
}

func (p ClientCapabilities_Future) HistoryStore() HistoryStore {
	return HistoryStore(p.Future.Field(1, nil).Client())
}

func (p ClientCapabilities_Future) PropertyStore() PropertyStore {
	return PropertyStore(p.Future.Field(2, nil).Client())
}

func (p ClientCapabilities_Future) ProvisioningService() ProvisioningService {
	return ProvisioningService(p.Future.Field(3, nil).Client())
}

type Gateway capnp.Client

// Gateway_TypeID is the unique identifier for the type Gateway.
const Gateway_TypeID = 0x928a26cd0a89a930

func (c Gateway) Login(ctx context.Context, params func(Gateway_login_Params) error) (Gateway_login_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x928a26cd0a89a930,
			MethodID:      0,
			InterfaceName: "hubapi/Gateway.capnp:Gateway",
			MethodName:    "login",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 2}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Gateway_login_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Gateway_login_Results_Future{Future: ans.Future()}, release
}
func (c Gateway) Capabilities(ctx context.Context, params func(Gateway_capabilities_Params) error) (Gateway_capabilities_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x928a26cd0a89a930,
			MethodID:      1,
			InterfaceName: "hubapi/Gateway.capnp:Gateway",
			MethodName:    "capabilities",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Gateway_capabilities_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Gateway_capabilities_Results_Future{Future: ans.Future()}, release
}

func (c Gateway) AddRef() Gateway {
	return Gateway(capnp.Client(c).AddRef())
}

func (c Gateway) Release() {
	capnp.Client(c).Release()
}

func (c Gateway) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Gateway) DecodeFromPtr(p capnp.Ptr) Gateway {
	return Gateway(capnp.Client{}.DecodeFromPtr(p))
}

func (c Gateway) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// A Gateway_Server is a Gateway with a local implementation.
type Gateway_Server interface {
	Login(context.Context, Gateway_login) error

	Capabilities(context.Context, Gateway_capabilities) error
}

// Gateway_NewServer creates a new Server from an implementation of Gateway_Server.
func Gateway_NewServer(s Gateway_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Gateway_Methods(nil, s), s, c)
}

// Gateway_ServerToClient creates a new Client from an implementation of Gateway_Server.
// The caller is responsible for calling Release on the returned Client.
func Gateway_ServerToClient(s Gateway_Server) Gateway {
	return Gateway(capnp.NewClient(Gateway_NewServer(s)))
}

// Gateway_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Gateway_Methods(methods []server.Method, s Gateway_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x928a26cd0a89a930,
			MethodID:      0,
			InterfaceName: "hubapi/Gateway.capnp:Gateway",
			MethodName:    "login",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Login(ctx, Gateway_login{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x928a26cd0a89a930,
			MethodID:      1,
			InterfaceName: "hubapi/Gateway.capnp:Gateway",
			MethodName:    "capabilities",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Capabilities(ctx, Gateway_capabilities{call})
		},
	})

	return methods
}

// Gateway_login holds the state for a server call to Gateway.login.
// See server.Call for documentation.
type Gateway_login struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Gateway_login) Args() Gateway_login_Params {
	return Gateway_login_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Gateway_login) AllocResults() (Gateway_login_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Gateway_login_Results(r), err
}

// Gateway_capabilities holds the state for a server call to Gateway.capabilities.
// See server.Call for documentation.
type Gateway_capabilities struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Gateway_capabilities) Args() Gateway_capabilities_Params {
	return Gateway_capabilities_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Gateway_capabilities) AllocResults() (Gateway_capabilities_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Gateway_capabilities_Results(r), err
}

// Gateway_List is a list of Gateway.
type Gateway_List = capnp.CapList[Gateway]

// NewGateway creates a new list of Gateway.
func NewGateway_List(s *capnp.Segment, sz int32) (Gateway_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Gateway](l), err
}

type Gateway_login_Params capnp.Struct

// Gateway_login_Params_TypeID is the unique identifier for the type Gateway_login_Params.
const Gateway_login_Params_TypeID = 0xb3dc61f56f39dbdd

func NewGateway_login_Params(s *capnp.Segment) (Gateway_login_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Gateway_login_Params(st), err
}

func NewRootGateway_login_Params(s *capnp.Segment) (Gateway_login_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Gateway_login_Params(st), err
}

func ReadRootGateway_login_Params(msg *capnp.Message) (Gateway_login_Params, error) {
	root, err := msg.Root()
	return Gateway_login_Params(root.Struct()), err
}

func (s Gateway_login_Params) String() string {
	str, _ := text.Marshal(0xb3dc61f56f39dbdd, capnp.Struct(s))
	return str
}

func (s Gateway_login_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Gateway_login_Params) DecodeFromPtr(p capnp.Ptr) Gateway_login_Params {
	return Gateway_login_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Gateway_login_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Gateway_login_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Gateway_login_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Gateway_login_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Gateway_login_Params) ClientID() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Gateway_login_Params) HasClientID() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Gateway_login_Params) ClientIDBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Gateway_login_Params) SetClientID(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Gateway_login_Params) Password() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Gateway_login_Params) HasPassword() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Gateway_login_Params) PasswordBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Gateway_login_Params) SetPassword(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// Gateway_login_Params_List is a list of Gateway_login_Params.
type Gateway_login_Params_List = capnp.StructList[Gateway_login_Params]

// NewGateway_login_Params creates a new list of Gateway_login_Params.
func NewGateway_login_Params_List(s *capnp.Segment, sz int32) (Gateway_login_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[Gateway_login_Params](l), err
}

// Gateway_login_Params_Future is a wrapper for a Gateway_login_Params promised by a client call.
type Gateway_login_Params_Future struct{ *capnp.Future }

func (p Gateway_login_Params_Future) Struct() (Gateway_login_Params, error) {
	s, err := p.Future.Struct()
	return Gateway_login_Params(s), err
}

type Gateway_login_Results capnp.Struct

// Gateway_login_Results_TypeID is the unique identifier for the type Gateway_login_Results.
const Gateway_login_Results_TypeID = 0x9838f96648ca7264

func NewGateway_login_Results(s *capnp.Segment) (Gateway_login_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Gateway_login_Results(st), err
}

func NewRootGateway_login_Results(s *capnp.Segment) (Gateway_login_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Gateway_login_Results(st), err
}

func ReadRootGateway_login_Results(msg *capnp.Message) (Gateway_login_Results, error) {
	root, err := msg.Root()
	return Gateway_login_Results(root.Struct()), err
}

func (s Gateway_login_Results) String() string {
	str, _ := text.Marshal(0x9838f96648ca7264, capnp.Struct(s))
	return str
}

func (s Gateway_login_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Gateway_login_Results) DecodeFromPtr(p capnp.Ptr) Gateway_login_Results {
	return Gateway_login_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Gateway_login_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Gateway_login_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Gateway_login_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Gateway_login_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Gateway_login_Results) ClientCertPEM() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Gateway_login_Results) HasClientCertPEM() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Gateway_login_Results) ClientCertPEMBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Gateway_login_Results) SetClientCertPEM(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// Gateway_login_Results_List is a list of Gateway_login_Results.
type Gateway_login_Results_List = capnp.StructList[Gateway_login_Results]

// NewGateway_login_Results creates a new list of Gateway_login_Results.
func NewGateway_login_Results_List(s *capnp.Segment, sz int32) (Gateway_login_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Gateway_login_Results](l), err
}

// Gateway_login_Results_Future is a wrapper for a Gateway_login_Results promised by a client call.
type Gateway_login_Results_Future struct{ *capnp.Future }

func (p Gateway_login_Results_Future) Struct() (Gateway_login_Results, error) {
	s, err := p.Future.Struct()
	return Gateway_login_Results(s), err
}

type Gateway_capabilities_Params capnp.Struct

// Gateway_capabilities_Params_TypeID is the unique identifier for the type Gateway_capabilities_Params.
const Gateway_capabilities_Params_TypeID = 0x87103ac78ef7acf7

func NewGateway_capabilities_Params(s *capnp.Segment) (Gateway_capabilities_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Gateway_capabilities_Params(st), err
}

func NewRootGateway_capabilities_Params(s *capnp.Segment) (Gateway_capabilities_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Gateway_capabilities_Params(st), err
}

func ReadRootGateway_capabilities_Params(msg *capnp.Message) (Gateway_capabilities_Params, error) {
	root, err := msg.Root()
	return Gateway_capabilities_Params(root.Struct()), err
}

func (s Gateway_capabilities_Params) String() string {
	str, _ := text.Marshal(0x87103ac78ef7acf7, capnp.Struct(s))
	return str
}

func (s Gateway_capabilities_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Gateway_capabilities_Params) DecodeFromPtr(p capnp.Ptr) Gateway_capabilities_Params {
	return Gateway_capabilities_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Gateway_capabilities_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Gateway_capabilities_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Gateway_capabilities_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Gateway_capabilities_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Gateway_capabilities_Params_List is a list of Gateway_capabilities_Params.
type Gateway_capabilities_Params_List = capnp.StructList[Gateway_capabilities_Params]

// NewGateway_capabilities_Params creates a new list of Gateway_capabilities_Params.
func NewGateway_capabilities_Params_List(s *capnp.Segment, sz int32) (Gateway_capabilities_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Gateway_capabilities_Params](l), err
}

// Gateway_capabilities_Params_Future is a wrapper for a Gateway_capabilities_Params promised by a client call.
type Gateway_capabilities_Params_Future struct{ *capnp.Future }

func (p Gateway_capabilities_Params_Future) Struct() (Gateway_capabilities_Params, error) {
	s, err := p.Future.Struct()
	return Gateway_capabilities_Params(s), err
}

type Gateway_capabilities_Results capnp.Struct

// Gateway_capabilities_Results_TypeID is the unique identifier for the type Gateway_capabilities_Results.
const Gateway_capabilities_Results_TypeID = 0xfb8d66387b9cc035

func NewGateway_capabilities_Results(s *capnp.Segment) (Gateway_capabilities_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Gateway_capabilities_Results(st), err
}

func NewRootGateway_capabilities_Results(s *capnp.Segment) (Gateway_capabilities_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Gateway_capabilities_Results(st), err
}

func ReadRootGateway_capabilities_Results(msg *capnp.Message) (Gateway_capabilities_Results, error) {
	root, err := msg.Root()
	return Gateway_capabilities_Results(root.Struct()), err
}

func (s Gateway_capabilities_Results) String() string {
	str, _ := text.Marshal(0xfb8d66387b9cc035, capnp.Struct(s))
	return str
}

func (s Gateway_capabilities_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Gateway_capabilities_Results) DecodeFromPtr(p capnp.Ptr) Gateway_capabilities_Results {
	return Gateway_capabilities_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Gateway_capabilities_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Gateway_capabilities_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Gateway_capabilities_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Gateway_capabilities_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Gateway_capabilities_Results) ClientCap() (ClientCapabilities, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return ClientCapabilities(p.Struct()), err
}

func (s Gateway_capabilities_Results) HasClientCap() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Gateway_capabilities_Results) SetClientCap(v ClientCapabilities) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewClientCap sets the clientCap field to a newly
// allocated ClientCapabilities struct, preferring placement in s's segment.
func (s Gateway_capabilities_Results) NewClientCap() (ClientCapabilities, error) {
	ss, err := NewClientCapabilities(capnp.Struct(s).Segment())
	if err != nil {
		return ClientCapabilities{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Gateway_capabilities_Results_List is a list of Gateway_capabilities_Results.
type Gateway_capabilities_Results_List = capnp.StructList[Gateway_capabilities_Results]

// NewGateway_capabilities_Results creates a new list of Gateway_capabilities_Results.
func NewGateway_capabilities_Results_List(s *capnp.Segment, sz int32) (Gateway_capabilities_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Gateway_capabilities_Results](l), err
}

// Gateway_capabilities_Results_Future is a wrapper for a Gateway_capabilities_Results promised by a client call.
type Gateway_capabilities_Results_Future struct{ *capnp.Future }

func (p Gateway_capabilities_Results_Future) Struct() (Gateway_capabilities_Results, error) {
	s, err := p.Future.Struct()
	return Gateway_capabilities_Results(s), err
}

func (p Gateway_capabilities_Results_Future) ClientCap() ClientCapabilities_Future {
	return ClientCapabilities_Future{Future: p.Future.Field(0, nil)}
}

const schema_dd3a962266ddd0e3 = "x\xda\x8c\x93\xcfKT]\x18\xc7\xbf\xcf=w\xde\xf1" +
	"}g\x06\xe70\xca[\x8b\x10J#\x17\x95\xf6\x83L" +
	"\x02%\x0bM\x0a\xe68\xabZu\x1d\xafzd\x9c{" +
	"\xbd\xf7\xaa\xdc\xb2U\x81?\xa0 \xa1(\x88\x16\xd2&" +
	"j\xe7?\x10\x18D\x82\x10\xb4\x8a\xb2MD\x14\xd5\"" +
	"\xa8!\"N\x9c\xd1\xb9N\xe5\xc2\xdd=\x0f\xdf\xe7\xfb" +
	"\xf9\x9e\xe7\xb9\xa7e\x91u\x9a\xad\xa9\xa1\xffa\xe4\xd2" +
	"\x14\xfbG\x95\x1e\x96\xae=iOO\x83\xef \xc0\x8c" +
	"\x03\x07o'\xe6\x08\xa6j\xb9?\xfb\xdf\xca\xee\xb9y" +
	"\xf0z\xa6\xde<[\x1d\xdcy\xb3}\x15\xa0\xccl\xe2" +
	"C\xe6F\"\x0ed\xae'\xa63o\xf5\x97\x1a\xf0\x96" +
	"{\x06\xbf\xb7\xddZ\xb3\x89\x91\xf6YI\x9c#P\xe6" +
	"E\xa2\x03\xa4V_\x1eu\xbeZ\xaf\x16\xd7\x05\x86\x16" +
	"\xfcL\xf4i\xc1\xbf\xc9I\x90\x8a\x7f\x9ey\xba\xf4\xa5" +
	"\xe9\x1bx=m\xe0b\xe5D\xa3\xc9\xe3\x94\xb9\x94\xd4" +
	"\xc80\xf9\x0e\xa4\x0e?\xbas\xb1m\xf0\xea\x8fj\x9c" +
	"\x95\x9a\xd7nc\xa9\x0e((<P\xc3\xe3\xfd\x96+" +
	"\xf7w\xc7\xac\xc0\x9e\xb4\xc2}y\xcb-\xba\xed\xdd\x1b" +
	"'\xab_\x16d m\xbf1ky\xd6\xa8\x0fD=" +
	"\xc6\x9f=\xb5\xfa\x98%\x125,\x06D\xd7\xa1\xca\xc5" +
	"y\xeb\x01\x18\xbc)N\x14\x8d\x94*)\xf9\xf6\x11\x18" +
	"\x9c\xc7\x1b\x0a\xce\x90,v\x92\xaa\xb0Q\xab\xe9\x9d\x94" +
	"%\x8a\xc8\xe6\xa6i\xcb\x9d\x8d}\xb6?^`\x81/" +
	"Lf\x02&\x01<\xe5\x01\"\xc9Hl3H\xe5\x0b" +
	"\xd2.\x06]6\x1a\xbc {\xf2\x0c%aP\x12[" +
	"\xf3.\x8f\x80|Q\x13Y7\xf7\x02b\x0f#q\xc8" +
	" NTG\xba\xd8\xaa\x8b-\x8c\xc4\xb1\x88w\xea\x04" +
	"\x80\x88\xe5Z\xbe?\xe9x\x03\xd5\xb5\xcd\xf9]ki" +
	"\xab\xf6\x00=\xe0t\x14\xc0\xba\x00\x88\xf3\x8cD\xa1*" +
	"\x80\x1c\x01\xc40#\x11\x18\xc4\x0d\xa3\x8e\x0c\x80\x8f\xe9" +
	")\xb8\x8c\xc4\x94A\x9c\xb1:b\x00\x0f\x17\x001\xc5" +
	"H\xcc\x18\xa4\x06\xa4g\xe7\x03\xc7CG\x98\x0b\x1c\xcf" +
	"&\xae\xc2O\x0b\xbd\xbbN\xdf\xfb\x08\x10q\x9dR\xfa" +
	"\x81\xe3\x859\xd4\xae\x0b\xea\xe5\x95\xf7\xa5\xc7G^W" +
	"\x04\xae\xe7\xb8\xb6\x17\x84h\xa8X\xf4\x9f\xe5\xa9\xbbK" +
	"\xbd\xcbU\x8a\x09\xe9K\x87\x8a\xb28\x94\xb3\xbd\x89\xb8" +
	"\xcck]\xe9\xf2\xe2^\xb3\xb9\xe7y\x84\xda\xfa\xafY" +
	"\xdey@\xbf\xed\xbc\xef\xef\x9d[ \x97\xd2\x1b\xaf\x08" +
	"Di\xd0\xaf\x00\x00\x00\xff\xff\xd0\x00$\xe6"

func init() {
	schemas.Register(schema_dd3a962266ddd0e3,
		0x87103ac78ef7acf7,
		0x928a26cd0a89a930,
		0x9838f96648ca7264,
		0xb3dc61f56f39dbdd,
		0xf625f2c3c988ee07,
		0xfb8d66387b9cc035)
}
