// Code generated by capnpc-go. DO NOT EDIT.

package hubapi

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
)

type ClientCapabilities capnp.Struct

// ClientCapabilities_TypeID is the unique identifier for the type ClientCapabilities.
const ClientCapabilities_TypeID = 0xf625f2c3c988ee07

func NewClientCapabilities(s *capnp.Segment) (ClientCapabilities, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return ClientCapabilities(st), err
}

func NewRootClientCapabilities(s *capnp.Segment) (ClientCapabilities, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return ClientCapabilities(st), err
}

func ReadRootClientCapabilities(msg *capnp.Message) (ClientCapabilities, error) {
	root, err := msg.Root()
	return ClientCapabilities(root.Struct()), err
}

func (s ClientCapabilities) String() string {
	str, _ := text.Marshal(0xf625f2c3c988ee07, capnp.Struct(s))
	return str
}

func (s ClientCapabilities) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ClientCapabilities) DecodeFromPtr(p capnp.Ptr) ClientCapabilities {
	return ClientCapabilities(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ClientCapabilities) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ClientCapabilities) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ClientCapabilities) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ClientCapabilities) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ClientCapabilities) DirectoryStore() DirectoryStore {
	p, _ := capnp.Struct(s).Ptr(0)
	return DirectoryStore(p.Interface().Client())
}

func (s ClientCapabilities) HasDirectoryStore() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ClientCapabilities) SetDirectoryStore(v DirectoryStore) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().AddCap(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(0, in.ToPtr())
}

func (s ClientCapabilities) HistoryStore() HistoryStore {
	p, _ := capnp.Struct(s).Ptr(1)
	return HistoryStore(p.Interface().Client())
}

func (s ClientCapabilities) HasHistoryStore() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ClientCapabilities) SetHistoryStore(v HistoryStore) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(1, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().AddCap(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(1, in.ToPtr())
}

func (s ClientCapabilities) PropertyStore() PropertyStore {
	p, _ := capnp.Struct(s).Ptr(2)
	return PropertyStore(p.Interface().Client())
}

func (s ClientCapabilities) HasPropertyStore() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s ClientCapabilities) SetPropertyStore(v PropertyStore) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(2, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().AddCap(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(2, in.ToPtr())
}

func (s ClientCapabilities) ProvisioningService() ProvisioningService {
	p, _ := capnp.Struct(s).Ptr(3)
	return ProvisioningService(p.Interface().Client())
}

func (s ClientCapabilities) HasProvisioningService() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s ClientCapabilities) SetProvisioningService(v ProvisioningService) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(3, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().AddCap(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(3, in.ToPtr())
}

// ClientCapabilities_List is a list of ClientCapabilities.
type ClientCapabilities_List = capnp.StructList[ClientCapabilities]

// NewClientCapabilities creates a new list of ClientCapabilities.
func NewClientCapabilities_List(s *capnp.Segment, sz int32) (ClientCapabilities_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4}, sz)
	return capnp.StructList[ClientCapabilities](l), err
}

// ClientCapabilities_Future is a wrapper for a ClientCapabilities promised by a client call.
type ClientCapabilities_Future struct{ *capnp.Future }

func (p ClientCapabilities_Future) Struct() (ClientCapabilities, error) {
	s, err := p.Future.Struct()
	return ClientCapabilities(s), err
}

func (p ClientCapabilities_Future) DirectoryStore() DirectoryStore {
	return DirectoryStore(p.Future.Field(0, nil).Client())
}

func (p ClientCapabilities_Future) HistoryStore() HistoryStore {
	return HistoryStore(p.Future.Field(1, nil).Client())
}

func (p ClientCapabilities_Future) PropertyStore() PropertyStore {
	return PropertyStore(p.Future.Field(2, nil).Client())
}

func (p ClientCapabilities_Future) ProvisioningService() ProvisioningService {
	return ProvisioningService(p.Future.Field(3, nil).Client())
}

type Gateway capnp.Client

// Gateway_TypeID is the unique identifier for the type Gateway.
const Gateway_TypeID = 0x928a26cd0a89a930

func (c Gateway) Login(ctx context.Context, params func(Gateway_login_Params) error) (Gateway_login_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x928a26cd0a89a930,
			MethodID:      0,
			InterfaceName: "hubapi/Gateway.capnp:Gateway",
			MethodName:    "login",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 2}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Gateway_login_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Gateway_login_Results_Future{Future: ans.Future()}, release
}
func (c Gateway) Capabilities(ctx context.Context, params func(Gateway_capabilities_Params) error) (Gateway_capabilities_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x928a26cd0a89a930,
			MethodID:      1,
			InterfaceName: "hubapi/Gateway.capnp:Gateway",
			MethodName:    "capabilities",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Gateway_capabilities_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Gateway_capabilities_Results_Future{Future: ans.Future()}, release
}

func (c Gateway) AddRef() Gateway {
	return Gateway(capnp.Client(c).AddRef())
}

func (c Gateway) Release() {
	capnp.Client(c).Release()
}

func (c Gateway) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Gateway) DecodeFromPtr(p capnp.Ptr) Gateway {
	return Gateway(capnp.Client{}.DecodeFromPtr(p))
}

func (c Gateway) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// A Gateway_Server is a Gateway with a local implementation.
type Gateway_Server interface {
	Login(context.Context, Gateway_login) error

	Capabilities(context.Context, Gateway_capabilities) error
}

// Gateway_NewServer creates a new Server from an implementation of Gateway_Server.
func Gateway_NewServer(s Gateway_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Gateway_Methods(nil, s), s, c)
}

// Gateway_ServerToClient creates a new Client from an implementation of Gateway_Server.
// The caller is responsible for calling Release on the returned Client.
func Gateway_ServerToClient(s Gateway_Server) Gateway {
	return Gateway(capnp.NewClient(Gateway_NewServer(s)))
}

// Gateway_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Gateway_Methods(methods []server.Method, s Gateway_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x928a26cd0a89a930,
			MethodID:      0,
			InterfaceName: "hubapi/Gateway.capnp:Gateway",
			MethodName:    "login",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Login(ctx, Gateway_login{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x928a26cd0a89a930,
			MethodID:      1,
			InterfaceName: "hubapi/Gateway.capnp:Gateway",
			MethodName:    "capabilities",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Capabilities(ctx, Gateway_capabilities{call})
		},
	})

	return methods
}

// Gateway_login holds the state for a server call to Gateway.login.
// See server.Call for documentation.
type Gateway_login struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Gateway_login) Args() Gateway_login_Params {
	return Gateway_login_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Gateway_login) AllocResults() (Gateway_login_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Gateway_login_Results(r), err
}

// Gateway_capabilities holds the state for a server call to Gateway.capabilities.
// See server.Call for documentation.
type Gateway_capabilities struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Gateway_capabilities) Args() Gateway_capabilities_Params {
	return Gateway_capabilities_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Gateway_capabilities) AllocResults() (Gateway_capabilities_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Gateway_capabilities_Results(r), err
}

// Gateway_List is a list of Gateway.
type Gateway_List = capnp.CapList[Gateway]

// NewGateway creates a new list of Gateway.
func NewGateway_List(s *capnp.Segment, sz int32) (Gateway_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Gateway](l), err
}

type Gateway_login_Params capnp.Struct

// Gateway_login_Params_TypeID is the unique identifier for the type Gateway_login_Params.
const Gateway_login_Params_TypeID = 0xb3dc61f56f39dbdd

func NewGateway_login_Params(s *capnp.Segment) (Gateway_login_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Gateway_login_Params(st), err
}

func NewRootGateway_login_Params(s *capnp.Segment) (Gateway_login_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Gateway_login_Params(st), err
}

func ReadRootGateway_login_Params(msg *capnp.Message) (Gateway_login_Params, error) {
	root, err := msg.Root()
	return Gateway_login_Params(root.Struct()), err
}

func (s Gateway_login_Params) String() string {
	str, _ := text.Marshal(0xb3dc61f56f39dbdd, capnp.Struct(s))
	return str
}

func (s Gateway_login_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Gateway_login_Params) DecodeFromPtr(p capnp.Ptr) Gateway_login_Params {
	return Gateway_login_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Gateway_login_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Gateway_login_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Gateway_login_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Gateway_login_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Gateway_login_Params) ClientID() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Gateway_login_Params) HasClientID() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Gateway_login_Params) ClientIDBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Gateway_login_Params) SetClientID(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Gateway_login_Params) Password() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Gateway_login_Params) HasPassword() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Gateway_login_Params) PasswordBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Gateway_login_Params) SetPassword(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// Gateway_login_Params_List is a list of Gateway_login_Params.
type Gateway_login_Params_List = capnp.StructList[Gateway_login_Params]

// NewGateway_login_Params creates a new list of Gateway_login_Params.
func NewGateway_login_Params_List(s *capnp.Segment, sz int32) (Gateway_login_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[Gateway_login_Params](l), err
}

// Gateway_login_Params_Future is a wrapper for a Gateway_login_Params promised by a client call.
type Gateway_login_Params_Future struct{ *capnp.Future }

func (p Gateway_login_Params_Future) Struct() (Gateway_login_Params, error) {
	s, err := p.Future.Struct()
	return Gateway_login_Params(s), err
}

type Gateway_login_Results capnp.Struct

// Gateway_login_Results_TypeID is the unique identifier for the type Gateway_login_Results.
const Gateway_login_Results_TypeID = 0x9838f96648ca7264

func NewGateway_login_Results(s *capnp.Segment) (Gateway_login_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Gateway_login_Results(st), err
}

func NewRootGateway_login_Results(s *capnp.Segment) (Gateway_login_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Gateway_login_Results(st), err
}

func ReadRootGateway_login_Results(msg *capnp.Message) (Gateway_login_Results, error) {
	root, err := msg.Root()
	return Gateway_login_Results(root.Struct()), err
}

func (s Gateway_login_Results) String() string {
	str, _ := text.Marshal(0x9838f96648ca7264, capnp.Struct(s))
	return str
}

func (s Gateway_login_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Gateway_login_Results) DecodeFromPtr(p capnp.Ptr) Gateway_login_Results {
	return Gateway_login_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Gateway_login_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Gateway_login_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Gateway_login_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Gateway_login_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Gateway_login_Results) ClientCertPEM() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Gateway_login_Results) HasClientCertPEM() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Gateway_login_Results) ClientCertPEMBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Gateway_login_Results) SetClientCertPEM(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// Gateway_login_Results_List is a list of Gateway_login_Results.
type Gateway_login_Results_List = capnp.StructList[Gateway_login_Results]

// NewGateway_login_Results creates a new list of Gateway_login_Results.
func NewGateway_login_Results_List(s *capnp.Segment, sz int32) (Gateway_login_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Gateway_login_Results](l), err
}

// Gateway_login_Results_Future is a wrapper for a Gateway_login_Results promised by a client call.
type Gateway_login_Results_Future struct{ *capnp.Future }

func (p Gateway_login_Results_Future) Struct() (Gateway_login_Results, error) {
	s, err := p.Future.Struct()
	return Gateway_login_Results(s), err
}

type Gateway_capabilities_Params capnp.Struct

// Gateway_capabilities_Params_TypeID is the unique identifier for the type Gateway_capabilities_Params.
const Gateway_capabilities_Params_TypeID = 0x87103ac78ef7acf7

func NewGateway_capabilities_Params(s *capnp.Segment) (Gateway_capabilities_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Gateway_capabilities_Params(st), err
}

func NewRootGateway_capabilities_Params(s *capnp.Segment) (Gateway_capabilities_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Gateway_capabilities_Params(st), err
}

func ReadRootGateway_capabilities_Params(msg *capnp.Message) (Gateway_capabilities_Params, error) {
	root, err := msg.Root()
	return Gateway_capabilities_Params(root.Struct()), err
}

func (s Gateway_capabilities_Params) String() string {
	str, _ := text.Marshal(0x87103ac78ef7acf7, capnp.Struct(s))
	return str
}

func (s Gateway_capabilities_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Gateway_capabilities_Params) DecodeFromPtr(p capnp.Ptr) Gateway_capabilities_Params {
	return Gateway_capabilities_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Gateway_capabilities_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Gateway_capabilities_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Gateway_capabilities_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Gateway_capabilities_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Gateway_capabilities_Params_List is a list of Gateway_capabilities_Params.
type Gateway_capabilities_Params_List = capnp.StructList[Gateway_capabilities_Params]

// NewGateway_capabilities_Params creates a new list of Gateway_capabilities_Params.
func NewGateway_capabilities_Params_List(s *capnp.Segment, sz int32) (Gateway_capabilities_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Gateway_capabilities_Params](l), err
}

// Gateway_capabilities_Params_Future is a wrapper for a Gateway_capabilities_Params promised by a client call.
type Gateway_capabilities_Params_Future struct{ *capnp.Future }

func (p Gateway_capabilities_Params_Future) Struct() (Gateway_capabilities_Params, error) {
	s, err := p.Future.Struct()
	return Gateway_capabilities_Params(s), err
}

type Gateway_capabilities_Results capnp.Struct

// Gateway_capabilities_Results_TypeID is the unique identifier for the type Gateway_capabilities_Results.
const Gateway_capabilities_Results_TypeID = 0xfb8d66387b9cc035

func NewGateway_capabilities_Results(s *capnp.Segment) (Gateway_capabilities_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Gateway_capabilities_Results(st), err
}

func NewRootGateway_capabilities_Results(s *capnp.Segment) (Gateway_capabilities_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Gateway_capabilities_Results(st), err
}

func ReadRootGateway_capabilities_Results(msg *capnp.Message) (Gateway_capabilities_Results, error) {
	root, err := msg.Root()
	return Gateway_capabilities_Results(root.Struct()), err
}

func (s Gateway_capabilities_Results) String() string {
	str, _ := text.Marshal(0xfb8d66387b9cc035, capnp.Struct(s))
	return str
}

func (s Gateway_capabilities_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Gateway_capabilities_Results) DecodeFromPtr(p capnp.Ptr) Gateway_capabilities_Results {
	return Gateway_capabilities_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Gateway_capabilities_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Gateway_capabilities_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Gateway_capabilities_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Gateway_capabilities_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Gateway_capabilities_Results) ClientCap() (ClientCapabilities, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return ClientCapabilities(p.Struct()), err
}

func (s Gateway_capabilities_Results) HasClientCap() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Gateway_capabilities_Results) SetClientCap(v ClientCapabilities) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewClientCap sets the clientCap field to a newly
// allocated ClientCapabilities struct, preferring placement in s's segment.
func (s Gateway_capabilities_Results) NewClientCap() (ClientCapabilities, error) {
	ss, err := NewClientCapabilities(capnp.Struct(s).Segment())
	if err != nil {
		return ClientCapabilities{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Gateway_capabilities_Results_List is a list of Gateway_capabilities_Results.
type Gateway_capabilities_Results_List = capnp.StructList[Gateway_capabilities_Results]

// NewGateway_capabilities_Results creates a new list of Gateway_capabilities_Results.
func NewGateway_capabilities_Results_List(s *capnp.Segment, sz int32) (Gateway_capabilities_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Gateway_capabilities_Results](l), err
}

// Gateway_capabilities_Results_Future is a wrapper for a Gateway_capabilities_Results promised by a client call.
type Gateway_capabilities_Results_Future struct{ *capnp.Future }

func (p Gateway_capabilities_Results_Future) Struct() (Gateway_capabilities_Results, error) {
	s, err := p.Future.Struct()
	return Gateway_capabilities_Results(s), err
}

func (p Gateway_capabilities_Results_Future) ClientCap() ClientCapabilities_Future {
	return ClientCapabilities_Future{Future: p.Future.Field(0, nil)}
}

const schema_dd3a962266ddd0e3 = "x\xda\x8c\x93\xc1K\x14a\x18\xc6\x9fw\xbe\xd9V\xc6" +
	"]\xdc\x8f]!\x0f\"\x94F\x1e*\xb7\x92T\x02%" +
	"\x0bM\x0a\xf6sO\xd5\xa5q\x1dud\xdd\x99fF" +
	"e\xca[\x85&\xd4\xc1Ct\xa8\x0e\x12\x84\xd0\xcd\x7f" +
	" 0\x88\x84 \xe8Xv\xe9\x10EE\x04\xb5D\x87" +
	"/\xbe\xd5\x1d\xb7\xf2\xe0m\xbe\x97\xe7}~\xcf\xf7\xbe" +
	"\xf3u\\b}z6\xf98\x03M|\x8b\xed\x91\xe5" +
	"'\xe5;\xcf{R\xf3\xe0\xcd\x04\xe8q\xe0X\xb7\xb1" +
	"H\xd0e\xc7\xca-\xe3\xe5\x81\xc5%\xf0F&\xdf\xbf" +
	"\xda\x18\xdbw\xb7g\x03\xa0t\xbb\xf1)\xddi\xc4\x81" +
	"t\xd6\x98O\xdfT_r\xd4[\x1f\x1c\xfb\xd5uo" +
	"\xd3&F\xcag\xca\xb8H\xa0th\xf4\x82\xe4\xc6\x9b" +
	"n\xe7\x87\xf9vuK\xa0)\xc1\x03cX\x09V\x8c" +
	"Y\x90\x8c\x7f]x\xb1\xf6\xbd\xed'x#m\xe3b" +
	"\x95D\xc9\xfaS\x94n\xaeW\xc8\xa6\xfa\x0f \xd9\xf9" +
	"\xf4\xfe\xb5\xae\xb1\xdb\xbfkq\x94XRn<\xd1\x0b" +
	"\x09\x89\xbc\x9c\x98\x1e1]\xfb\xc8@\xcc\x0c\xacY3" +
	"<\\0\xdd\x92\xdb3\xb0}2G\xec\xa2\x1d\xd8\x96" +
	"\xdf\x9a3=s\xca\x07\xa2\x1e\xed\xdf\x9e\x06u\xcc\x11" +
	"\x89:\x16\x03\xa2\xebP\xf5\xe2<{\x14\x1ao\x8b\x13" +
	"E#\xa5jJ\xde4\x09\x8d\xf3xK\xd1\x19\xb7K" +
	"}$\xabl4(z\x1f\xe5\x88\"\xb2\xbec\xdaJ" +
	"g\xeb\xb0\xe5O\x17Y\xe0\x0b\x9d\xe9\x80N\x00Oz" +
	"\x80H0\x12{5\x92\x85\xa2m\x95\x82~\x0b-^" +
	"\x90;s\x9e\x12\xd0(\x81\xddyWF@\xbe\xa8\x8b" +
	"\xac\xdb\x87\x00q\x90\x918\xae\x11'\xca\x90*fU" +
	"\xb1\x83\x918\x19\xf1\xce\x9e\x06\x10\xb1\\\xd3\xf7g\x1d" +
	"o\xb4\xb6\xb63\xbf\x7f3m\xcd\x1e\xa0\x06\x9c\x8a\x02" +
	"\x98W\x01q\x99\x91(\xd6\x04\xb0'\x011\xc1H\x04" +
	"\x1aqM\xcb\x90\x06\xf0+j\x0a.#1\xa7\x11g" +
	",C\x0c\xe0\xe12 \xe6\x18\x89\x05\x8d\xe4\xa8\xedY" +
	"\x85\xc0\xf1\xd0\x1b\xe6\x03\xc7\xb3\x88\xcb\xf0\xcb\xf2\xd0\xfe" +
	"s\x8f>\x03D\\\xa5\xb4\xfd\xc0\xf1\xc2<\x1a\xb6\x04" +
	"\x8d\xf6\x8d\x8f\xe5g'\xdeU\x05\xae\xe7\xb8\x96\x17\x84" +
	"h\xa9Z\x8c\\\xe0\xc9\x87kC\xeb5\x8a\x19\xdb\xb7" +
	"\x1d*\xd9\xa5\xf1\xbc\xe5\xcd\xc4\xed\x82\xd2\x95\xaf\xaf\x1e" +
	"\xd2\xdb\x07_G\xa8\xdd\xff\x9a\x95\x9d\x07\xf4\xd7\xce\x87" +
	"\xff\xdf\xb9\x09r)\xb5\xfd\x8a@\x94\x02\xfd\x09\x00\x00" +
	"\xff\xff\xea\xa8!\x01"

func init() {
	schemas.Register(schema_dd3a962266ddd0e3,
		0x87103ac78ef7acf7,
		0x928a26cd0a89a930,
		0x9838f96648ca7264,
		0xb3dc61f56f39dbdd,
		0xf625f2c3c988ee07,
		0xfb8d66387b9cc035)
}
