// Code generated by capnpc-go. DO NOT EDIT.

package hubapi

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
)

type ServiceInfo capnp.Struct

// ServiceInfo_TypeID is the unique identifier for the type ServiceInfo.
const ServiceInfo_TypeID = 0x8aa0c0b71a33baab

func NewServiceInfo(s *capnp.Segment) (ServiceInfo, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 40, PointerCount: 6})
	return ServiceInfo(st), err
}

func NewRootServiceInfo(s *capnp.Segment) (ServiceInfo, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 40, PointerCount: 6})
	return ServiceInfo(st), err
}

func ReadRootServiceInfo(msg *capnp.Message) (ServiceInfo, error) {
	root, err := msg.Root()
	return ServiceInfo(root.Struct()), err
}

func (s ServiceInfo) String() string {
	str, _ := text.Marshal(0x8aa0c0b71a33baab, capnp.Struct(s))
	return str
}

func (s ServiceInfo) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ServiceInfo) DecodeFromPtr(p capnp.Ptr) ServiceInfo {
	return ServiceInfo(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ServiceInfo) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ServiceInfo) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ServiceInfo) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ServiceInfo) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ServiceInfo) Cpu() int32 {
	return int32(capnp.Struct(s).Uint32(0))
}

func (s ServiceInfo) SetCpu(v int32) {
	capnp.Struct(s).SetUint32(0, uint32(v))
}

func (s ServiceInfo) Rss() int64 {
	return int64(capnp.Struct(s).Uint64(8))
}

func (s ServiceInfo) SetRss(v int64) {
	capnp.Struct(s).SetUint64(8, uint64(v))
}

func (s ServiceInfo) ModifiedTime() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ServiceInfo) HasModifiedTime() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ServiceInfo) ModifiedTimeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ServiceInfo) SetModifiedTime(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ServiceInfo) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ServiceInfo) HasName() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ServiceInfo) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ServiceInfo) SetName(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s ServiceInfo) Path() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s ServiceInfo) HasPath() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s ServiceInfo) PathBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s ServiceInfo) SetPath(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s ServiceInfo) Pid() int32 {
	return int32(capnp.Struct(s).Uint32(4))
}

func (s ServiceInfo) SetPid(v int32) {
	capnp.Struct(s).SetUint32(4, uint32(v))
}

func (s ServiceInfo) Running() bool {
	return capnp.Struct(s).Bit(128)
}

func (s ServiceInfo) SetRunning(v bool) {
	capnp.Struct(s).SetBit(128, v)
}

func (s ServiceInfo) Size() int64 {
	return int64(capnp.Struct(s).Uint64(24))
}

func (s ServiceInfo) SetSize(v int64) {
	capnp.Struct(s).SetUint64(24, uint64(v))
}

func (s ServiceInfo) Status() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s ServiceInfo) HasStatus() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s ServiceInfo) StatusBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s ServiceInfo) SetStatus(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s ServiceInfo) StartCount() int32 {
	return int32(capnp.Struct(s).Uint32(20))
}

func (s ServiceInfo) SetStartCount(v int32) {
	capnp.Struct(s).SetUint32(20, uint32(v))
}

func (s ServiceInfo) StartTime() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s ServiceInfo) HasStartTime() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s ServiceInfo) StartTimeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s ServiceInfo) SetStartTime(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s ServiceInfo) StopTime() (string, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.Text(), err
}

func (s ServiceInfo) HasStopTime() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s ServiceInfo) StopTimeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.TextBytes(), err
}

func (s ServiceInfo) SetStopTime(v string) error {
	return capnp.Struct(s).SetText(5, v)
}

func (s ServiceInfo) Uptime() int32 {
	return int32(capnp.Struct(s).Uint32(32))
}

func (s ServiceInfo) SetUptime(v int32) {
	capnp.Struct(s).SetUint32(32, uint32(v))
}

// ServiceInfo_List is a list of ServiceInfo.
type ServiceInfo_List = capnp.StructList[ServiceInfo]

// NewServiceInfo creates a new list of ServiceInfo.
func NewServiceInfo_List(s *capnp.Segment, sz int32) (ServiceInfo_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 40, PointerCount: 6}, sz)
	return capnp.StructList[ServiceInfo](l), err
}

// ServiceInfo_Future is a wrapper for a ServiceInfo promised by a client call.
type ServiceInfo_Future struct{ *capnp.Future }

func (p ServiceInfo_Future) Struct() (ServiceInfo, error) {
	s, err := p.Future.Struct()
	return ServiceInfo(s), err
}

type CapLauncher capnp.Client

// CapLauncher_TypeID is the unique identifier for the type CapLauncher.
const CapLauncher_TypeID = 0x96524352b99b59d2

func (c CapLauncher) List(ctx context.Context, params func(CapLauncher_list_Params) error) (CapLauncher_list_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x96524352b99b59d2,
			MethodID:      0,
			InterfaceName: "hubapi/Launcher.capnp:CapLauncher",
			MethodName:    "list",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CapLauncher_list_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CapLauncher_list_Results_Future{Future: ans.Future()}, release
}
func (c CapLauncher) Start(ctx context.Context, params func(CapLauncher_start_Params) error) (CapLauncher_start_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x96524352b99b59d2,
			MethodID:      1,
			InterfaceName: "hubapi/Launcher.capnp:CapLauncher",
			MethodName:    "start",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CapLauncher_start_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CapLauncher_start_Results_Future{Future: ans.Future()}, release
}
func (c CapLauncher) Stop(ctx context.Context, params func(CapLauncher_stop_Params) error) (CapLauncher_stop_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x96524352b99b59d2,
			MethodID:      2,
			InterfaceName: "hubapi/Launcher.capnp:CapLauncher",
			MethodName:    "stop",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CapLauncher_stop_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CapLauncher_stop_Results_Future{Future: ans.Future()}, release
}
func (c CapLauncher) StopAll(ctx context.Context, params func(CapLauncher_stopAll_Params) error) (CapLauncher_stopAll_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x96524352b99b59d2,
			MethodID:      3,
			InterfaceName: "hubapi/Launcher.capnp:CapLauncher",
			MethodName:    "stopAll",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CapLauncher_stopAll_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CapLauncher_stopAll_Results_Future{Future: ans.Future()}, release
}

func (c CapLauncher) AddRef() CapLauncher {
	return CapLauncher(capnp.Client(c).AddRef())
}

func (c CapLauncher) Release() {
	capnp.Client(c).Release()
}

func (c CapLauncher) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (CapLauncher) DecodeFromPtr(p capnp.Ptr) CapLauncher {
	return CapLauncher(capnp.Client{}.DecodeFromPtr(p))
}

func (c CapLauncher) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// A CapLauncher_Server is a CapLauncher with a local implementation.
type CapLauncher_Server interface {
	List(context.Context, CapLauncher_list) error

	Start(context.Context, CapLauncher_start) error

	Stop(context.Context, CapLauncher_stop) error

	StopAll(context.Context, CapLauncher_stopAll) error
}

// CapLauncher_NewServer creates a new Server from an implementation of CapLauncher_Server.
func CapLauncher_NewServer(s CapLauncher_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(CapLauncher_Methods(nil, s), s, c)
}

// CapLauncher_ServerToClient creates a new Client from an implementation of CapLauncher_Server.
// The caller is responsible for calling Release on the returned Client.
func CapLauncher_ServerToClient(s CapLauncher_Server) CapLauncher {
	return CapLauncher(capnp.NewClient(CapLauncher_NewServer(s)))
}

// CapLauncher_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func CapLauncher_Methods(methods []server.Method, s CapLauncher_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 4)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x96524352b99b59d2,
			MethodID:      0,
			InterfaceName: "hubapi/Launcher.capnp:CapLauncher",
			MethodName:    "list",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.List(ctx, CapLauncher_list{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x96524352b99b59d2,
			MethodID:      1,
			InterfaceName: "hubapi/Launcher.capnp:CapLauncher",
			MethodName:    "start",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Start(ctx, CapLauncher_start{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x96524352b99b59d2,
			MethodID:      2,
			InterfaceName: "hubapi/Launcher.capnp:CapLauncher",
			MethodName:    "stop",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Stop(ctx, CapLauncher_stop{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x96524352b99b59d2,
			MethodID:      3,
			InterfaceName: "hubapi/Launcher.capnp:CapLauncher",
			MethodName:    "stopAll",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.StopAll(ctx, CapLauncher_stopAll{call})
		},
	})

	return methods
}

// CapLauncher_list holds the state for a server call to CapLauncher.list.
// See server.Call for documentation.
type CapLauncher_list struct {
	*server.Call
}

// Args returns the call's arguments.
func (c CapLauncher_list) Args() CapLauncher_list_Params {
	return CapLauncher_list_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c CapLauncher_list) AllocResults() (CapLauncher_list_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_list_Results(r), err
}

// CapLauncher_start holds the state for a server call to CapLauncher.start.
// See server.Call for documentation.
type CapLauncher_start struct {
	*server.Call
}

// Args returns the call's arguments.
func (c CapLauncher_start) Args() CapLauncher_start_Params {
	return CapLauncher_start_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c CapLauncher_start) AllocResults() (CapLauncher_start_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_start_Results(r), err
}

// CapLauncher_stop holds the state for a server call to CapLauncher.stop.
// See server.Call for documentation.
type CapLauncher_stop struct {
	*server.Call
}

// Args returns the call's arguments.
func (c CapLauncher_stop) Args() CapLauncher_stop_Params {
	return CapLauncher_stop_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c CapLauncher_stop) AllocResults() (CapLauncher_stop_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_stop_Results(r), err
}

// CapLauncher_stopAll holds the state for a server call to CapLauncher.stopAll.
// See server.Call for documentation.
type CapLauncher_stopAll struct {
	*server.Call
}

// Args returns the call's arguments.
func (c CapLauncher_stopAll) Args() CapLauncher_stopAll_Params {
	return CapLauncher_stopAll_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c CapLauncher_stopAll) AllocResults() (CapLauncher_stopAll_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CapLauncher_stopAll_Results(r), err
}

// CapLauncher_List is a list of CapLauncher.
type CapLauncher_List = capnp.CapList[CapLauncher]

// NewCapLauncher creates a new list of CapLauncher.
func NewCapLauncher_List(s *capnp.Segment, sz int32) (CapLauncher_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[CapLauncher](l), err
}

type CapLauncher_list_Params capnp.Struct

// CapLauncher_list_Params_TypeID is the unique identifier for the type CapLauncher_list_Params.
const CapLauncher_list_Params_TypeID = 0xd43c617d04683d01

func NewCapLauncher_list_Params(s *capnp.Segment) (CapLauncher_list_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return CapLauncher_list_Params(st), err
}

func NewRootCapLauncher_list_Params(s *capnp.Segment) (CapLauncher_list_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return CapLauncher_list_Params(st), err
}

func ReadRootCapLauncher_list_Params(msg *capnp.Message) (CapLauncher_list_Params, error) {
	root, err := msg.Root()
	return CapLauncher_list_Params(root.Struct()), err
}

func (s CapLauncher_list_Params) String() string {
	str, _ := text.Marshal(0xd43c617d04683d01, capnp.Struct(s))
	return str
}

func (s CapLauncher_list_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapLauncher_list_Params) DecodeFromPtr(p capnp.Ptr) CapLauncher_list_Params {
	return CapLauncher_list_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapLauncher_list_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapLauncher_list_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapLauncher_list_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapLauncher_list_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapLauncher_list_Params) OnlyRunning() bool {
	return capnp.Struct(s).Bit(0)
}

func (s CapLauncher_list_Params) SetOnlyRunning(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

// CapLauncher_list_Params_List is a list of CapLauncher_list_Params.
type CapLauncher_list_Params_List = capnp.StructList[CapLauncher_list_Params]

// NewCapLauncher_list_Params creates a new list of CapLauncher_list_Params.
func NewCapLauncher_list_Params_List(s *capnp.Segment, sz int32) (CapLauncher_list_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[CapLauncher_list_Params](l), err
}

// CapLauncher_list_Params_Future is a wrapper for a CapLauncher_list_Params promised by a client call.
type CapLauncher_list_Params_Future struct{ *capnp.Future }

func (p CapLauncher_list_Params_Future) Struct() (CapLauncher_list_Params, error) {
	s, err := p.Future.Struct()
	return CapLauncher_list_Params(s), err
}

type CapLauncher_list_Results capnp.Struct

// CapLauncher_list_Results_TypeID is the unique identifier for the type CapLauncher_list_Results.
const CapLauncher_list_Results_TypeID = 0xa7b81c0bbc4ab3a8

func NewCapLauncher_list_Results(s *capnp.Segment) (CapLauncher_list_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_list_Results(st), err
}

func NewRootCapLauncher_list_Results(s *capnp.Segment) (CapLauncher_list_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_list_Results(st), err
}

func ReadRootCapLauncher_list_Results(msg *capnp.Message) (CapLauncher_list_Results, error) {
	root, err := msg.Root()
	return CapLauncher_list_Results(root.Struct()), err
}

func (s CapLauncher_list_Results) String() string {
	str, _ := text.Marshal(0xa7b81c0bbc4ab3a8, capnp.Struct(s))
	return str
}

func (s CapLauncher_list_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapLauncher_list_Results) DecodeFromPtr(p capnp.Ptr) CapLauncher_list_Results {
	return CapLauncher_list_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapLauncher_list_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapLauncher_list_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapLauncher_list_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapLauncher_list_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapLauncher_list_Results) InfoList() (ServiceInfo_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return ServiceInfo_List(p.List()), err
}

func (s CapLauncher_list_Results) HasInfoList() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CapLauncher_list_Results) SetInfoList(v ServiceInfo_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewInfoList sets the infoList field to a newly
// allocated ServiceInfo_List, preferring placement in s's segment.
func (s CapLauncher_list_Results) NewInfoList(n int32) (ServiceInfo_List, error) {
	l, err := NewServiceInfo_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return ServiceInfo_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// CapLauncher_list_Results_List is a list of CapLauncher_list_Results.
type CapLauncher_list_Results_List = capnp.StructList[CapLauncher_list_Results]

// NewCapLauncher_list_Results creates a new list of CapLauncher_list_Results.
func NewCapLauncher_list_Results_List(s *capnp.Segment, sz int32) (CapLauncher_list_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[CapLauncher_list_Results](l), err
}

// CapLauncher_list_Results_Future is a wrapper for a CapLauncher_list_Results promised by a client call.
type CapLauncher_list_Results_Future struct{ *capnp.Future }

func (p CapLauncher_list_Results_Future) Struct() (CapLauncher_list_Results, error) {
	s, err := p.Future.Struct()
	return CapLauncher_list_Results(s), err
}

type CapLauncher_start_Params capnp.Struct

// CapLauncher_start_Params_TypeID is the unique identifier for the type CapLauncher_start_Params.
const CapLauncher_start_Params_TypeID = 0x9dd032618f0a61da

func NewCapLauncher_start_Params(s *capnp.Segment) (CapLauncher_start_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_start_Params(st), err
}

func NewRootCapLauncher_start_Params(s *capnp.Segment) (CapLauncher_start_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_start_Params(st), err
}

func ReadRootCapLauncher_start_Params(msg *capnp.Message) (CapLauncher_start_Params, error) {
	root, err := msg.Root()
	return CapLauncher_start_Params(root.Struct()), err
}

func (s CapLauncher_start_Params) String() string {
	str, _ := text.Marshal(0x9dd032618f0a61da, capnp.Struct(s))
	return str
}

func (s CapLauncher_start_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapLauncher_start_Params) DecodeFromPtr(p capnp.Ptr) CapLauncher_start_Params {
	return CapLauncher_start_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapLauncher_start_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapLauncher_start_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapLauncher_start_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapLauncher_start_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapLauncher_start_Params) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CapLauncher_start_Params) HasName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CapLauncher_start_Params) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CapLauncher_start_Params) SetName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// CapLauncher_start_Params_List is a list of CapLauncher_start_Params.
type CapLauncher_start_Params_List = capnp.StructList[CapLauncher_start_Params]

// NewCapLauncher_start_Params creates a new list of CapLauncher_start_Params.
func NewCapLauncher_start_Params_List(s *capnp.Segment, sz int32) (CapLauncher_start_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[CapLauncher_start_Params](l), err
}

// CapLauncher_start_Params_Future is a wrapper for a CapLauncher_start_Params promised by a client call.
type CapLauncher_start_Params_Future struct{ *capnp.Future }

func (p CapLauncher_start_Params_Future) Struct() (CapLauncher_start_Params, error) {
	s, err := p.Future.Struct()
	return CapLauncher_start_Params(s), err
}

type CapLauncher_start_Results capnp.Struct

// CapLauncher_start_Results_TypeID is the unique identifier for the type CapLauncher_start_Results.
const CapLauncher_start_Results_TypeID = 0xef6591cc288ebded

func NewCapLauncher_start_Results(s *capnp.Segment) (CapLauncher_start_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_start_Results(st), err
}

func NewRootCapLauncher_start_Results(s *capnp.Segment) (CapLauncher_start_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_start_Results(st), err
}

func ReadRootCapLauncher_start_Results(msg *capnp.Message) (CapLauncher_start_Results, error) {
	root, err := msg.Root()
	return CapLauncher_start_Results(root.Struct()), err
}

func (s CapLauncher_start_Results) String() string {
	str, _ := text.Marshal(0xef6591cc288ebded, capnp.Struct(s))
	return str
}

func (s CapLauncher_start_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapLauncher_start_Results) DecodeFromPtr(p capnp.Ptr) CapLauncher_start_Results {
	return CapLauncher_start_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapLauncher_start_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapLauncher_start_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapLauncher_start_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapLauncher_start_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapLauncher_start_Results) Info() (ServiceInfo, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return ServiceInfo(p.Struct()), err
}

func (s CapLauncher_start_Results) HasInfo() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CapLauncher_start_Results) SetInfo(v ServiceInfo) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewInfo sets the info field to a newly
// allocated ServiceInfo struct, preferring placement in s's segment.
func (s CapLauncher_start_Results) NewInfo() (ServiceInfo, error) {
	ss, err := NewServiceInfo(capnp.Struct(s).Segment())
	if err != nil {
		return ServiceInfo{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// CapLauncher_start_Results_List is a list of CapLauncher_start_Results.
type CapLauncher_start_Results_List = capnp.StructList[CapLauncher_start_Results]

// NewCapLauncher_start_Results creates a new list of CapLauncher_start_Results.
func NewCapLauncher_start_Results_List(s *capnp.Segment, sz int32) (CapLauncher_start_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[CapLauncher_start_Results](l), err
}

// CapLauncher_start_Results_Future is a wrapper for a CapLauncher_start_Results promised by a client call.
type CapLauncher_start_Results_Future struct{ *capnp.Future }

func (p CapLauncher_start_Results_Future) Struct() (CapLauncher_start_Results, error) {
	s, err := p.Future.Struct()
	return CapLauncher_start_Results(s), err
}

func (p CapLauncher_start_Results_Future) Info() ServiceInfo_Future {
	return ServiceInfo_Future{Future: p.Future.Field(0, nil)}
}

type CapLauncher_stop_Params capnp.Struct

// CapLauncher_stop_Params_TypeID is the unique identifier for the type CapLauncher_stop_Params.
const CapLauncher_stop_Params_TypeID = 0xa4f2766999f82f48

func NewCapLauncher_stop_Params(s *capnp.Segment) (CapLauncher_stop_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_stop_Params(st), err
}

func NewRootCapLauncher_stop_Params(s *capnp.Segment) (CapLauncher_stop_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_stop_Params(st), err
}

func ReadRootCapLauncher_stop_Params(msg *capnp.Message) (CapLauncher_stop_Params, error) {
	root, err := msg.Root()
	return CapLauncher_stop_Params(root.Struct()), err
}

func (s CapLauncher_stop_Params) String() string {
	str, _ := text.Marshal(0xa4f2766999f82f48, capnp.Struct(s))
	return str
}

func (s CapLauncher_stop_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapLauncher_stop_Params) DecodeFromPtr(p capnp.Ptr) CapLauncher_stop_Params {
	return CapLauncher_stop_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapLauncher_stop_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapLauncher_stop_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapLauncher_stop_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapLauncher_stop_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapLauncher_stop_Params) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CapLauncher_stop_Params) HasName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CapLauncher_stop_Params) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CapLauncher_stop_Params) SetName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// CapLauncher_stop_Params_List is a list of CapLauncher_stop_Params.
type CapLauncher_stop_Params_List = capnp.StructList[CapLauncher_stop_Params]

// NewCapLauncher_stop_Params creates a new list of CapLauncher_stop_Params.
func NewCapLauncher_stop_Params_List(s *capnp.Segment, sz int32) (CapLauncher_stop_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[CapLauncher_stop_Params](l), err
}

// CapLauncher_stop_Params_Future is a wrapper for a CapLauncher_stop_Params promised by a client call.
type CapLauncher_stop_Params_Future struct{ *capnp.Future }

func (p CapLauncher_stop_Params_Future) Struct() (CapLauncher_stop_Params, error) {
	s, err := p.Future.Struct()
	return CapLauncher_stop_Params(s), err
}

type CapLauncher_stop_Results capnp.Struct

// CapLauncher_stop_Results_TypeID is the unique identifier for the type CapLauncher_stop_Results.
const CapLauncher_stop_Results_TypeID = 0xd606313032e1634f

func NewCapLauncher_stop_Results(s *capnp.Segment) (CapLauncher_stop_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_stop_Results(st), err
}

func NewRootCapLauncher_stop_Results(s *capnp.Segment) (CapLauncher_stop_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_stop_Results(st), err
}

func ReadRootCapLauncher_stop_Results(msg *capnp.Message) (CapLauncher_stop_Results, error) {
	root, err := msg.Root()
	return CapLauncher_stop_Results(root.Struct()), err
}

func (s CapLauncher_stop_Results) String() string {
	str, _ := text.Marshal(0xd606313032e1634f, capnp.Struct(s))
	return str
}

func (s CapLauncher_stop_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapLauncher_stop_Results) DecodeFromPtr(p capnp.Ptr) CapLauncher_stop_Results {
	return CapLauncher_stop_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapLauncher_stop_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapLauncher_stop_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapLauncher_stop_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapLauncher_stop_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapLauncher_stop_Results) Info() (ServiceInfo, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return ServiceInfo(p.Struct()), err
}

func (s CapLauncher_stop_Results) HasInfo() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CapLauncher_stop_Results) SetInfo(v ServiceInfo) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewInfo sets the info field to a newly
// allocated ServiceInfo struct, preferring placement in s's segment.
func (s CapLauncher_stop_Results) NewInfo() (ServiceInfo, error) {
	ss, err := NewServiceInfo(capnp.Struct(s).Segment())
	if err != nil {
		return ServiceInfo{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// CapLauncher_stop_Results_List is a list of CapLauncher_stop_Results.
type CapLauncher_stop_Results_List = capnp.StructList[CapLauncher_stop_Results]

// NewCapLauncher_stop_Results creates a new list of CapLauncher_stop_Results.
func NewCapLauncher_stop_Results_List(s *capnp.Segment, sz int32) (CapLauncher_stop_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[CapLauncher_stop_Results](l), err
}

// CapLauncher_stop_Results_Future is a wrapper for a CapLauncher_stop_Results promised by a client call.
type CapLauncher_stop_Results_Future struct{ *capnp.Future }

func (p CapLauncher_stop_Results_Future) Struct() (CapLauncher_stop_Results, error) {
	s, err := p.Future.Struct()
	return CapLauncher_stop_Results(s), err
}

func (p CapLauncher_stop_Results_Future) Info() ServiceInfo_Future {
	return ServiceInfo_Future{Future: p.Future.Field(0, nil)}
}

type CapLauncher_stopAll_Params capnp.Struct

// CapLauncher_stopAll_Params_TypeID is the unique identifier for the type CapLauncher_stopAll_Params.
const CapLauncher_stopAll_Params_TypeID = 0xe4f33c61c382a6a7

func NewCapLauncher_stopAll_Params(s *capnp.Segment) (CapLauncher_stopAll_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CapLauncher_stopAll_Params(st), err
}

func NewRootCapLauncher_stopAll_Params(s *capnp.Segment) (CapLauncher_stopAll_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CapLauncher_stopAll_Params(st), err
}

func ReadRootCapLauncher_stopAll_Params(msg *capnp.Message) (CapLauncher_stopAll_Params, error) {
	root, err := msg.Root()
	return CapLauncher_stopAll_Params(root.Struct()), err
}

func (s CapLauncher_stopAll_Params) String() string {
	str, _ := text.Marshal(0xe4f33c61c382a6a7, capnp.Struct(s))
	return str
}

func (s CapLauncher_stopAll_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapLauncher_stopAll_Params) DecodeFromPtr(p capnp.Ptr) CapLauncher_stopAll_Params {
	return CapLauncher_stopAll_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapLauncher_stopAll_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapLauncher_stopAll_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapLauncher_stopAll_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapLauncher_stopAll_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CapLauncher_stopAll_Params_List is a list of CapLauncher_stopAll_Params.
type CapLauncher_stopAll_Params_List = capnp.StructList[CapLauncher_stopAll_Params]

// NewCapLauncher_stopAll_Params creates a new list of CapLauncher_stopAll_Params.
func NewCapLauncher_stopAll_Params_List(s *capnp.Segment, sz int32) (CapLauncher_stopAll_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CapLauncher_stopAll_Params](l), err
}

// CapLauncher_stopAll_Params_Future is a wrapper for a CapLauncher_stopAll_Params promised by a client call.
type CapLauncher_stopAll_Params_Future struct{ *capnp.Future }

func (p CapLauncher_stopAll_Params_Future) Struct() (CapLauncher_stopAll_Params, error) {
	s, err := p.Future.Struct()
	return CapLauncher_stopAll_Params(s), err
}

type CapLauncher_stopAll_Results capnp.Struct

// CapLauncher_stopAll_Results_TypeID is the unique identifier for the type CapLauncher_stopAll_Results.
const CapLauncher_stopAll_Results_TypeID = 0xb7dbdb4757bf491e

func NewCapLauncher_stopAll_Results(s *capnp.Segment) (CapLauncher_stopAll_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CapLauncher_stopAll_Results(st), err
}

func NewRootCapLauncher_stopAll_Results(s *capnp.Segment) (CapLauncher_stopAll_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CapLauncher_stopAll_Results(st), err
}

func ReadRootCapLauncher_stopAll_Results(msg *capnp.Message) (CapLauncher_stopAll_Results, error) {
	root, err := msg.Root()
	return CapLauncher_stopAll_Results(root.Struct()), err
}

func (s CapLauncher_stopAll_Results) String() string {
	str, _ := text.Marshal(0xb7dbdb4757bf491e, capnp.Struct(s))
	return str
}

func (s CapLauncher_stopAll_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapLauncher_stopAll_Results) DecodeFromPtr(p capnp.Ptr) CapLauncher_stopAll_Results {
	return CapLauncher_stopAll_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapLauncher_stopAll_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapLauncher_stopAll_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapLauncher_stopAll_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapLauncher_stopAll_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CapLauncher_stopAll_Results_List is a list of CapLauncher_stopAll_Results.
type CapLauncher_stopAll_Results_List = capnp.StructList[CapLauncher_stopAll_Results]

// NewCapLauncher_stopAll_Results creates a new list of CapLauncher_stopAll_Results.
func NewCapLauncher_stopAll_Results_List(s *capnp.Segment, sz int32) (CapLauncher_stopAll_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CapLauncher_stopAll_Results](l), err
}

// CapLauncher_stopAll_Results_Future is a wrapper for a CapLauncher_stopAll_Results promised by a client call.
type CapLauncher_stopAll_Results_Future struct{ *capnp.Future }

func (p CapLauncher_stopAll_Results_Future) Struct() (CapLauncher_stopAll_Results, error) {
	s, err := p.Future.Struct()
	return CapLauncher_stopAll_Results(s), err
}

const schema_e42f87955bd521e9 = "x\xda\xac\x94Oh\x1c\xe5\x1f\xc6\x9f\xe7\x9d\x7f\xf9\xd7" +
	"_2\x9d\xa1\xfc\x10k1\xe4\xd0\x06l\xdaDEJ" +
	"e\x93\xe6\xa0\x09\x11\xb3;\x15\xad\x9a\xc34\x99\xb8#" +
	"\xbb\xb3\xd3\x9d\x99\xd2\x94\x96\xd6\xd2\xa2\x16\xffc\xa5\"" +
	"\x85\x1e\x8aU<\x8aTEQ\x10o\x1eT\xac\x82=" +
	"\x88\xd0\x8b\x07\x11\xf5\xe2EF\xbe\xb3N\xb2\x95VR" +
	"\xf0\xb4;\x9f\xf7\xf9>\xf3\xfd\xbe\xef\xf3\xce\x8e\xbb\xd5" +
	"\xa4\xbes\xc3w:T\xf5\x1e\xc3\xcc\xdf\xf9p\xe2\x96" +
	"K\x9f\x9e?\x8d\xea&\x1a\xf9O\xb7_~\xec\xcc\xd3" +
	"cWa\x98\x160QU\x1b\xe9\xf8J\xfe.\xa8\x1f" +
	"\x14\x98\x7f\xbd\xef\x8d\x0fj\xd3\xb5\xd7`o\xd2\xd6\xd4" +
	"\xe0\xc4\x82\xb1\x91N\xd3\x10ihXtz\xc5 \xff" +
	"\xde\xef{\xd1\x1f\xff\xf2\x1c\xeca\x02\x06e\xf9W\xe3" +
	"0A\xe7O\xa3\x02\xe6\xf7\x8f\xfd\xf1zx\xf0\xb7\x0b" +
	"\xdd\x82\xcdf[\x04\xdbL\x11\xbc\xf5\xee\xecG\xfd\xb7" +
	"\xbe\x7f\xb1[0c\x16\x0e\x0f\x15\x82\xdbf>y\xf8" +
	"\xbe+W.u\x04\xba\xac?k\xbeB\xe89\xef\xad" +
	"\xebG\xfd\xdd\xdf\xa0:\xccri\xa5\xe3}\xaa(}" +
	"p\xf1\xc7\xf1\x1d;\xcdo\xbb\xbd\xdf\xeex\xbfW\x08" +
	".\xbey\xe23\x7f\xf7\xefW\xbb\xbc/\x9b\xa7\xc5\xfb" +
	"\xe7\x8f_\xd8\xfa\xc5\xcb\xc1/\xdd\xa5\x9f\x9b'\xa4\xf4" +
	"+\xb3\x82;\xf2z\xb6\xdf\x8f\xc3\xb19\xcd\xcf\xa2\xc5" +
	"z\xd0\xde\xbe\xe8\xc7Q\xbc\xcb\x0b\xda\x07\xc3\xc5`&" +
	"Zfk\x9e\xac\xde\xa9\xe9\x80N\xc0Y\xe00\xe0=" +
	"B\x8d\xde\x12\x15m\xd2\x95\xae\x1d\xbf\xe0\x8f\x0b\xafS" +
	"\x91\xca\xa5\x02\x9c\x80O\x02\xde\x92\xe0X\xe4\x1a]j" +
	"\x80\xd3\xe4(\xe0\xd5\x85\xa7\xc2u\xe5R\x07\x9c\x03\x05" +
	"o\x08?$\xdc\xa0K\x03p\xb2\xc2>\x16~D\xb8" +
	"y\xdc\xa5\x098+\xdc\x03x\xa9\xf0\xe3\xc2-\xcd\x95" +
	"!\x9d\xa3\x85\xcf!\xe1'\x85\xf7h.{\x00\xe7)" +
	"\xee\x02\xbc#\xc2\x9f\x11\xdek\xb8\xec\x05\x9cS|\x14" +
	"\xf0N\x0a\x7fIx\x9f\xee\xb2\x0fp\x9eg\x0d\xf0\x9e" +
	"\x13~Vx\xbf\xe1\xb2\x1fp\xcep\x16\xf0^\x15~" +
	"^\xf8@\x8f\xcb\x01\xc09W\xf8\x9f\x15~\x81\x8a\xd6" +
	"b\x9cQ\x87\xa2\x0eZ\xed$\xa1\x01E\x03\xcc\x9b\xad" +
	"\xa5p9\x0c\x960\xb87l\x06\x1c\x80\xe2\x008\x18" +
	"\xf9]\x0f\xb1\x9f\xd6\xcb\x07+\x0e\x97J\xa3c\xed," +
	"\x8a\xc2\xe8\x09\x12\x8a\x04\x07\x93\xf0pP:W\x92\xd4" +
	"O\xb3\xa4\xac\xcb\x93\xd4o\xa7\xd3\xad\x0cZ\x94\x96\x06" +
	"\x1d\xb87l\x82A\x97\xb0\x15K/\x00JV\xc9\xe2" +
	"T\xba+\xcbn\x10\x96i?\x9e\xeb\x10\xb6%,C" +
	"\x9a\x01\xac\xc6\x9a\xe5\xd5\xb0\x0f\x8cB\xd9\x81E\xae\xde" +
	"7\x96\xf9\xb4\xf7\x8dC\xd9\x0fXT\xabW\x8de\xec" +
	"\xed)\xa9\xbb\xcb\xa2\xb6\x1at\x96\xb7\xc9\xde\xb6\x07\xca" +
	"\xdel\x0d6\xc2$\x9d\xe4\x96b\xb0I\x0e\xca0\x93" +
	"<&?S\x8d\xc6$\xe7\xb9\xd6\xbd~\xa3\xee\xdb\xdb" +
	"\x8b\xf2\x91\xca\xbc\xdf\xf6\x9bIU/Coo\x18\x05" +
	"\xaa=\x1a\xab\xae\xba\xf6\x8c\xd6g\xda\x8aG\xe6\xb7\xfc" +
	"\xa7\x9e2\xeeH\xad\x12$Y#\xbd\xc6t\x16\xa8\x0e" +
	"h\xacnU\xcc\xc3h\xb95\x17&\xa9\x9c\xe8\xff\xc0" +
	"y\x8d\x1cZ\xfb\x90\x82\x02W_f\xfc\xfb\x00S\x8d" +
	"\xc6H\xadx\x1d\x93u7x\x9d\xa1\xf7\xff\xdd\xdf\xff" +
	"\x15\xf3V\xd4X\xa9eQ\x04\xab+\xcc\xeb\xde\xd1\xeb" +
	"M\xdf\xbd\xa52\xfd?\xe6\x1d\xba\xb9y;1\x00\xd6" +
	"W#\xc9\xe9\xecP\x82\x9b\xeb\xe9\xaf\x00\x00\x00\xff\xff" +
	"o3\xb2\x9a"

func init() {
	schemas.Register(schema_e42f87955bd521e9,
		0x8aa0c0b71a33baab,
		0x96524352b99b59d2,
		0x9dd032618f0a61da,
		0xa4f2766999f82f48,
		0xa7b81c0bbc4ab3a8,
		0xb7dbdb4757bf491e,
		0xd43c617d04683d01,
		0xd606313032e1634f,
		0xe4f33c61c382a6a7,
		0xef6591cc288ebded)
}
