// Code generated by capnpc-go. DO NOT EDIT.

package hubapi

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
	fmt "fmt"
)

type ServiceInfo capnp.Struct

// ServiceInfo_TypeID is the unique identifier for the type ServiceInfo.
const ServiceInfo_TypeID = 0x8aa0c0b71a33baab

func NewServiceInfo(s *capnp.Segment) (ServiceInfo, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 40, PointerCount: 6})
	return ServiceInfo(st), err
}

func NewRootServiceInfo(s *capnp.Segment) (ServiceInfo, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 40, PointerCount: 6})
	return ServiceInfo(st), err
}

func ReadRootServiceInfo(msg *capnp.Message) (ServiceInfo, error) {
	root, err := msg.Root()
	return ServiceInfo(root.Struct()), err
}

func (s ServiceInfo) String() string {
	str, _ := text.Marshal(0x8aa0c0b71a33baab, capnp.Struct(s))
	return str
}

func (s ServiceInfo) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ServiceInfo) DecodeFromPtr(p capnp.Ptr) ServiceInfo {
	return ServiceInfo(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ServiceInfo) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ServiceInfo) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ServiceInfo) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ServiceInfo) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ServiceInfo) Cpu() int32 {
	return int32(capnp.Struct(s).Uint32(0))
}

func (s ServiceInfo) SetCpu(v int32) {
	capnp.Struct(s).SetUint32(0, uint32(v))
}

func (s ServiceInfo) Rss() int64 {
	return int64(capnp.Struct(s).Uint64(8))
}

func (s ServiceInfo) SetRss(v int64) {
	capnp.Struct(s).SetUint64(8, uint64(v))
}

func (s ServiceInfo) ModifiedTime() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ServiceInfo) HasModifiedTime() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ServiceInfo) ModifiedTimeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ServiceInfo) SetModifiedTime(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ServiceInfo) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ServiceInfo) HasName() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ServiceInfo) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ServiceInfo) SetName(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s ServiceInfo) Path() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s ServiceInfo) HasPath() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s ServiceInfo) PathBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s ServiceInfo) SetPath(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s ServiceInfo) Pid() int32 {
	return int32(capnp.Struct(s).Uint32(4))
}

func (s ServiceInfo) SetPid(v int32) {
	capnp.Struct(s).SetUint32(4, uint32(v))
}

func (s ServiceInfo) Running() bool {
	return capnp.Struct(s).Bit(128)
}

func (s ServiceInfo) SetRunning(v bool) {
	capnp.Struct(s).SetBit(128, v)
}

func (s ServiceInfo) Size() int64 {
	return int64(capnp.Struct(s).Uint64(24))
}

func (s ServiceInfo) SetSize(v int64) {
	capnp.Struct(s).SetUint64(24, uint64(v))
}

func (s ServiceInfo) Status() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s ServiceInfo) HasStatus() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s ServiceInfo) StatusBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s ServiceInfo) SetStatus(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s ServiceInfo) StartCount() int32 {
	return int32(capnp.Struct(s).Uint32(20))
}

func (s ServiceInfo) SetStartCount(v int32) {
	capnp.Struct(s).SetUint32(20, uint32(v))
}

func (s ServiceInfo) StartTime() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s ServiceInfo) HasStartTime() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s ServiceInfo) StartTimeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s ServiceInfo) SetStartTime(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s ServiceInfo) StopTime() (string, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.Text(), err
}

func (s ServiceInfo) HasStopTime() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s ServiceInfo) StopTimeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.TextBytes(), err
}

func (s ServiceInfo) SetStopTime(v string) error {
	return capnp.Struct(s).SetText(5, v)
}

func (s ServiceInfo) Uptime() int32 {
	return int32(capnp.Struct(s).Uint32(32))
}

func (s ServiceInfo) SetUptime(v int32) {
	capnp.Struct(s).SetUint32(32, uint32(v))
}

// ServiceInfo_List is a list of ServiceInfo.
type ServiceInfo_List = capnp.StructList[ServiceInfo]

// NewServiceInfo creates a new list of ServiceInfo.
func NewServiceInfo_List(s *capnp.Segment, sz int32) (ServiceInfo_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 40, PointerCount: 6}, sz)
	return capnp.StructList[ServiceInfo](l), err
}

// ServiceInfo_Future is a wrapper for a ServiceInfo promised by a client call.
type ServiceInfo_Future struct{ *capnp.Future }

func (f ServiceInfo_Future) Struct() (ServiceInfo, error) {
	p, err := f.Future.Ptr()
	return ServiceInfo(p.Struct()), err
}

type CapLauncher capnp.Client

// CapLauncher_TypeID is the unique identifier for the type CapLauncher.
const CapLauncher_TypeID = 0x96524352b99b59d2

func (c CapLauncher) List(ctx context.Context, params func(CapLauncher_list_Params) error) (CapLauncher_list_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x96524352b99b59d2,
			MethodID:      0,
			InterfaceName: "hubapi/Launcher.capnp:CapLauncher",
			MethodName:    "list",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CapLauncher_list_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CapLauncher_list_Results_Future{Future: ans.Future()}, release
}
func (c CapLauncher) Start(ctx context.Context, params func(CapLauncher_start_Params) error) (CapLauncher_start_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x96524352b99b59d2,
			MethodID:      1,
			InterfaceName: "hubapi/Launcher.capnp:CapLauncher",
			MethodName:    "start",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CapLauncher_start_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CapLauncher_start_Results_Future{Future: ans.Future()}, release
}
func (c CapLauncher) Stop(ctx context.Context, params func(CapLauncher_stop_Params) error) (CapLauncher_stop_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x96524352b99b59d2,
			MethodID:      2,
			InterfaceName: "hubapi/Launcher.capnp:CapLauncher",
			MethodName:    "stop",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CapLauncher_stop_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CapLauncher_stop_Results_Future{Future: ans.Future()}, release
}
func (c CapLauncher) StopAll(ctx context.Context, params func(CapLauncher_stopAll_Params) error) (CapLauncher_stopAll_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x96524352b99b59d2,
			MethodID:      3,
			InterfaceName: "hubapi/Launcher.capnp:CapLauncher",
			MethodName:    "stopAll",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CapLauncher_stopAll_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CapLauncher_stopAll_Results_Future{Future: ans.Future()}, release
}
func (c CapLauncher) GetCapability(ctx context.Context, params func(CapHiveOTService_getCapability_Params) error) (CapHiveOTService_getCapability_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xe7182cfc5650a2c2,
			MethodID:      0,
			InterfaceName: "hubapi/Service.capnp:CapHiveOTService",
			MethodName:    "getCapability",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 4}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CapHiveOTService_getCapability_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CapHiveOTService_getCapability_Results_Future{Future: ans.Future()}, release
}
func (c CapLauncher) ListCapabilities(ctx context.Context, params func(CapHiveOTService_listCapabilities_Params) error) (CapHiveOTService_listCapabilities_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xe7182cfc5650a2c2,
			MethodID:      1,
			InterfaceName: "hubapi/Service.capnp:CapHiveOTService",
			MethodName:    "listCapabilities",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CapHiveOTService_listCapabilities_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CapHiveOTService_listCapabilities_Results_Future{Future: ans.Future()}, release
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c CapLauncher) String() string {
	return fmt.Sprintf("%T(%v)", c, capnp.Client(c))
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c CapLauncher) AddRef() CapLauncher {
	return CapLauncher(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c CapLauncher) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c CapLauncher) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c CapLauncher) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (CapLauncher) DecodeFromPtr(p capnp.Ptr) CapLauncher {
	return CapLauncher(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c CapLauncher) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c CapLauncher) IsSame(other CapLauncher) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c CapLauncher) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c CapLauncher) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
} // A CapLauncher_Server is a CapLauncher with a local implementation.
type CapLauncher_Server interface {
	List(context.Context, CapLauncher_list) error

	Start(context.Context, CapLauncher_start) error

	Stop(context.Context, CapLauncher_stop) error

	StopAll(context.Context, CapLauncher_stopAll) error

	GetCapability(context.Context, CapHiveOTService_getCapability) error

	ListCapabilities(context.Context, CapHiveOTService_listCapabilities) error
}

// CapLauncher_NewServer creates a new Server from an implementation of CapLauncher_Server.
func CapLauncher_NewServer(s CapLauncher_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(CapLauncher_Methods(nil, s), s, c)
}

// CapLauncher_ServerToClient creates a new Client from an implementation of CapLauncher_Server.
// The caller is responsible for calling Release on the returned Client.
func CapLauncher_ServerToClient(s CapLauncher_Server) CapLauncher {
	return CapLauncher(capnp.NewClient(CapLauncher_NewServer(s)))
}

// CapLauncher_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func CapLauncher_Methods(methods []server.Method, s CapLauncher_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 6)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x96524352b99b59d2,
			MethodID:      0,
			InterfaceName: "hubapi/Launcher.capnp:CapLauncher",
			MethodName:    "list",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.List(ctx, CapLauncher_list{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x96524352b99b59d2,
			MethodID:      1,
			InterfaceName: "hubapi/Launcher.capnp:CapLauncher",
			MethodName:    "start",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Start(ctx, CapLauncher_start{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x96524352b99b59d2,
			MethodID:      2,
			InterfaceName: "hubapi/Launcher.capnp:CapLauncher",
			MethodName:    "stop",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Stop(ctx, CapLauncher_stop{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x96524352b99b59d2,
			MethodID:      3,
			InterfaceName: "hubapi/Launcher.capnp:CapLauncher",
			MethodName:    "stopAll",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.StopAll(ctx, CapLauncher_stopAll{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xe7182cfc5650a2c2,
			MethodID:      0,
			InterfaceName: "hubapi/Service.capnp:CapHiveOTService",
			MethodName:    "getCapability",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.GetCapability(ctx, CapHiveOTService_getCapability{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xe7182cfc5650a2c2,
			MethodID:      1,
			InterfaceName: "hubapi/Service.capnp:CapHiveOTService",
			MethodName:    "listCapabilities",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.ListCapabilities(ctx, CapHiveOTService_listCapabilities{call})
		},
	})

	return methods
}

// CapLauncher_list holds the state for a server call to CapLauncher.list.
// See server.Call for documentation.
type CapLauncher_list struct {
	*server.Call
}

// Args returns the call's arguments.
func (c CapLauncher_list) Args() CapLauncher_list_Params {
	return CapLauncher_list_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c CapLauncher_list) AllocResults() (CapLauncher_list_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_list_Results(r), err
}

// CapLauncher_start holds the state for a server call to CapLauncher.start.
// See server.Call for documentation.
type CapLauncher_start struct {
	*server.Call
}

// Args returns the call's arguments.
func (c CapLauncher_start) Args() CapLauncher_start_Params {
	return CapLauncher_start_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c CapLauncher_start) AllocResults() (CapLauncher_start_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_start_Results(r), err
}

// CapLauncher_stop holds the state for a server call to CapLauncher.stop.
// See server.Call for documentation.
type CapLauncher_stop struct {
	*server.Call
}

// Args returns the call's arguments.
func (c CapLauncher_stop) Args() CapLauncher_stop_Params {
	return CapLauncher_stop_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c CapLauncher_stop) AllocResults() (CapLauncher_stop_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_stop_Results(r), err
}

// CapLauncher_stopAll holds the state for a server call to CapLauncher.stopAll.
// See server.Call for documentation.
type CapLauncher_stopAll struct {
	*server.Call
}

// Args returns the call's arguments.
func (c CapLauncher_stopAll) Args() CapLauncher_stopAll_Params {
	return CapLauncher_stopAll_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c CapLauncher_stopAll) AllocResults() (CapLauncher_stopAll_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CapLauncher_stopAll_Results(r), err
}

// CapLauncher_List is a list of CapLauncher.
type CapLauncher_List = capnp.CapList[CapLauncher]

// NewCapLauncher creates a new list of CapLauncher.
func NewCapLauncher_List(s *capnp.Segment, sz int32) (CapLauncher_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[CapLauncher](l), err
}

type CapLauncher_list_Params capnp.Struct

// CapLauncher_list_Params_TypeID is the unique identifier for the type CapLauncher_list_Params.
const CapLauncher_list_Params_TypeID = 0xd43c617d04683d01

func NewCapLauncher_list_Params(s *capnp.Segment) (CapLauncher_list_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return CapLauncher_list_Params(st), err
}

func NewRootCapLauncher_list_Params(s *capnp.Segment) (CapLauncher_list_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return CapLauncher_list_Params(st), err
}

func ReadRootCapLauncher_list_Params(msg *capnp.Message) (CapLauncher_list_Params, error) {
	root, err := msg.Root()
	return CapLauncher_list_Params(root.Struct()), err
}

func (s CapLauncher_list_Params) String() string {
	str, _ := text.Marshal(0xd43c617d04683d01, capnp.Struct(s))
	return str
}

func (s CapLauncher_list_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapLauncher_list_Params) DecodeFromPtr(p capnp.Ptr) CapLauncher_list_Params {
	return CapLauncher_list_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapLauncher_list_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapLauncher_list_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapLauncher_list_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapLauncher_list_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapLauncher_list_Params) OnlyRunning() bool {
	return capnp.Struct(s).Bit(0)
}

func (s CapLauncher_list_Params) SetOnlyRunning(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

// CapLauncher_list_Params_List is a list of CapLauncher_list_Params.
type CapLauncher_list_Params_List = capnp.StructList[CapLauncher_list_Params]

// NewCapLauncher_list_Params creates a new list of CapLauncher_list_Params.
func NewCapLauncher_list_Params_List(s *capnp.Segment, sz int32) (CapLauncher_list_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[CapLauncher_list_Params](l), err
}

// CapLauncher_list_Params_Future is a wrapper for a CapLauncher_list_Params promised by a client call.
type CapLauncher_list_Params_Future struct{ *capnp.Future }

func (f CapLauncher_list_Params_Future) Struct() (CapLauncher_list_Params, error) {
	p, err := f.Future.Ptr()
	return CapLauncher_list_Params(p.Struct()), err
}

type CapLauncher_list_Results capnp.Struct

// CapLauncher_list_Results_TypeID is the unique identifier for the type CapLauncher_list_Results.
const CapLauncher_list_Results_TypeID = 0xa7b81c0bbc4ab3a8

func NewCapLauncher_list_Results(s *capnp.Segment) (CapLauncher_list_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_list_Results(st), err
}

func NewRootCapLauncher_list_Results(s *capnp.Segment) (CapLauncher_list_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_list_Results(st), err
}

func ReadRootCapLauncher_list_Results(msg *capnp.Message) (CapLauncher_list_Results, error) {
	root, err := msg.Root()
	return CapLauncher_list_Results(root.Struct()), err
}

func (s CapLauncher_list_Results) String() string {
	str, _ := text.Marshal(0xa7b81c0bbc4ab3a8, capnp.Struct(s))
	return str
}

func (s CapLauncher_list_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapLauncher_list_Results) DecodeFromPtr(p capnp.Ptr) CapLauncher_list_Results {
	return CapLauncher_list_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapLauncher_list_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapLauncher_list_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapLauncher_list_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapLauncher_list_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapLauncher_list_Results) InfoList() (ServiceInfo_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return ServiceInfo_List(p.List()), err
}

func (s CapLauncher_list_Results) HasInfoList() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CapLauncher_list_Results) SetInfoList(v ServiceInfo_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewInfoList sets the infoList field to a newly
// allocated ServiceInfo_List, preferring placement in s's segment.
func (s CapLauncher_list_Results) NewInfoList(n int32) (ServiceInfo_List, error) {
	l, err := NewServiceInfo_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return ServiceInfo_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// CapLauncher_list_Results_List is a list of CapLauncher_list_Results.
type CapLauncher_list_Results_List = capnp.StructList[CapLauncher_list_Results]

// NewCapLauncher_list_Results creates a new list of CapLauncher_list_Results.
func NewCapLauncher_list_Results_List(s *capnp.Segment, sz int32) (CapLauncher_list_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[CapLauncher_list_Results](l), err
}

// CapLauncher_list_Results_Future is a wrapper for a CapLauncher_list_Results promised by a client call.
type CapLauncher_list_Results_Future struct{ *capnp.Future }

func (f CapLauncher_list_Results_Future) Struct() (CapLauncher_list_Results, error) {
	p, err := f.Future.Ptr()
	return CapLauncher_list_Results(p.Struct()), err
}

type CapLauncher_start_Params capnp.Struct

// CapLauncher_start_Params_TypeID is the unique identifier for the type CapLauncher_start_Params.
const CapLauncher_start_Params_TypeID = 0x9dd032618f0a61da

func NewCapLauncher_start_Params(s *capnp.Segment) (CapLauncher_start_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_start_Params(st), err
}

func NewRootCapLauncher_start_Params(s *capnp.Segment) (CapLauncher_start_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_start_Params(st), err
}

func ReadRootCapLauncher_start_Params(msg *capnp.Message) (CapLauncher_start_Params, error) {
	root, err := msg.Root()
	return CapLauncher_start_Params(root.Struct()), err
}

func (s CapLauncher_start_Params) String() string {
	str, _ := text.Marshal(0x9dd032618f0a61da, capnp.Struct(s))
	return str
}

func (s CapLauncher_start_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapLauncher_start_Params) DecodeFromPtr(p capnp.Ptr) CapLauncher_start_Params {
	return CapLauncher_start_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapLauncher_start_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapLauncher_start_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapLauncher_start_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapLauncher_start_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapLauncher_start_Params) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CapLauncher_start_Params) HasName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CapLauncher_start_Params) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CapLauncher_start_Params) SetName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// CapLauncher_start_Params_List is a list of CapLauncher_start_Params.
type CapLauncher_start_Params_List = capnp.StructList[CapLauncher_start_Params]

// NewCapLauncher_start_Params creates a new list of CapLauncher_start_Params.
func NewCapLauncher_start_Params_List(s *capnp.Segment, sz int32) (CapLauncher_start_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[CapLauncher_start_Params](l), err
}

// CapLauncher_start_Params_Future is a wrapper for a CapLauncher_start_Params promised by a client call.
type CapLauncher_start_Params_Future struct{ *capnp.Future }

func (f CapLauncher_start_Params_Future) Struct() (CapLauncher_start_Params, error) {
	p, err := f.Future.Ptr()
	return CapLauncher_start_Params(p.Struct()), err
}

type CapLauncher_start_Results capnp.Struct

// CapLauncher_start_Results_TypeID is the unique identifier for the type CapLauncher_start_Results.
const CapLauncher_start_Results_TypeID = 0xef6591cc288ebded

func NewCapLauncher_start_Results(s *capnp.Segment) (CapLauncher_start_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_start_Results(st), err
}

func NewRootCapLauncher_start_Results(s *capnp.Segment) (CapLauncher_start_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_start_Results(st), err
}

func ReadRootCapLauncher_start_Results(msg *capnp.Message) (CapLauncher_start_Results, error) {
	root, err := msg.Root()
	return CapLauncher_start_Results(root.Struct()), err
}

func (s CapLauncher_start_Results) String() string {
	str, _ := text.Marshal(0xef6591cc288ebded, capnp.Struct(s))
	return str
}

func (s CapLauncher_start_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapLauncher_start_Results) DecodeFromPtr(p capnp.Ptr) CapLauncher_start_Results {
	return CapLauncher_start_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapLauncher_start_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapLauncher_start_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapLauncher_start_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapLauncher_start_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapLauncher_start_Results) Info() (ServiceInfo, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return ServiceInfo(p.Struct()), err
}

func (s CapLauncher_start_Results) HasInfo() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CapLauncher_start_Results) SetInfo(v ServiceInfo) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewInfo sets the info field to a newly
// allocated ServiceInfo struct, preferring placement in s's segment.
func (s CapLauncher_start_Results) NewInfo() (ServiceInfo, error) {
	ss, err := NewServiceInfo(capnp.Struct(s).Segment())
	if err != nil {
		return ServiceInfo{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// CapLauncher_start_Results_List is a list of CapLauncher_start_Results.
type CapLauncher_start_Results_List = capnp.StructList[CapLauncher_start_Results]

// NewCapLauncher_start_Results creates a new list of CapLauncher_start_Results.
func NewCapLauncher_start_Results_List(s *capnp.Segment, sz int32) (CapLauncher_start_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[CapLauncher_start_Results](l), err
}

// CapLauncher_start_Results_Future is a wrapper for a CapLauncher_start_Results promised by a client call.
type CapLauncher_start_Results_Future struct{ *capnp.Future }

func (f CapLauncher_start_Results_Future) Struct() (CapLauncher_start_Results, error) {
	p, err := f.Future.Ptr()
	return CapLauncher_start_Results(p.Struct()), err
}
func (p CapLauncher_start_Results_Future) Info() ServiceInfo_Future {
	return ServiceInfo_Future{Future: p.Future.Field(0, nil)}
}

type CapLauncher_stop_Params capnp.Struct

// CapLauncher_stop_Params_TypeID is the unique identifier for the type CapLauncher_stop_Params.
const CapLauncher_stop_Params_TypeID = 0xa4f2766999f82f48

func NewCapLauncher_stop_Params(s *capnp.Segment) (CapLauncher_stop_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_stop_Params(st), err
}

func NewRootCapLauncher_stop_Params(s *capnp.Segment) (CapLauncher_stop_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_stop_Params(st), err
}

func ReadRootCapLauncher_stop_Params(msg *capnp.Message) (CapLauncher_stop_Params, error) {
	root, err := msg.Root()
	return CapLauncher_stop_Params(root.Struct()), err
}

func (s CapLauncher_stop_Params) String() string {
	str, _ := text.Marshal(0xa4f2766999f82f48, capnp.Struct(s))
	return str
}

func (s CapLauncher_stop_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapLauncher_stop_Params) DecodeFromPtr(p capnp.Ptr) CapLauncher_stop_Params {
	return CapLauncher_stop_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapLauncher_stop_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapLauncher_stop_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapLauncher_stop_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapLauncher_stop_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapLauncher_stop_Params) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CapLauncher_stop_Params) HasName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CapLauncher_stop_Params) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CapLauncher_stop_Params) SetName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// CapLauncher_stop_Params_List is a list of CapLauncher_stop_Params.
type CapLauncher_stop_Params_List = capnp.StructList[CapLauncher_stop_Params]

// NewCapLauncher_stop_Params creates a new list of CapLauncher_stop_Params.
func NewCapLauncher_stop_Params_List(s *capnp.Segment, sz int32) (CapLauncher_stop_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[CapLauncher_stop_Params](l), err
}

// CapLauncher_stop_Params_Future is a wrapper for a CapLauncher_stop_Params promised by a client call.
type CapLauncher_stop_Params_Future struct{ *capnp.Future }

func (f CapLauncher_stop_Params_Future) Struct() (CapLauncher_stop_Params, error) {
	p, err := f.Future.Ptr()
	return CapLauncher_stop_Params(p.Struct()), err
}

type CapLauncher_stop_Results capnp.Struct

// CapLauncher_stop_Results_TypeID is the unique identifier for the type CapLauncher_stop_Results.
const CapLauncher_stop_Results_TypeID = 0xd606313032e1634f

func NewCapLauncher_stop_Results(s *capnp.Segment) (CapLauncher_stop_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_stop_Results(st), err
}

func NewRootCapLauncher_stop_Results(s *capnp.Segment) (CapLauncher_stop_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_stop_Results(st), err
}

func ReadRootCapLauncher_stop_Results(msg *capnp.Message) (CapLauncher_stop_Results, error) {
	root, err := msg.Root()
	return CapLauncher_stop_Results(root.Struct()), err
}

func (s CapLauncher_stop_Results) String() string {
	str, _ := text.Marshal(0xd606313032e1634f, capnp.Struct(s))
	return str
}

func (s CapLauncher_stop_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapLauncher_stop_Results) DecodeFromPtr(p capnp.Ptr) CapLauncher_stop_Results {
	return CapLauncher_stop_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapLauncher_stop_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapLauncher_stop_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapLauncher_stop_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapLauncher_stop_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapLauncher_stop_Results) Info() (ServiceInfo, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return ServiceInfo(p.Struct()), err
}

func (s CapLauncher_stop_Results) HasInfo() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CapLauncher_stop_Results) SetInfo(v ServiceInfo) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewInfo sets the info field to a newly
// allocated ServiceInfo struct, preferring placement in s's segment.
func (s CapLauncher_stop_Results) NewInfo() (ServiceInfo, error) {
	ss, err := NewServiceInfo(capnp.Struct(s).Segment())
	if err != nil {
		return ServiceInfo{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// CapLauncher_stop_Results_List is a list of CapLauncher_stop_Results.
type CapLauncher_stop_Results_List = capnp.StructList[CapLauncher_stop_Results]

// NewCapLauncher_stop_Results creates a new list of CapLauncher_stop_Results.
func NewCapLauncher_stop_Results_List(s *capnp.Segment, sz int32) (CapLauncher_stop_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[CapLauncher_stop_Results](l), err
}

// CapLauncher_stop_Results_Future is a wrapper for a CapLauncher_stop_Results promised by a client call.
type CapLauncher_stop_Results_Future struct{ *capnp.Future }

func (f CapLauncher_stop_Results_Future) Struct() (CapLauncher_stop_Results, error) {
	p, err := f.Future.Ptr()
	return CapLauncher_stop_Results(p.Struct()), err
}
func (p CapLauncher_stop_Results_Future) Info() ServiceInfo_Future {
	return ServiceInfo_Future{Future: p.Future.Field(0, nil)}
}

type CapLauncher_stopAll_Params capnp.Struct

// CapLauncher_stopAll_Params_TypeID is the unique identifier for the type CapLauncher_stopAll_Params.
const CapLauncher_stopAll_Params_TypeID = 0xe4f33c61c382a6a7

func NewCapLauncher_stopAll_Params(s *capnp.Segment) (CapLauncher_stopAll_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CapLauncher_stopAll_Params(st), err
}

func NewRootCapLauncher_stopAll_Params(s *capnp.Segment) (CapLauncher_stopAll_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CapLauncher_stopAll_Params(st), err
}

func ReadRootCapLauncher_stopAll_Params(msg *capnp.Message) (CapLauncher_stopAll_Params, error) {
	root, err := msg.Root()
	return CapLauncher_stopAll_Params(root.Struct()), err
}

func (s CapLauncher_stopAll_Params) String() string {
	str, _ := text.Marshal(0xe4f33c61c382a6a7, capnp.Struct(s))
	return str
}

func (s CapLauncher_stopAll_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapLauncher_stopAll_Params) DecodeFromPtr(p capnp.Ptr) CapLauncher_stopAll_Params {
	return CapLauncher_stopAll_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapLauncher_stopAll_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapLauncher_stopAll_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapLauncher_stopAll_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapLauncher_stopAll_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CapLauncher_stopAll_Params_List is a list of CapLauncher_stopAll_Params.
type CapLauncher_stopAll_Params_List = capnp.StructList[CapLauncher_stopAll_Params]

// NewCapLauncher_stopAll_Params creates a new list of CapLauncher_stopAll_Params.
func NewCapLauncher_stopAll_Params_List(s *capnp.Segment, sz int32) (CapLauncher_stopAll_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CapLauncher_stopAll_Params](l), err
}

// CapLauncher_stopAll_Params_Future is a wrapper for a CapLauncher_stopAll_Params promised by a client call.
type CapLauncher_stopAll_Params_Future struct{ *capnp.Future }

func (f CapLauncher_stopAll_Params_Future) Struct() (CapLauncher_stopAll_Params, error) {
	p, err := f.Future.Ptr()
	return CapLauncher_stopAll_Params(p.Struct()), err
}

type CapLauncher_stopAll_Results capnp.Struct

// CapLauncher_stopAll_Results_TypeID is the unique identifier for the type CapLauncher_stopAll_Results.
const CapLauncher_stopAll_Results_TypeID = 0xb7dbdb4757bf491e

func NewCapLauncher_stopAll_Results(s *capnp.Segment) (CapLauncher_stopAll_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CapLauncher_stopAll_Results(st), err
}

func NewRootCapLauncher_stopAll_Results(s *capnp.Segment) (CapLauncher_stopAll_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CapLauncher_stopAll_Results(st), err
}

func ReadRootCapLauncher_stopAll_Results(msg *capnp.Message) (CapLauncher_stopAll_Results, error) {
	root, err := msg.Root()
	return CapLauncher_stopAll_Results(root.Struct()), err
}

func (s CapLauncher_stopAll_Results) String() string {
	str, _ := text.Marshal(0xb7dbdb4757bf491e, capnp.Struct(s))
	return str
}

func (s CapLauncher_stopAll_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapLauncher_stopAll_Results) DecodeFromPtr(p capnp.Ptr) CapLauncher_stopAll_Results {
	return CapLauncher_stopAll_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapLauncher_stopAll_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapLauncher_stopAll_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapLauncher_stopAll_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapLauncher_stopAll_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CapLauncher_stopAll_Results_List is a list of CapLauncher_stopAll_Results.
type CapLauncher_stopAll_Results_List = capnp.StructList[CapLauncher_stopAll_Results]

// NewCapLauncher_stopAll_Results creates a new list of CapLauncher_stopAll_Results.
func NewCapLauncher_stopAll_Results_List(s *capnp.Segment, sz int32) (CapLauncher_stopAll_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CapLauncher_stopAll_Results](l), err
}

// CapLauncher_stopAll_Results_Future is a wrapper for a CapLauncher_stopAll_Results promised by a client call.
type CapLauncher_stopAll_Results_Future struct{ *capnp.Future }

func (f CapLauncher_stopAll_Results_Future) Struct() (CapLauncher_stopAll_Results, error) {
	p, err := f.Future.Ptr()
	return CapLauncher_stopAll_Results(p.Struct()), err
}

const schema_e42f87955bd521e9 = "x\xda\xac\x94Mh\x1cu\x18\xc6\x9f\xe7?3;\xdb" +
	"&1\x99\xceP\x8b\xa8\xc5\x90C\x0d\xda\xb4\x89\x1e," +
	"-\x9b4\x07m\x88\x98\xdd\x0dj\xfc8L\x93\x89;" +
	"\xb2;;\xdd\x99-mhi-\x0dJ\xf1+b\xa4" +
	"\"\x81*\xc5\x0a\x1eE\xaa\xa2\xf8\x857\x0f\"\xea\xc1" +
	"\x1eD\xa8\x88\x07\x11\xf5\xe2A\x18yg\x9d\xedTZ" +
	"M\xc1S2\xbf\xff\xfb>\xf3>\xffy\xde\xdd\xb1\xac" +
	"\xc6\xf5\x9d}%\x13\xaa<k\x14\x927\xdf\x1b\xbb\xe1" +
	"\xfcGgN\xa1\xbc\x99F\xf2\xd3-_?\xbc\xfa\xe4" +
	"\xc8E\x18\x05\x13\x18[\xd66\xd1^\xd5\xe4\xdf\x15\xed" +
	";\x05&_\xce\xbd\xf2ne\xb2\xf2\x12\xac\xcd\xda\xa5" +
	"jpl\xa5\xb0\x89\xf6\xabi\xd7Z\xc1\xa4\xbd\xc7\xbc" +
	"\x1eH\xbeu7>\xe7\x8e~\xb1\x06k\x90\x80A9" +
	"\xbe\xdd\\\"h\xdfe\x96\xc0\xe4\x9e\x91?^\xf6\x0f" +
	"\xfev6_0g\xb6\xa4\xc0K\x0b\xdexk\xea\xfd" +
	"\x9e\x1b\xdf9\x97/X\xee(\xac\xa4\x057\xef\xfb\xf0" +
	"\x81\xbb/\\8\xdf)\xd0\xe5\xfc3\xf3\x05BO\xb8" +
	"\xa7\xa6\x1fuw\x7f\x85\xf2 \xb3\xa3\xb7;\xda\x1f\xa7" +
	"\xad\xf7\xcd\x7f?\xbacg\xe1\x9b\xbc\xf6\x0f\x1d\xed_" +
	"\xd3\x82s\xaf\x9f\xf8\xd4\xdd\xfd\xfb\xc5\x9c\xb6U<%" +
	"\xda?\x7f\xf0\xec\xb6\xcfW\xbc_\xf2\xad,\x9e\x90\xd6" +
	"\xbeb\x09KI\xad\xbd\xdf\x0d\xfd\x91i\xcdm\x07\xf3" +
	"5\xaf\xb5}\xde\x0d\x83pW\xd5k\x1d\xf4\xe7\xbd}" +
	"\xc1\"\x9b3d\xf9\x0eM\x07t\x02\xf6\xa3\x1c\x04\xaa" +
	"\x0fRcu\x81\x8a\x16\xe9\xc8\xd4\xb6\x9b\xf2G\x84\xd7" +
	"\xa8H\xe5P\x01\xb6\xc7\xc7\x81\xea\x82\xe0P\xca5:" +
	"\xd4\x00\xbb\xc1a\xa0Z\x13\x1e\x0b\xd7\x95C\x1d\xb0\x0f" +
	"\xa4\xbc.\xfc\x90p\x83\x0e\x0d\xc0n\xa7\xf2\xa1\xf0#" +
	"\xc2\x0b\xc7\x1d\x16\x00\xfb0\xf7\x02\xd5X\xf8q\xe1\xa6" +
	"\xe6\x88I\xfbh\xaasH\xf8I\xe1E\xcda\x11\xb0" +
	"\x9f\xe0.\xa0zD\xf8S\xc27\x18\x0e7\x00\xf62" +
	"\x1f\x02\xaa'\x85?/|\xa3\xeep#`?\xc3\x0a" +
	"P}Z\xf8i\xe1=\x86\xc3\x1e\xc0^\xe5\x14P}" +
	"Q\xf8\x19\xe1\xbdE\x87\xbd\x80\xbd\x96\xea\x9f\x16~\x96" +
	"\x8a\xe6|\xd8\xa6\x0eE\x1d4[QD\x03\x8a\x06\x98" +
	"4\x9a\x0b\xfe\xa2\xef-\xa0\x7f\xd6ox\xec\x85b/" +
	"\xd8\x1f\xb8\xb9\x87\xd0\x8dk\xd9\x83\x19\xfa\x0b\x99\xd0\xb1" +
	"V;\x08\xfc\xe01\x12\x8a\x04\xfb#\x7f\xc9\xcb\x94K" +
	"Q\xec\xc6\xed(\xebK\xa2\xd8m\xc5\x93\xcd6\xb4 " +
	"\xce\x04:p\xd6o\x80^\xae\xb0\x19\xca,\x002V" +
	"j\x87\xb1L\x97\xb5]%,\x93n8\xdd!lI" +
	"X\x064\x03\xe8\xc6\x9a\xd9jX\x07\x86\xa1,\xcf$" +
	"\xbb\xfb\xc6,\x9f\xd6\xdc(\x94u\xafI\xd5]5f" +
	"\xb1\xb7&\xa4\xefN\x93Z7\xe8\xcc\xb6\xc9\xbau/" +
	"\x94u\x93\xd9_\xf7\xa3x\x9c[Sc\xe3\xec\x173" +
	"\xe3<&\x7f&\xea\xf5q\x96u2\xf9\xe4\xb5\x99\xfb" +
	"\xff\xbcm\xcb\x8f\x00\xbaV\xf4\xabYimO\xb5\x86" +
	"J3n\xcbmDe=\xdb\x00\xabo\x18(\x175" +
	"\x96\x1du\xf9\x07[\x9fh3\x1c\x9a\xd9\xfa\xbfj\x8a" +
	"\xf7\xa1J\xc9\x8b\xda\xf5\xf82\xd1)\xa0\xdc\xab\xb1\xbc" +
	"M1\xf1\x83\xc5\xe6\xb4\x1f\xc5\xf2y\xaf\x03g4r" +
	"\xe0\xd2\xaf*(\xb0\xfb2\xe3\xdf\x0dL\xd4\xebC\x95" +
	"\xf4u\x8c\xd6=\xe0\x15L\xef\xff{\xbe-\x8aI3" +
	"\xa8\x1f\xae\xb4\x83\x00f.\xd9\xeb\xbe\xd1+\xb9\xcf_" +
	"\xa9\xb8\xff\x87\xdf\x81k\xf3\xdb\x89A.9\xc6\x7f%" +
	"\xa7sC\x11\xaem\xa6\xbf\x02\x00\x00\xff\xffp\xa0\xb7" +
	"\xd0"

func init() {
	schemas.Register(schema_e42f87955bd521e9,
		0x8aa0c0b71a33baab,
		0x96524352b99b59d2,
		0x9dd032618f0a61da,
		0xa4f2766999f82f48,
		0xa7b81c0bbc4ab3a8,
		0xb7dbdb4757bf491e,
		0xd43c617d04683d01,
		0xd606313032e1634f,
		0xe4f33c61c382a6a7,
		0xef6591cc288ebded)
}
