// Code generated by capnpc-go. DO NOT EDIT.

package hubapi

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
	fmt "fmt"
)

type ServiceInfo capnp.Struct

// ServiceInfo_TypeID is the unique identifier for the type ServiceInfo.
const ServiceInfo_TypeID = 0x8aa0c0b71a33baab

func NewServiceInfo(s *capnp.Segment) (ServiceInfo, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 40, PointerCount: 6})
	return ServiceInfo(st), err
}

func NewRootServiceInfo(s *capnp.Segment) (ServiceInfo, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 40, PointerCount: 6})
	return ServiceInfo(st), err
}

func ReadRootServiceInfo(msg *capnp.Message) (ServiceInfo, error) {
	root, err := msg.Root()
	return ServiceInfo(root.Struct()), err
}

func (s ServiceInfo) String() string {
	str, _ := text.Marshal(0x8aa0c0b71a33baab, capnp.Struct(s))
	return str
}

func (s ServiceInfo) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ServiceInfo) DecodeFromPtr(p capnp.Ptr) ServiceInfo {
	return ServiceInfo(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ServiceInfo) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ServiceInfo) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ServiceInfo) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ServiceInfo) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ServiceInfo) Cpu() int32 {
	return int32(capnp.Struct(s).Uint32(0))
}

func (s ServiceInfo) SetCpu(v int32) {
	capnp.Struct(s).SetUint32(0, uint32(v))
}

func (s ServiceInfo) ModifiedTime() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ServiceInfo) HasModifiedTime() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ServiceInfo) ModifiedTimeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ServiceInfo) SetModifiedTime(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ServiceInfo) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ServiceInfo) HasName() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ServiceInfo) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ServiceInfo) SetName(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s ServiceInfo) Path() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s ServiceInfo) HasPath() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s ServiceInfo) PathBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s ServiceInfo) SetPath(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s ServiceInfo) Pid() int32 {
	return int32(capnp.Struct(s).Uint32(4))
}

func (s ServiceInfo) SetPid(v int32) {
	capnp.Struct(s).SetUint32(4, uint32(v))
}

func (s ServiceInfo) Rss() int64 {
	return int64(capnp.Struct(s).Uint64(8))
}

func (s ServiceInfo) SetRss(v int64) {
	capnp.Struct(s).SetUint64(8, uint64(v))
}

func (s ServiceInfo) Running() bool {
	return capnp.Struct(s).Bit(128)
}

func (s ServiceInfo) SetRunning(v bool) {
	capnp.Struct(s).SetBit(128, v)
}

func (s ServiceInfo) Size() int64 {
	return int64(capnp.Struct(s).Uint64(24))
}

func (s ServiceInfo) SetSize(v int64) {
	capnp.Struct(s).SetUint64(24, uint64(v))
}

func (s ServiceInfo) Status() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s ServiceInfo) HasStatus() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s ServiceInfo) StatusBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s ServiceInfo) SetStatus(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s ServiceInfo) StartCount() int32 {
	return int32(capnp.Struct(s).Uint32(20))
}

func (s ServiceInfo) SetStartCount(v int32) {
	capnp.Struct(s).SetUint32(20, uint32(v))
}

func (s ServiceInfo) StartTime() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s ServiceInfo) HasStartTime() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s ServiceInfo) StartTimeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s ServiceInfo) SetStartTime(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s ServiceInfo) StopTime() (string, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.Text(), err
}

func (s ServiceInfo) HasStopTime() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s ServiceInfo) StopTimeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.TextBytes(), err
}

func (s ServiceInfo) SetStopTime(v string) error {
	return capnp.Struct(s).SetText(5, v)
}

func (s ServiceInfo) Uptime() int32 {
	return int32(capnp.Struct(s).Uint32(32))
}

func (s ServiceInfo) SetUptime(v int32) {
	capnp.Struct(s).SetUint32(32, uint32(v))
}

// ServiceInfo_List is a list of ServiceInfo.
type ServiceInfo_List = capnp.StructList[ServiceInfo]

// NewServiceInfo creates a new list of ServiceInfo.
func NewServiceInfo_List(s *capnp.Segment, sz int32) (ServiceInfo_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 40, PointerCount: 6}, sz)
	return capnp.StructList[ServiceInfo](l), err
}

// ServiceInfo_Future is a wrapper for a ServiceInfo promised by a client call.
type ServiceInfo_Future struct{ *capnp.Future }

func (f ServiceInfo_Future) Struct() (ServiceInfo, error) {
	p, err := f.Future.Ptr()
	return ServiceInfo(p.Struct()), err
}

type CapLauncher capnp.Client

// CapLauncher_TypeID is the unique identifier for the type CapLauncher.
const CapLauncher_TypeID = 0x96524352b99b59d2

func (c CapLauncher) List(ctx context.Context, params func(CapLauncher_list_Params) error) (CapLauncher_list_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x96524352b99b59d2,
			MethodID:      0,
			InterfaceName: "hubapi/Launcher.capnp:CapLauncher",
			MethodName:    "list",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CapLauncher_list_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CapLauncher_list_Results_Future{Future: ans.Future()}, release
}
func (c CapLauncher) StartService(ctx context.Context, params func(CapLauncher_startService_Params) error) (CapLauncher_startService_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x96524352b99b59d2,
			MethodID:      1,
			InterfaceName: "hubapi/Launcher.capnp:CapLauncher",
			MethodName:    "startService",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CapLauncher_startService_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CapLauncher_startService_Results_Future{Future: ans.Future()}, release
}
func (c CapLauncher) StartAll(ctx context.Context, params func(CapLauncher_startAll_Params) error) (CapLauncher_startAll_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x96524352b99b59d2,
			MethodID:      2,
			InterfaceName: "hubapi/Launcher.capnp:CapLauncher",
			MethodName:    "startAll",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CapLauncher_startAll_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CapLauncher_startAll_Results_Future{Future: ans.Future()}, release
}
func (c CapLauncher) StopService(ctx context.Context, params func(CapLauncher_stopService_Params) error) (CapLauncher_stopService_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x96524352b99b59d2,
			MethodID:      3,
			InterfaceName: "hubapi/Launcher.capnp:CapLauncher",
			MethodName:    "stopService",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CapLauncher_stopService_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CapLauncher_stopService_Results_Future{Future: ans.Future()}, release
}
func (c CapLauncher) StopAll(ctx context.Context, params func(CapLauncher_stopAll_Params) error) (CapLauncher_stopAll_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x96524352b99b59d2,
			MethodID:      4,
			InterfaceName: "hubapi/Launcher.capnp:CapLauncher",
			MethodName:    "stopAll",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CapLauncher_stopAll_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CapLauncher_stopAll_Results_Future{Future: ans.Future()}, release
}
func (c CapLauncher) GetCapability(ctx context.Context, params func(CapHiveOTService_getCapability_Params) error) (CapHiveOTService_getCapability_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xe7182cfc5650a2c2,
			MethodID:      0,
			InterfaceName: "hubapi/Service.capnp:CapHiveOTService",
			MethodName:    "getCapability",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 4}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CapHiveOTService_getCapability_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CapHiveOTService_getCapability_Results_Future{Future: ans.Future()}, release
}
func (c CapLauncher) ListCapabilities(ctx context.Context, params func(CapHiveOTService_listCapabilities_Params) error) (CapHiveOTService_listCapabilities_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xe7182cfc5650a2c2,
			MethodID:      1,
			InterfaceName: "hubapi/Service.capnp:CapHiveOTService",
			MethodName:    "listCapabilities",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CapHiveOTService_listCapabilities_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CapHiveOTService_listCapabilities_Results_Future{Future: ans.Future()}, release
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c CapLauncher) String() string {
	return fmt.Sprintf("%T(%v)", c, capnp.Client(c))
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c CapLauncher) AddRef() CapLauncher {
	return CapLauncher(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c CapLauncher) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c CapLauncher) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c CapLauncher) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (CapLauncher) DecodeFromPtr(p capnp.Ptr) CapLauncher {
	return CapLauncher(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c CapLauncher) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c CapLauncher) IsSame(other CapLauncher) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c CapLauncher) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c CapLauncher) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
} // A CapLauncher_Server is a CapLauncher with a local implementation.
type CapLauncher_Server interface {
	List(context.Context, CapLauncher_list) error

	StartService(context.Context, CapLauncher_startService) error

	StartAll(context.Context, CapLauncher_startAll) error

	StopService(context.Context, CapLauncher_stopService) error

	StopAll(context.Context, CapLauncher_stopAll) error

	GetCapability(context.Context, CapHiveOTService_getCapability) error

	ListCapabilities(context.Context, CapHiveOTService_listCapabilities) error
}

// CapLauncher_NewServer creates a new Server from an implementation of CapLauncher_Server.
func CapLauncher_NewServer(s CapLauncher_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(CapLauncher_Methods(nil, s), s, c)
}

// CapLauncher_ServerToClient creates a new Client from an implementation of CapLauncher_Server.
// The caller is responsible for calling Release on the returned Client.
func CapLauncher_ServerToClient(s CapLauncher_Server) CapLauncher {
	return CapLauncher(capnp.NewClient(CapLauncher_NewServer(s)))
}

// CapLauncher_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func CapLauncher_Methods(methods []server.Method, s CapLauncher_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 7)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x96524352b99b59d2,
			MethodID:      0,
			InterfaceName: "hubapi/Launcher.capnp:CapLauncher",
			MethodName:    "list",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.List(ctx, CapLauncher_list{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x96524352b99b59d2,
			MethodID:      1,
			InterfaceName: "hubapi/Launcher.capnp:CapLauncher",
			MethodName:    "startService",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.StartService(ctx, CapLauncher_startService{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x96524352b99b59d2,
			MethodID:      2,
			InterfaceName: "hubapi/Launcher.capnp:CapLauncher",
			MethodName:    "startAll",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.StartAll(ctx, CapLauncher_startAll{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x96524352b99b59d2,
			MethodID:      3,
			InterfaceName: "hubapi/Launcher.capnp:CapLauncher",
			MethodName:    "stopService",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.StopService(ctx, CapLauncher_stopService{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x96524352b99b59d2,
			MethodID:      4,
			InterfaceName: "hubapi/Launcher.capnp:CapLauncher",
			MethodName:    "stopAll",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.StopAll(ctx, CapLauncher_stopAll{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xe7182cfc5650a2c2,
			MethodID:      0,
			InterfaceName: "hubapi/Service.capnp:CapHiveOTService",
			MethodName:    "getCapability",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.GetCapability(ctx, CapHiveOTService_getCapability{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xe7182cfc5650a2c2,
			MethodID:      1,
			InterfaceName: "hubapi/Service.capnp:CapHiveOTService",
			MethodName:    "listCapabilities",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.ListCapabilities(ctx, CapHiveOTService_listCapabilities{call})
		},
	})

	return methods
}

// CapLauncher_list holds the state for a server call to CapLauncher.list.
// See server.Call for documentation.
type CapLauncher_list struct {
	*server.Call
}

// Args returns the call's arguments.
func (c CapLauncher_list) Args() CapLauncher_list_Params {
	return CapLauncher_list_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c CapLauncher_list) AllocResults() (CapLauncher_list_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_list_Results(r), err
}

// CapLauncher_startService holds the state for a server call to CapLauncher.startService.
// See server.Call for documentation.
type CapLauncher_startService struct {
	*server.Call
}

// Args returns the call's arguments.
func (c CapLauncher_startService) Args() CapLauncher_startService_Params {
	return CapLauncher_startService_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c CapLauncher_startService) AllocResults() (CapLauncher_startService_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_startService_Results(r), err
}

// CapLauncher_startAll holds the state for a server call to CapLauncher.startAll.
// See server.Call for documentation.
type CapLauncher_startAll struct {
	*server.Call
}

// Args returns the call's arguments.
func (c CapLauncher_startAll) Args() CapLauncher_startAll_Params {
	return CapLauncher_startAll_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c CapLauncher_startAll) AllocResults() (CapLauncher_startAll_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CapLauncher_startAll_Results(r), err
}

// CapLauncher_stopService holds the state for a server call to CapLauncher.stopService.
// See server.Call for documentation.
type CapLauncher_stopService struct {
	*server.Call
}

// Args returns the call's arguments.
func (c CapLauncher_stopService) Args() CapLauncher_stopService_Params {
	return CapLauncher_stopService_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c CapLauncher_stopService) AllocResults() (CapLauncher_stopService_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_stopService_Results(r), err
}

// CapLauncher_stopAll holds the state for a server call to CapLauncher.stopAll.
// See server.Call for documentation.
type CapLauncher_stopAll struct {
	*server.Call
}

// Args returns the call's arguments.
func (c CapLauncher_stopAll) Args() CapLauncher_stopAll_Params {
	return CapLauncher_stopAll_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c CapLauncher_stopAll) AllocResults() (CapLauncher_stopAll_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CapLauncher_stopAll_Results(r), err
}

// CapLauncher_List is a list of CapLauncher.
type CapLauncher_List = capnp.CapList[CapLauncher]

// NewCapLauncher creates a new list of CapLauncher.
func NewCapLauncher_List(s *capnp.Segment, sz int32) (CapLauncher_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[CapLauncher](l), err
}

type CapLauncher_list_Params capnp.Struct

// CapLauncher_list_Params_TypeID is the unique identifier for the type CapLauncher_list_Params.
const CapLauncher_list_Params_TypeID = 0xd43c617d04683d01

func NewCapLauncher_list_Params(s *capnp.Segment) (CapLauncher_list_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return CapLauncher_list_Params(st), err
}

func NewRootCapLauncher_list_Params(s *capnp.Segment) (CapLauncher_list_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return CapLauncher_list_Params(st), err
}

func ReadRootCapLauncher_list_Params(msg *capnp.Message) (CapLauncher_list_Params, error) {
	root, err := msg.Root()
	return CapLauncher_list_Params(root.Struct()), err
}

func (s CapLauncher_list_Params) String() string {
	str, _ := text.Marshal(0xd43c617d04683d01, capnp.Struct(s))
	return str
}

func (s CapLauncher_list_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapLauncher_list_Params) DecodeFromPtr(p capnp.Ptr) CapLauncher_list_Params {
	return CapLauncher_list_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapLauncher_list_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapLauncher_list_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapLauncher_list_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapLauncher_list_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapLauncher_list_Params) OnlyRunning() bool {
	return capnp.Struct(s).Bit(0)
}

func (s CapLauncher_list_Params) SetOnlyRunning(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

// CapLauncher_list_Params_List is a list of CapLauncher_list_Params.
type CapLauncher_list_Params_List = capnp.StructList[CapLauncher_list_Params]

// NewCapLauncher_list_Params creates a new list of CapLauncher_list_Params.
func NewCapLauncher_list_Params_List(s *capnp.Segment, sz int32) (CapLauncher_list_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[CapLauncher_list_Params](l), err
}

// CapLauncher_list_Params_Future is a wrapper for a CapLauncher_list_Params promised by a client call.
type CapLauncher_list_Params_Future struct{ *capnp.Future }

func (f CapLauncher_list_Params_Future) Struct() (CapLauncher_list_Params, error) {
	p, err := f.Future.Ptr()
	return CapLauncher_list_Params(p.Struct()), err
}

type CapLauncher_list_Results capnp.Struct

// CapLauncher_list_Results_TypeID is the unique identifier for the type CapLauncher_list_Results.
const CapLauncher_list_Results_TypeID = 0xa7b81c0bbc4ab3a8

func NewCapLauncher_list_Results(s *capnp.Segment) (CapLauncher_list_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_list_Results(st), err
}

func NewRootCapLauncher_list_Results(s *capnp.Segment) (CapLauncher_list_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_list_Results(st), err
}

func ReadRootCapLauncher_list_Results(msg *capnp.Message) (CapLauncher_list_Results, error) {
	root, err := msg.Root()
	return CapLauncher_list_Results(root.Struct()), err
}

func (s CapLauncher_list_Results) String() string {
	str, _ := text.Marshal(0xa7b81c0bbc4ab3a8, capnp.Struct(s))
	return str
}

func (s CapLauncher_list_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapLauncher_list_Results) DecodeFromPtr(p capnp.Ptr) CapLauncher_list_Results {
	return CapLauncher_list_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapLauncher_list_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapLauncher_list_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapLauncher_list_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapLauncher_list_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapLauncher_list_Results) InfoList() (ServiceInfo_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return ServiceInfo_List(p.List()), err
}

func (s CapLauncher_list_Results) HasInfoList() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CapLauncher_list_Results) SetInfoList(v ServiceInfo_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewInfoList sets the infoList field to a newly
// allocated ServiceInfo_List, preferring placement in s's segment.
func (s CapLauncher_list_Results) NewInfoList(n int32) (ServiceInfo_List, error) {
	l, err := NewServiceInfo_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return ServiceInfo_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// CapLauncher_list_Results_List is a list of CapLauncher_list_Results.
type CapLauncher_list_Results_List = capnp.StructList[CapLauncher_list_Results]

// NewCapLauncher_list_Results creates a new list of CapLauncher_list_Results.
func NewCapLauncher_list_Results_List(s *capnp.Segment, sz int32) (CapLauncher_list_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[CapLauncher_list_Results](l), err
}

// CapLauncher_list_Results_Future is a wrapper for a CapLauncher_list_Results promised by a client call.
type CapLauncher_list_Results_Future struct{ *capnp.Future }

func (f CapLauncher_list_Results_Future) Struct() (CapLauncher_list_Results, error) {
	p, err := f.Future.Ptr()
	return CapLauncher_list_Results(p.Struct()), err
}

type CapLauncher_startService_Params capnp.Struct

// CapLauncher_startService_Params_TypeID is the unique identifier for the type CapLauncher_startService_Params.
const CapLauncher_startService_Params_TypeID = 0x9dd032618f0a61da

func NewCapLauncher_startService_Params(s *capnp.Segment) (CapLauncher_startService_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_startService_Params(st), err
}

func NewRootCapLauncher_startService_Params(s *capnp.Segment) (CapLauncher_startService_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_startService_Params(st), err
}

func ReadRootCapLauncher_startService_Params(msg *capnp.Message) (CapLauncher_startService_Params, error) {
	root, err := msg.Root()
	return CapLauncher_startService_Params(root.Struct()), err
}

func (s CapLauncher_startService_Params) String() string {
	str, _ := text.Marshal(0x9dd032618f0a61da, capnp.Struct(s))
	return str
}

func (s CapLauncher_startService_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapLauncher_startService_Params) DecodeFromPtr(p capnp.Ptr) CapLauncher_startService_Params {
	return CapLauncher_startService_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapLauncher_startService_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapLauncher_startService_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapLauncher_startService_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapLauncher_startService_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapLauncher_startService_Params) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CapLauncher_startService_Params) HasName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CapLauncher_startService_Params) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CapLauncher_startService_Params) SetName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// CapLauncher_startService_Params_List is a list of CapLauncher_startService_Params.
type CapLauncher_startService_Params_List = capnp.StructList[CapLauncher_startService_Params]

// NewCapLauncher_startService_Params creates a new list of CapLauncher_startService_Params.
func NewCapLauncher_startService_Params_List(s *capnp.Segment, sz int32) (CapLauncher_startService_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[CapLauncher_startService_Params](l), err
}

// CapLauncher_startService_Params_Future is a wrapper for a CapLauncher_startService_Params promised by a client call.
type CapLauncher_startService_Params_Future struct{ *capnp.Future }

func (f CapLauncher_startService_Params_Future) Struct() (CapLauncher_startService_Params, error) {
	p, err := f.Future.Ptr()
	return CapLauncher_startService_Params(p.Struct()), err
}

type CapLauncher_startService_Results capnp.Struct

// CapLauncher_startService_Results_TypeID is the unique identifier for the type CapLauncher_startService_Results.
const CapLauncher_startService_Results_TypeID = 0xef6591cc288ebded

func NewCapLauncher_startService_Results(s *capnp.Segment) (CapLauncher_startService_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_startService_Results(st), err
}

func NewRootCapLauncher_startService_Results(s *capnp.Segment) (CapLauncher_startService_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_startService_Results(st), err
}

func ReadRootCapLauncher_startService_Results(msg *capnp.Message) (CapLauncher_startService_Results, error) {
	root, err := msg.Root()
	return CapLauncher_startService_Results(root.Struct()), err
}

func (s CapLauncher_startService_Results) String() string {
	str, _ := text.Marshal(0xef6591cc288ebded, capnp.Struct(s))
	return str
}

func (s CapLauncher_startService_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapLauncher_startService_Results) DecodeFromPtr(p capnp.Ptr) CapLauncher_startService_Results {
	return CapLauncher_startService_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapLauncher_startService_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapLauncher_startService_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapLauncher_startService_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapLauncher_startService_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapLauncher_startService_Results) Info() (ServiceInfo, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return ServiceInfo(p.Struct()), err
}

func (s CapLauncher_startService_Results) HasInfo() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CapLauncher_startService_Results) SetInfo(v ServiceInfo) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewInfo sets the info field to a newly
// allocated ServiceInfo struct, preferring placement in s's segment.
func (s CapLauncher_startService_Results) NewInfo() (ServiceInfo, error) {
	ss, err := NewServiceInfo(capnp.Struct(s).Segment())
	if err != nil {
		return ServiceInfo{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// CapLauncher_startService_Results_List is a list of CapLauncher_startService_Results.
type CapLauncher_startService_Results_List = capnp.StructList[CapLauncher_startService_Results]

// NewCapLauncher_startService_Results creates a new list of CapLauncher_startService_Results.
func NewCapLauncher_startService_Results_List(s *capnp.Segment, sz int32) (CapLauncher_startService_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[CapLauncher_startService_Results](l), err
}

// CapLauncher_startService_Results_Future is a wrapper for a CapLauncher_startService_Results promised by a client call.
type CapLauncher_startService_Results_Future struct{ *capnp.Future }

func (f CapLauncher_startService_Results_Future) Struct() (CapLauncher_startService_Results, error) {
	p, err := f.Future.Ptr()
	return CapLauncher_startService_Results(p.Struct()), err
}
func (p CapLauncher_startService_Results_Future) Info() ServiceInfo_Future {
	return ServiceInfo_Future{Future: p.Future.Field(0, nil)}
}

type CapLauncher_startAll_Params capnp.Struct

// CapLauncher_startAll_Params_TypeID is the unique identifier for the type CapLauncher_startAll_Params.
const CapLauncher_startAll_Params_TypeID = 0xa4f2766999f82f48

func NewCapLauncher_startAll_Params(s *capnp.Segment) (CapLauncher_startAll_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CapLauncher_startAll_Params(st), err
}

func NewRootCapLauncher_startAll_Params(s *capnp.Segment) (CapLauncher_startAll_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CapLauncher_startAll_Params(st), err
}

func ReadRootCapLauncher_startAll_Params(msg *capnp.Message) (CapLauncher_startAll_Params, error) {
	root, err := msg.Root()
	return CapLauncher_startAll_Params(root.Struct()), err
}

func (s CapLauncher_startAll_Params) String() string {
	str, _ := text.Marshal(0xa4f2766999f82f48, capnp.Struct(s))
	return str
}

func (s CapLauncher_startAll_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapLauncher_startAll_Params) DecodeFromPtr(p capnp.Ptr) CapLauncher_startAll_Params {
	return CapLauncher_startAll_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapLauncher_startAll_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapLauncher_startAll_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapLauncher_startAll_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapLauncher_startAll_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CapLauncher_startAll_Params_List is a list of CapLauncher_startAll_Params.
type CapLauncher_startAll_Params_List = capnp.StructList[CapLauncher_startAll_Params]

// NewCapLauncher_startAll_Params creates a new list of CapLauncher_startAll_Params.
func NewCapLauncher_startAll_Params_List(s *capnp.Segment, sz int32) (CapLauncher_startAll_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CapLauncher_startAll_Params](l), err
}

// CapLauncher_startAll_Params_Future is a wrapper for a CapLauncher_startAll_Params promised by a client call.
type CapLauncher_startAll_Params_Future struct{ *capnp.Future }

func (f CapLauncher_startAll_Params_Future) Struct() (CapLauncher_startAll_Params, error) {
	p, err := f.Future.Ptr()
	return CapLauncher_startAll_Params(p.Struct()), err
}

type CapLauncher_startAll_Results capnp.Struct

// CapLauncher_startAll_Results_TypeID is the unique identifier for the type CapLauncher_startAll_Results.
const CapLauncher_startAll_Results_TypeID = 0xd606313032e1634f

func NewCapLauncher_startAll_Results(s *capnp.Segment) (CapLauncher_startAll_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CapLauncher_startAll_Results(st), err
}

func NewRootCapLauncher_startAll_Results(s *capnp.Segment) (CapLauncher_startAll_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CapLauncher_startAll_Results(st), err
}

func ReadRootCapLauncher_startAll_Results(msg *capnp.Message) (CapLauncher_startAll_Results, error) {
	root, err := msg.Root()
	return CapLauncher_startAll_Results(root.Struct()), err
}

func (s CapLauncher_startAll_Results) String() string {
	str, _ := text.Marshal(0xd606313032e1634f, capnp.Struct(s))
	return str
}

func (s CapLauncher_startAll_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapLauncher_startAll_Results) DecodeFromPtr(p capnp.Ptr) CapLauncher_startAll_Results {
	return CapLauncher_startAll_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapLauncher_startAll_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapLauncher_startAll_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapLauncher_startAll_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapLauncher_startAll_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CapLauncher_startAll_Results_List is a list of CapLauncher_startAll_Results.
type CapLauncher_startAll_Results_List = capnp.StructList[CapLauncher_startAll_Results]

// NewCapLauncher_startAll_Results creates a new list of CapLauncher_startAll_Results.
func NewCapLauncher_startAll_Results_List(s *capnp.Segment, sz int32) (CapLauncher_startAll_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CapLauncher_startAll_Results](l), err
}

// CapLauncher_startAll_Results_Future is a wrapper for a CapLauncher_startAll_Results promised by a client call.
type CapLauncher_startAll_Results_Future struct{ *capnp.Future }

func (f CapLauncher_startAll_Results_Future) Struct() (CapLauncher_startAll_Results, error) {
	p, err := f.Future.Ptr()
	return CapLauncher_startAll_Results(p.Struct()), err
}

type CapLauncher_stopService_Params capnp.Struct

// CapLauncher_stopService_Params_TypeID is the unique identifier for the type CapLauncher_stopService_Params.
const CapLauncher_stopService_Params_TypeID = 0xe4f33c61c382a6a7

func NewCapLauncher_stopService_Params(s *capnp.Segment) (CapLauncher_stopService_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_stopService_Params(st), err
}

func NewRootCapLauncher_stopService_Params(s *capnp.Segment) (CapLauncher_stopService_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_stopService_Params(st), err
}

func ReadRootCapLauncher_stopService_Params(msg *capnp.Message) (CapLauncher_stopService_Params, error) {
	root, err := msg.Root()
	return CapLauncher_stopService_Params(root.Struct()), err
}

func (s CapLauncher_stopService_Params) String() string {
	str, _ := text.Marshal(0xe4f33c61c382a6a7, capnp.Struct(s))
	return str
}

func (s CapLauncher_stopService_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapLauncher_stopService_Params) DecodeFromPtr(p capnp.Ptr) CapLauncher_stopService_Params {
	return CapLauncher_stopService_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapLauncher_stopService_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapLauncher_stopService_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapLauncher_stopService_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapLauncher_stopService_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapLauncher_stopService_Params) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CapLauncher_stopService_Params) HasName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CapLauncher_stopService_Params) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CapLauncher_stopService_Params) SetName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// CapLauncher_stopService_Params_List is a list of CapLauncher_stopService_Params.
type CapLauncher_stopService_Params_List = capnp.StructList[CapLauncher_stopService_Params]

// NewCapLauncher_stopService_Params creates a new list of CapLauncher_stopService_Params.
func NewCapLauncher_stopService_Params_List(s *capnp.Segment, sz int32) (CapLauncher_stopService_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[CapLauncher_stopService_Params](l), err
}

// CapLauncher_stopService_Params_Future is a wrapper for a CapLauncher_stopService_Params promised by a client call.
type CapLauncher_stopService_Params_Future struct{ *capnp.Future }

func (f CapLauncher_stopService_Params_Future) Struct() (CapLauncher_stopService_Params, error) {
	p, err := f.Future.Ptr()
	return CapLauncher_stopService_Params(p.Struct()), err
}

type CapLauncher_stopService_Results capnp.Struct

// CapLauncher_stopService_Results_TypeID is the unique identifier for the type CapLauncher_stopService_Results.
const CapLauncher_stopService_Results_TypeID = 0xb7dbdb4757bf491e

func NewCapLauncher_stopService_Results(s *capnp.Segment) (CapLauncher_stopService_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_stopService_Results(st), err
}

func NewRootCapLauncher_stopService_Results(s *capnp.Segment) (CapLauncher_stopService_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapLauncher_stopService_Results(st), err
}

func ReadRootCapLauncher_stopService_Results(msg *capnp.Message) (CapLauncher_stopService_Results, error) {
	root, err := msg.Root()
	return CapLauncher_stopService_Results(root.Struct()), err
}

func (s CapLauncher_stopService_Results) String() string {
	str, _ := text.Marshal(0xb7dbdb4757bf491e, capnp.Struct(s))
	return str
}

func (s CapLauncher_stopService_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapLauncher_stopService_Results) DecodeFromPtr(p capnp.Ptr) CapLauncher_stopService_Results {
	return CapLauncher_stopService_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapLauncher_stopService_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapLauncher_stopService_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapLauncher_stopService_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapLauncher_stopService_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapLauncher_stopService_Results) Info() (ServiceInfo, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return ServiceInfo(p.Struct()), err
}

func (s CapLauncher_stopService_Results) HasInfo() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CapLauncher_stopService_Results) SetInfo(v ServiceInfo) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewInfo sets the info field to a newly
// allocated ServiceInfo struct, preferring placement in s's segment.
func (s CapLauncher_stopService_Results) NewInfo() (ServiceInfo, error) {
	ss, err := NewServiceInfo(capnp.Struct(s).Segment())
	if err != nil {
		return ServiceInfo{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// CapLauncher_stopService_Results_List is a list of CapLauncher_stopService_Results.
type CapLauncher_stopService_Results_List = capnp.StructList[CapLauncher_stopService_Results]

// NewCapLauncher_stopService_Results creates a new list of CapLauncher_stopService_Results.
func NewCapLauncher_stopService_Results_List(s *capnp.Segment, sz int32) (CapLauncher_stopService_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[CapLauncher_stopService_Results](l), err
}

// CapLauncher_stopService_Results_Future is a wrapper for a CapLauncher_stopService_Results promised by a client call.
type CapLauncher_stopService_Results_Future struct{ *capnp.Future }

func (f CapLauncher_stopService_Results_Future) Struct() (CapLauncher_stopService_Results, error) {
	p, err := f.Future.Ptr()
	return CapLauncher_stopService_Results(p.Struct()), err
}
func (p CapLauncher_stopService_Results_Future) Info() ServiceInfo_Future {
	return ServiceInfo_Future{Future: p.Future.Field(0, nil)}
}

type CapLauncher_stopAll_Params capnp.Struct

// CapLauncher_stopAll_Params_TypeID is the unique identifier for the type CapLauncher_stopAll_Params.
const CapLauncher_stopAll_Params_TypeID = 0x97fd81fe4e5a7de8

func NewCapLauncher_stopAll_Params(s *capnp.Segment) (CapLauncher_stopAll_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CapLauncher_stopAll_Params(st), err
}

func NewRootCapLauncher_stopAll_Params(s *capnp.Segment) (CapLauncher_stopAll_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CapLauncher_stopAll_Params(st), err
}

func ReadRootCapLauncher_stopAll_Params(msg *capnp.Message) (CapLauncher_stopAll_Params, error) {
	root, err := msg.Root()
	return CapLauncher_stopAll_Params(root.Struct()), err
}

func (s CapLauncher_stopAll_Params) String() string {
	str, _ := text.Marshal(0x97fd81fe4e5a7de8, capnp.Struct(s))
	return str
}

func (s CapLauncher_stopAll_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapLauncher_stopAll_Params) DecodeFromPtr(p capnp.Ptr) CapLauncher_stopAll_Params {
	return CapLauncher_stopAll_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapLauncher_stopAll_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapLauncher_stopAll_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapLauncher_stopAll_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapLauncher_stopAll_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CapLauncher_stopAll_Params_List is a list of CapLauncher_stopAll_Params.
type CapLauncher_stopAll_Params_List = capnp.StructList[CapLauncher_stopAll_Params]

// NewCapLauncher_stopAll_Params creates a new list of CapLauncher_stopAll_Params.
func NewCapLauncher_stopAll_Params_List(s *capnp.Segment, sz int32) (CapLauncher_stopAll_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CapLauncher_stopAll_Params](l), err
}

// CapLauncher_stopAll_Params_Future is a wrapper for a CapLauncher_stopAll_Params promised by a client call.
type CapLauncher_stopAll_Params_Future struct{ *capnp.Future }

func (f CapLauncher_stopAll_Params_Future) Struct() (CapLauncher_stopAll_Params, error) {
	p, err := f.Future.Ptr()
	return CapLauncher_stopAll_Params(p.Struct()), err
}

type CapLauncher_stopAll_Results capnp.Struct

// CapLauncher_stopAll_Results_TypeID is the unique identifier for the type CapLauncher_stopAll_Results.
const CapLauncher_stopAll_Results_TypeID = 0xe272876d68537114

func NewCapLauncher_stopAll_Results(s *capnp.Segment) (CapLauncher_stopAll_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CapLauncher_stopAll_Results(st), err
}

func NewRootCapLauncher_stopAll_Results(s *capnp.Segment) (CapLauncher_stopAll_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CapLauncher_stopAll_Results(st), err
}

func ReadRootCapLauncher_stopAll_Results(msg *capnp.Message) (CapLauncher_stopAll_Results, error) {
	root, err := msg.Root()
	return CapLauncher_stopAll_Results(root.Struct()), err
}

func (s CapLauncher_stopAll_Results) String() string {
	str, _ := text.Marshal(0xe272876d68537114, capnp.Struct(s))
	return str
}

func (s CapLauncher_stopAll_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapLauncher_stopAll_Results) DecodeFromPtr(p capnp.Ptr) CapLauncher_stopAll_Results {
	return CapLauncher_stopAll_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapLauncher_stopAll_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapLauncher_stopAll_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapLauncher_stopAll_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapLauncher_stopAll_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CapLauncher_stopAll_Results_List is a list of CapLauncher_stopAll_Results.
type CapLauncher_stopAll_Results_List = capnp.StructList[CapLauncher_stopAll_Results]

// NewCapLauncher_stopAll_Results creates a new list of CapLauncher_stopAll_Results.
func NewCapLauncher_stopAll_Results_List(s *capnp.Segment, sz int32) (CapLauncher_stopAll_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CapLauncher_stopAll_Results](l), err
}

// CapLauncher_stopAll_Results_Future is a wrapper for a CapLauncher_stopAll_Results promised by a client call.
type CapLauncher_stopAll_Results_Future struct{ *capnp.Future }

func (f CapLauncher_stopAll_Results_Future) Struct() (CapLauncher_stopAll_Results, error) {
	p, err := f.Future.Ptr()
	return CapLauncher_stopAll_Results(p.Struct()), err
}

const schema_e42f87955bd521e9 = "x\xda\xac\x94_h\xddt\x14\xc7\xbf\xe7\x97\xe4&\xfd" +
	"3\xef\xb2\x849E\x1c\x96>\x8c\"\xeb\xba\xfa\xe2\xd8" +
	"h\xb7\"\xb3\xa5\xe8\xcd\xcdP;\x1d\x98\xb6\xa97\xe3" +
	"\xde\xdc4\xc9\x1dkY\xd9&\x1b\xd3\xe1\xbf\x89\xd3\xa9" +
	"\x0c\x86\x0c\xe7\x9f7}\x98-\x8a\xa2O\x03\x1fD\x9c" +
	"\xa0CD\x19h\x1f\xc6@\x11\x14\xd4\xc8I\x9b\xbbL" +
	"W\xd6\x82o7\x9fs\xbe\xe7\xdf\xef\x9c\xbbiN\xf4" +
	"\xcb=\xab\xae\xaa\x10\xd6cJ!yw\xae\xf7\xf6\xf3" +
	"\x9f\x9c9\x0ek-)\xc9\xfc]\x17\x1f=y\xac\xfb" +
	"2\x94\x82\x0a\xf4~'\xad!\xe3\x8a\xc4?\xe7\xa5\xef" +
	"\x05(\xf9r\xe4\xf5\xd9\xf2@\xf9e\xe8k\xa5k\xde" +
	"\xa0\xde\xf9\xc2\x1a2\xfeHU\xbf\x15v\x92qA\xbd" +
	"\x15H~\x9e\xd9\xfd\xc0\xdf\x87\xffz\x05z\x07\x012" +
	"[g\xd5\xe3\x049\xf9\xd6i}\xde\xd9\xfc\xc5\xe9\x05" +
	"\x8bBlz[}\x8f@\xc6\xac\xda\x07J\xee\xef\xfe" +
	"\xfdUo\xdf/gs\xd2o\xd4\x17Y\xfa\xd6\xfbC" +
	"\x1f\xb6\xdd\xf1\xc1\xb9\xbc\xf4\x82:\xcd\xd2\x8b\xa9\xf4\xce" +
	"\xc1\x8f\x1f\xdey\xe9\xd2\xf9\xbcC\x8b\x96\xc6\xbeMc" +
	"\x07\xdaV\x91g\x9c\xad_\xc1\xea\xa0,\xf8\xbdZ\xc8" +
	"\x0e\xf7\xa5\x0e\x0f\x8e\xfd\xb0ySO\xe1\xeb\\rO" +
	"{\x8d\x93\x9b\x93v\xa5v,\xfc1g\x19\xd1\xd2\xb2" +
	"\xce\xbd\xf9\xe4g\xce\xd6_/\xe7\xb3\x0ej\xefp\xd0" +
	"\x914\xe8\x95\x8f\x9e\xdb\xf0\xf9\x09\xf7j\xdeaJ\x9b" +
	"c\x87\xa7\xb5>L'\x95\xc6\xa8\x13x\xdd\xc3\x92\xd3" +
	"\xf0\xc7*n\xb8q\xcc\x09\xfc`\x8b\xed\x86\xfb\xbc1" +
	"w\xd0\x9f\xa0z\x89\xc8\xbaG\x92\x01\x99\x00c\x0fu" +
	"\x00\xf6#$\x91=N\x82\x88Ln\xc7ph/`" +
	"?\xce\xb8J\x82tA&\x09\xc0\xf0\xa8\x0b\xb0\xc7\x99" +
	"\x07\xcc%a\x92\x04\x18\xb5\x94W\x98\xc7\xcce2I" +
	"\x06\x8c\xc94|\x95\xf9~\xe6\x0a\x99\xa4\x00F#\xe5" +
	"\x01\xf3\x03\xcc\x0b\x87L*\x00\xc6\x14\xed\x00\xec\x98\xf9" +
	"!\xe6\xaadr\x93\xc6L\x1a\x7f?\xf3#\xcc5\xc9" +
	"$\x0d0\x0e\xd3\x16\xc0>\xc0\xfc)\xe6-\x8aI-" +
	"\x80q\x94v\x03\xf6\x11\xe6/0o\x95Mj\x05\x8c" +
	"g\xa9\x0c\xd8\xcf0?\xc5\xbcM1\xa9\x0d0N\xd2" +
	"\x10`\xbf\xc4\xfc\x0c\xf3v\xcd\xa4v\xc08\x9d\xc6?" +
	"\xc5\xfc,\x09R\xc7\x82\x06\xc9\x10$\x83\x92Z}\xdc" +
	"\x9b\xf0\xdcq\x14wy5\x97\xda!\xa8\x1dT\xf4\x9d" +
	"\xdcG\xe0\xc4\x95\xecC\x0d\xbc\xf1L\xac\x86QD\x0a" +
	"\x04)\xa0\x83a\xc3\xf7=\xff\x09\"\x08\"P1\xf2" +
	"\xa6\xdd\xcc\xd8\x17\xc5N\xdc\x88\xb2\x18I\x14;a<" +
	"Po@\xf2\xe3f%)\xdc\xe5\xd5@n\xce\xb1\x1e" +
	"p]\x002\xd6\xd7\x08b\xae4\x93-\xb1,\x03N" +
	"0\xbc@(\xe4e1%\x05h.<e\xb7\xa3\x9f" +
	"\xe8\x82\xd0\x8f\xaaD\xcdK\xa4l?\xf5\xa9\xbd\x10\xfa" +
	"\xa4J\xa2y\x84\x94\x1d\x84\xee\x0eA\xe8{T\x92\x9a" +
	"\xfbN\xd9\xb9\xe9\xd6(\x84>\xa8\x92\xdc\xbc{\xca\xce" +
	"E\xdf\xb6\x03B\xefQ\x8bU/\x8a\xfb\x17\x9b\xb6\xdd" +
	"\x10E^\xed\x0cl\xafV\x01\xf4/\xf4\xcfk\x0f5" +
	"\xb5\x1e\xe4\xef\xed\xd5j?Y2Q\xf2\xe9\x1b\xa5\x87" +
	"\xfe\xbc{\xddO\x00\x9acP\x96\x1aC\xb8qQ\xdc" +
	"YrB\xa7\x16-W\xb3P\x1fW\xd7YZ\x9f*" +
	"-9;<}U\x17`i\x12Y\xa6\xb8~g\x96" +
	"\x1d\xbbY\x10EM\x8d\xbc\xb4\x86\xc7\xd6Y\xees\xa3" +
	"F5\xbe\xae\x90!\xc0j\x97\xc8\xda (\xf1\xfc\x89" +
	"\xfa\xb0\x17\xc5\xbc5\xb7\x80J\x12\xd1\xeak\x7f\xf0 " +
	"\x86\xcb\x1dX\xd6{\xd9]\xff\x9f\x9c\xf9\xe69\xe7\xbf" +
	"\xb2\xac\xcee\xb9YK7\x18\xed\xe8bG\xeb\x04%" +
	"u\xbf:Un\xf8>\xd4\xdc\x89\xadh\xc6e\x1e\x99" +
	"\x14G+Y\x94T\x13S\xb4\xd2Y\x95\x9c\xe2\xff\xbe" +
	"'\xcdw\xb8\xc1\xdb\xdf\xfc\x1d\xfe\x09\x00\x00\xff\xff\xe1" +
	"\x15\x15\xcc"

func init() {
	schemas.Register(schema_e42f87955bd521e9,
		0x8aa0c0b71a33baab,
		0x96524352b99b59d2,
		0x97fd81fe4e5a7de8,
		0x9dd032618f0a61da,
		0xa4f2766999f82f48,
		0xa7b81c0bbc4ab3a8,
		0xb7dbdb4757bf491e,
		0xd43c617d04683d01,
		0xd606313032e1634f,
		0xe272876d68537114,
		0xe4f33c61c382a6a7,
		0xef6591cc288ebded)
}
