// Code generated by capnpc-go. DO NOT EDIT.

package hubapi

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
	fmt "fmt"
)

const ClientType = uint64(0xe1385e5b215ca71f)

// Constants defined in Resolver.capnp.
const (
	ResolverServiceName       = "resolver"
	DefaultResolverAddress    = "/tmp/hiveot-resolver.socket"
	ClientTypeUnauthenticated = "noauth"
	ClientTypeAdmin           = "admin"
	ClientTypeIotDevice       = "iotdevice"
	ClientTypeUser            = "user"
	ClientTypeService         = "service"
)

type CapabilityInfo capnp.Struct

// CapabilityInfo_TypeID is the unique identifier for the type CapabilityInfo.
const CapabilityInfo_TypeID = 0xae50171d46b6aaf1

func NewCapabilityInfo(s *capnp.Segment) (CapabilityInfo, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 7})
	return CapabilityInfo(st), err
}

func NewRootCapabilityInfo(s *capnp.Segment) (CapabilityInfo, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 7})
	return CapabilityInfo(st), err
}

func ReadRootCapabilityInfo(msg *capnp.Message) (CapabilityInfo, error) {
	root, err := msg.Root()
	return CapabilityInfo(root.Struct()), err
}

func (s CapabilityInfo) String() string {
	str, _ := text.Marshal(0xae50171d46b6aaf1, capnp.Struct(s))
	return str
}

func (s CapabilityInfo) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapabilityInfo) DecodeFromPtr(p capnp.Ptr) CapabilityInfo {
	return CapabilityInfo(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapabilityInfo) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapabilityInfo) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapabilityInfo) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapabilityInfo) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapabilityInfo) InterfaceID() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s CapabilityInfo) SetInterfaceID(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s CapabilityInfo) MethodID() uint16 {
	return capnp.Struct(s).Uint16(8)
}

func (s CapabilityInfo) SetMethodID(v uint16) {
	capnp.Struct(s).SetUint16(8, v)
}

func (s CapabilityInfo) InterfaceName() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CapabilityInfo) HasInterfaceName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CapabilityInfo) InterfaceNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CapabilityInfo) SetInterfaceName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s CapabilityInfo) MethodName() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s CapabilityInfo) HasMethodName() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s CapabilityInfo) MethodNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s CapabilityInfo) SetMethodName(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s CapabilityInfo) ClientTypes() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return capnp.TextList(p.List()), err
}

func (s CapabilityInfo) HasClientTypes() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s CapabilityInfo) SetClientTypes(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(2, v.ToPtr())
}

// NewClientTypes sets the clientTypes field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s CapabilityInfo) NewClientTypes(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(2, l.ToPtr())
	return l, err
}
func (s CapabilityInfo) Protocol() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s CapabilityInfo) HasProtocol() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s CapabilityInfo) ProtocolBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s CapabilityInfo) SetProtocol(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s CapabilityInfo) ServiceID() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s CapabilityInfo) HasServiceID() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s CapabilityInfo) ServiceIDBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s CapabilityInfo) SetServiceID(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s CapabilityInfo) Network() (string, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.Text(), err
}

func (s CapabilityInfo) HasNetwork() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s CapabilityInfo) NetworkBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.TextBytes(), err
}

func (s CapabilityInfo) SetNetwork(v string) error {
	return capnp.Struct(s).SetText(5, v)
}

func (s CapabilityInfo) Address() (string, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.Text(), err
}

func (s CapabilityInfo) HasAddress() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s CapabilityInfo) AddressBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.TextBytes(), err
}

func (s CapabilityInfo) SetAddress(v string) error {
	return capnp.Struct(s).SetText(6, v)
}

// CapabilityInfo_List is a list of CapabilityInfo.
type CapabilityInfo_List = capnp.StructList[CapabilityInfo]

// NewCapabilityInfo creates a new list of CapabilityInfo.
func NewCapabilityInfo_List(s *capnp.Segment, sz int32) (CapabilityInfo_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 7}, sz)
	return capnp.StructList[CapabilityInfo](l), err
}

// CapabilityInfo_Future is a wrapper for a CapabilityInfo promised by a client call.
type CapabilityInfo_Future struct{ *capnp.Future }

func (f CapabilityInfo_Future) Struct() (CapabilityInfo, error) {
	p, err := f.Future.Ptr()
	return CapabilityInfo(p.Struct()), err
}

type CapResolverService capnp.Client

// CapResolverService_TypeID is the unique identifier for the type CapResolverService.
const CapResolverService_TypeID = 0xab76eb2c88343a05

func (c CapResolverService) ListCapabilities(ctx context.Context, params func(CapProvider_listCapabilities_Params) error) (CapProvider_listCapabilities_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xacf14758b95cf892,
			MethodID:      0,
			InterfaceName: "hubapi/Resolver.capnp:CapProvider",
			MethodName:    "listCapabilities",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CapProvider_listCapabilities_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CapProvider_listCapabilities_Results_Future{Future: ans.Future()}, release
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c CapResolverService) String() string {
	return fmt.Sprintf("%T(%v)", c, capnp.Client(c))
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c CapResolverService) AddRef() CapResolverService {
	return CapResolverService(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c CapResolverService) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c CapResolverService) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c CapResolverService) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (CapResolverService) DecodeFromPtr(p capnp.Ptr) CapResolverService {
	return CapResolverService(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c CapResolverService) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c CapResolverService) IsSame(other CapResolverService) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c CapResolverService) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c CapResolverService) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
} // A CapResolverService_Server is a CapResolverService with a local implementation.
type CapResolverService_Server interface {
	ListCapabilities(context.Context, CapProvider_listCapabilities) error
}

// CapResolverService_NewServer creates a new Server from an implementation of CapResolverService_Server.
func CapResolverService_NewServer(s CapResolverService_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(CapResolverService_Methods(nil, s), s, c)
}

// CapResolverService_ServerToClient creates a new Client from an implementation of CapResolverService_Server.
// The caller is responsible for calling Release on the returned Client.
func CapResolverService_ServerToClient(s CapResolverService_Server) CapResolverService {
	return CapResolverService(capnp.NewClient(CapResolverService_NewServer(s)))
}

// CapResolverService_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func CapResolverService_Methods(methods []server.Method, s CapResolverService_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 1)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xacf14758b95cf892,
			MethodID:      0,
			InterfaceName: "hubapi/Resolver.capnp:CapProvider",
			MethodName:    "listCapabilities",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.ListCapabilities(ctx, CapProvider_listCapabilities{call})
		},
	})

	return methods
}

// CapResolverService_List is a list of CapResolverService.
type CapResolverService_List = capnp.CapList[CapResolverService]

// NewCapResolverService creates a new list of CapResolverService.
func NewCapResolverService_List(s *capnp.Segment, sz int32) (CapResolverService_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[CapResolverService](l), err
}

type CapProvider capnp.Client

// CapProvider_TypeID is the unique identifier for the type CapProvider.
const CapProvider_TypeID = 0xacf14758b95cf892

func (c CapProvider) ListCapabilities(ctx context.Context, params func(CapProvider_listCapabilities_Params) error) (CapProvider_listCapabilities_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xacf14758b95cf892,
			MethodID:      0,
			InterfaceName: "hubapi/Resolver.capnp:CapProvider",
			MethodName:    "listCapabilities",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CapProvider_listCapabilities_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CapProvider_listCapabilities_Results_Future{Future: ans.Future()}, release
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c CapProvider) String() string {
	return fmt.Sprintf("%T(%v)", c, capnp.Client(c))
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c CapProvider) AddRef() CapProvider {
	return CapProvider(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c CapProvider) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c CapProvider) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c CapProvider) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (CapProvider) DecodeFromPtr(p capnp.Ptr) CapProvider {
	return CapProvider(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c CapProvider) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c CapProvider) IsSame(other CapProvider) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c CapProvider) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c CapProvider) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
} // A CapProvider_Server is a CapProvider with a local implementation.
type CapProvider_Server interface {
	ListCapabilities(context.Context, CapProvider_listCapabilities) error
}

// CapProvider_NewServer creates a new Server from an implementation of CapProvider_Server.
func CapProvider_NewServer(s CapProvider_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(CapProvider_Methods(nil, s), s, c)
}

// CapProvider_ServerToClient creates a new Client from an implementation of CapProvider_Server.
// The caller is responsible for calling Release on the returned Client.
func CapProvider_ServerToClient(s CapProvider_Server) CapProvider {
	return CapProvider(capnp.NewClient(CapProvider_NewServer(s)))
}

// CapProvider_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func CapProvider_Methods(methods []server.Method, s CapProvider_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 1)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xacf14758b95cf892,
			MethodID:      0,
			InterfaceName: "hubapi/Resolver.capnp:CapProvider",
			MethodName:    "listCapabilities",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.ListCapabilities(ctx, CapProvider_listCapabilities{call})
		},
	})

	return methods
}

// CapProvider_listCapabilities holds the state for a server call to CapProvider.listCapabilities.
// See server.Call for documentation.
type CapProvider_listCapabilities struct {
	*server.Call
}

// Args returns the call's arguments.
func (c CapProvider_listCapabilities) Args() CapProvider_listCapabilities_Params {
	return CapProvider_listCapabilities_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c CapProvider_listCapabilities) AllocResults() (CapProvider_listCapabilities_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapProvider_listCapabilities_Results(r), err
}

// CapProvider_List is a list of CapProvider.
type CapProvider_List = capnp.CapList[CapProvider]

// NewCapProvider creates a new list of CapProvider.
func NewCapProvider_List(s *capnp.Segment, sz int32) (CapProvider_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[CapProvider](l), err
}

type CapProvider_listCapabilities_Params capnp.Struct

// CapProvider_listCapabilities_Params_TypeID is the unique identifier for the type CapProvider_listCapabilities_Params.
const CapProvider_listCapabilities_Params_TypeID = 0xbb0d5b68acfa1d84

func NewCapProvider_listCapabilities_Params(s *capnp.Segment) (CapProvider_listCapabilities_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapProvider_listCapabilities_Params(st), err
}

func NewRootCapProvider_listCapabilities_Params(s *capnp.Segment) (CapProvider_listCapabilities_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapProvider_listCapabilities_Params(st), err
}

func ReadRootCapProvider_listCapabilities_Params(msg *capnp.Message) (CapProvider_listCapabilities_Params, error) {
	root, err := msg.Root()
	return CapProvider_listCapabilities_Params(root.Struct()), err
}

func (s CapProvider_listCapabilities_Params) String() string {
	str, _ := text.Marshal(0xbb0d5b68acfa1d84, capnp.Struct(s))
	return str
}

func (s CapProvider_listCapabilities_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapProvider_listCapabilities_Params) DecodeFromPtr(p capnp.Ptr) CapProvider_listCapabilities_Params {
	return CapProvider_listCapabilities_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapProvider_listCapabilities_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapProvider_listCapabilities_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapProvider_listCapabilities_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapProvider_listCapabilities_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapProvider_listCapabilities_Params) ClientType() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CapProvider_listCapabilities_Params) HasClientType() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CapProvider_listCapabilities_Params) ClientTypeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CapProvider_listCapabilities_Params) SetClientType(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// CapProvider_listCapabilities_Params_List is a list of CapProvider_listCapabilities_Params.
type CapProvider_listCapabilities_Params_List = capnp.StructList[CapProvider_listCapabilities_Params]

// NewCapProvider_listCapabilities_Params creates a new list of CapProvider_listCapabilities_Params.
func NewCapProvider_listCapabilities_Params_List(s *capnp.Segment, sz int32) (CapProvider_listCapabilities_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[CapProvider_listCapabilities_Params](l), err
}

// CapProvider_listCapabilities_Params_Future is a wrapper for a CapProvider_listCapabilities_Params promised by a client call.
type CapProvider_listCapabilities_Params_Future struct{ *capnp.Future }

func (f CapProvider_listCapabilities_Params_Future) Struct() (CapProvider_listCapabilities_Params, error) {
	p, err := f.Future.Ptr()
	return CapProvider_listCapabilities_Params(p.Struct()), err
}

type CapProvider_listCapabilities_Results capnp.Struct

// CapProvider_listCapabilities_Results_TypeID is the unique identifier for the type CapProvider_listCapabilities_Results.
const CapProvider_listCapabilities_Results_TypeID = 0xf5cba8f2960769af

func NewCapProvider_listCapabilities_Results(s *capnp.Segment) (CapProvider_listCapabilities_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapProvider_listCapabilities_Results(st), err
}

func NewRootCapProvider_listCapabilities_Results(s *capnp.Segment) (CapProvider_listCapabilities_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapProvider_listCapabilities_Results(st), err
}

func ReadRootCapProvider_listCapabilities_Results(msg *capnp.Message) (CapProvider_listCapabilities_Results, error) {
	root, err := msg.Root()
	return CapProvider_listCapabilities_Results(root.Struct()), err
}

func (s CapProvider_listCapabilities_Results) String() string {
	str, _ := text.Marshal(0xf5cba8f2960769af, capnp.Struct(s))
	return str
}

func (s CapProvider_listCapabilities_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapProvider_listCapabilities_Results) DecodeFromPtr(p capnp.Ptr) CapProvider_listCapabilities_Results {
	return CapProvider_listCapabilities_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapProvider_listCapabilities_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapProvider_listCapabilities_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapProvider_listCapabilities_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapProvider_listCapabilities_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapProvider_listCapabilities_Results) InfoList() (CapabilityInfo_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return CapabilityInfo_List(p.List()), err
}

func (s CapProvider_listCapabilities_Results) HasInfoList() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CapProvider_listCapabilities_Results) SetInfoList(v CapabilityInfo_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewInfoList sets the infoList field to a newly
// allocated CapabilityInfo_List, preferring placement in s's segment.
func (s CapProvider_listCapabilities_Results) NewInfoList(n int32) (CapabilityInfo_List, error) {
	l, err := NewCapabilityInfo_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return CapabilityInfo_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// CapProvider_listCapabilities_Results_List is a list of CapProvider_listCapabilities_Results.
type CapProvider_listCapabilities_Results_List = capnp.StructList[CapProvider_listCapabilities_Results]

// NewCapProvider_listCapabilities_Results creates a new list of CapProvider_listCapabilities_Results.
func NewCapProvider_listCapabilities_Results_List(s *capnp.Segment, sz int32) (CapProvider_listCapabilities_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[CapProvider_listCapabilities_Results](l), err
}

// CapProvider_listCapabilities_Results_Future is a wrapper for a CapProvider_listCapabilities_Results promised by a client call.
type CapProvider_listCapabilities_Results_Future struct{ *capnp.Future }

func (f CapProvider_listCapabilities_Results_Future) Struct() (CapProvider_listCapabilities_Results, error) {
	p, err := f.Future.Ptr()
	return CapProvider_listCapabilities_Results(p.Struct()), err
}

const schema_f02d0b8fc1fe2004 = "x\xda\x9c\x95\xddk\x1cU\x18\xc6\xdf\xe7\x9c9\x99$" +
	"&M\xc6Y\x92z\x11\xd3J\x0a%\xe4;\x0d\xd4\xa0" +
	"&M\xa2e\x83\x96\xdd\x9dF\xa5\xad\xcad\xf7\x84\x8c" +
	"\xdd\xec\xac3\xb3\xab\xb9\xaah/\xa4\xa0b\x11\xff\x05" +
	"E\x83_\x17\xa2xc/ze+*\x96\x8a(R" +
	"?\xc0\xfa\xd9\x94\x06\xaaXG\xcelf\x93u\x89\x11" +
	"\xefv\x9e\xf3\xbc\xbf\xf7|</;\xd4\xc3&\xb5\xe1" +
	"\xd6\xaf\x05\xb1\xf4\x8ch\x08/\x0e\x97\x9a\xef\x1e\x99?" +
	"MF\x87\x16j\xbb\xfe:\xf3\xfcM\xfdW\x880z" +
	"\x81e`^f:\x91\xf5\x1d\xe3\xb0\xae0\x06\xa2\xf0" +
	"\xfb\xc3O\x7fv\x97\xffd\xbd\xff2\xeb\x85\xf9{\xe4" +
	"\xbf\xc682<\xb2\x8b\xf1}\xcf\xf4\xfdT~\x8d\x8c" +
	"\x0e^c_c\xb30\x9b\xb8Nd\x0a\xae\x9b\x82w" +
	"\x12\x85\xf9\xfbw\xb5?2v\xdfJ\x1d|\x8d\x8d@" +
	"\xf9\x882\x9c\xc3j\xa9\xc0O_?\xf6\xde\x83\x07W" +
	"W\xea\xe0\xe07\xc34\"x+?h\xde\xa9~\x85" +
	"\xab\xaf\xbesOWg\xeauJw\x80m\xd8\x85\xae" +
	"\x13\x8d\xee\xe1\xbd0\xc7\x94ot\x98\x87 \x84o\xde" +
	"\xb2\xf3\xdb\x8f\x92\xc6\xdbu{yH<\x0a\xf31\xa1" +
	"\x0e\x9a\x17\x1c\xd6\x13\"\xda\xcc\xc9\xae?V\x16\x8f\xb6" +
	"\xbeO\xc6m \x12P\xa8e\xf1)\x08\xe6\xb3b\x82" +
	"\x10\xdez\xb5y\xf7\xf9\xd4\xca\xc5:\xe0[\"\x03\xf3" +
	"l\x04\xfc@\x01\xcfU\x80\xdd/\x1f\xdb}\xf4\xe1\xfd" +
	"\x97\xe8\x85\x0e\xc1j\x0a\xce\x8af\x98\x17\xa2\x82\x8f\x05" +
	"W\x9b\xf5Ovv\xfd\xda\xf7\xdc\x8fu\xec3b\x0a" +
	"\xe6'\x91\xf5\x9cb\x7f^a\xcf\xbd\xf8\xc0\x8dS\xef" +
	"\xea\xbf\xd5\xf9\xcf\x8b\xa7`^\x8a\xfc_*\xff\x0f\x15" +
	"\xff\x1b\x8e\xfe\xd2\xd5W>\\\xdb|\xb8\xaf\xc4\x17\xea" +
	"p\xabb\x82\xfa\xc3\xc5\xd2\xbc]t\x063\x9a\xf4\xdd" +
	"|Yz\x03Y\xbbX(\x8e{\xeb\x9f\x96\xf4\xcaN" +
	"V\x1e\xb2\x97 S\x00Z\x88\xa1\x85\xc8\xc0l\x18[" +
	"\x88\xa8J\xe1\xb5\x94l\xde\x91\x85\xe0\xf0rQ\xb6\xcd" +
	"\xf9\xd2\xab\x01\xf4\xb6\x95|\xe9m\xd5\x7f\xda.fj" +
	"\xb7@\x94\x02R\\\xa45`#@\xff\xa5w\xf7\x81" +
	"\xdc\x92S\xa8i>\xd2m+m\xab\xdai\xbb\x98\xf2" +
	"\xdc\xb2\x93\x93P\x9bNk\\l\x0a\x0a\xe2K5\x8c" +
	"S\xc4\x8cV=\xcc;~0m\x17m\xcc;y'" +
	"p\xa4O4\x89\x14\xf0/|;\xb2.\xb7%\x0b\x0b" +
	"\xaej\xd1\xc35\"\x0dD\xc6/\xf3D\xe9\x9f9\xd2" +
	"\xd7\x19\x0ch\x09(qm\x96(}\x8d#\x03\x06\xb0" +
	"\x04\x18\x91q\xc3#J\xff\xc9a5\x82\xc1\xe0H\x80" +
	"\xab\xa1\xc4\x11\"K\x03\x87\xd5\xaet\x8d%\xa0\xa9y" +
	"\xc2<\x91\xd5\xa2\xf4\xbdJ\x17<\x01Ad\xee\xc1," +
	"\x91\xd5\xa3\xf4!\xa57h\x094\x10\x99\xfd\xc8\x10Y" +
	"}J\xdf\xaft]$Tz\xcc1L\x11YCJ" +
	"\xbfC\xe9\x8d\x0d\x094\x12\x99\xb7G\xfa>\xa5O\x82" +
	"!t\x0a\x81\xf4\x16\xec,\xe929\x83&bh\"" +
	"\x84K2Xts\xc9\x19\"\x82N\x0c:mrv" +
	"\xab\x9c\xc9\xf5W\x8a\xbd\x87l\xe2\x9b\xc4\xf8YI/" +
	"J\x1f;\x08)^y\xd7\x1d\x84\xb0\xe8\xb9\x81\x9bu" +
	"\xf3\x8a\x1e\x17\xf8\x95\xf8$\x093\xb1v\xa2 \x83\xc7" +
	"]\xefx\xf5\xdb\xce\xe5<\xe9\xfb\xd5\x9a-B\x99\x93" +
	"\x0bv)\x1f\xc4\xc1<\x90\xcb\xb5\xa9\xb2\x9ad}\x13" +
	"\x0e\x06K\xc5\xc1E\xa7\xcc\xa4\x1b\xf4\xc7C2\xe0\xbb" +
	"Y\xfd\xb8\x0c\xaa\xe8\x86\xad\x12\xe7\x0d\xc4i\x8a\xc3\xd4" +
	"\x93\xb2={\x09~Z\xabf\xa4\xf5\x08Q\xba\x85#" +
	"\xbd\x93m\xba\x12^\x94\xdb\x1dac*\x92n0#" +
	"\xcbN\xf6\x1fs\x9d\x09\x1d7\xc8\xa9\x05\x82\xdc~\xb6" +
	"\xa2\xa9T\xd5\xdb7\x8c\xe7\xb8\xa6\xdd\xd4\x89\xf5\xf7\xa9" +
	"\xd6\x8b\xad\xea\xe7\x0av)X\x94\x85\xc0\xc9\xda\x81\xcc" +
	"\xd5r\xc6'\x0a\xaeZ\xfe_\xf7\x9b\x91~)\xcf\x83" +
	"\x9a\x0b\x9e]\xbf\xe0\xbdQ\x94\x17\xdc{\x1d?P\xb1" +
	"ZO\\\xfb\xc6\xbf\x12A\x89\x7f\x07\x00\x00\xff\xff\x9c" +
	"K\x15\x85"

func init() {
	schemas.Register(schema_f02d0b8fc1fe2004,
		0x926232450a7531d7,
		0x9280733ed48354e5,
		0xab76eb2c88343a05,
		0xac4d355f1020566c,
		0xacf14758b95cf892,
		0xae50171d46b6aaf1,
		0xb21149cee31819b0,
		0xbb0d5b68acfa1d84,
		0xd7ac50cd210af21e,
		0xe1385e5b215ca71f,
		0xea8e2cee1d178473,
		0xef07b88afd579455,
		0xf5cba8f2960769af)
}
