// Code generated by capnpc-go. DO NOT EDIT.

package hubapi

import (
	"capnproto.org/go/capnp/v3"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
)

type HiveService capnp.Client

// HiveService_TypeID is the unique identifier for the type HiveService.
const HiveService_TypeID = 0xc1eb6623bba14b45

func (c HiveService) AddRef() HiveService {
	return HiveService(capnp.Client(c).AddRef())
}

func (c HiveService) Release() {
	capnp.Client(c).Release()
}

func (c HiveService) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (HiveService) DecodeFromPtr(p capnp.Ptr) HiveService {
	return HiveService(capnp.Client{}.DecodeFromPtr(p))
}

func (c HiveService) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// A HiveService_Server is a HiveService with a local implementation.
type HiveService_Server interface {
}

// HiveService_NewServer creates a new Server from an implementation of HiveService_Server.
func HiveService_NewServer(s HiveService_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(HiveService_Methods(nil, s), s, c)
}

// HiveService_ServerToClient creates a new Client from an implementation of HiveService_Server.
// The caller is responsible for calling Release on the returned Client.
func HiveService_ServerToClient(s HiveService_Server) HiveService {
	return HiveService(capnp.NewClient(HiveService_NewServer(s)))
}

// HiveService_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func HiveService_Methods(methods []server.Method, s HiveService_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 0)
	}

	return methods
}

// HiveService_List is a list of HiveService.
type HiveService_List = capnp.CapList[HiveService]

// NewHiveService creates a new list of HiveService.
func NewHiveService_List(s *capnp.Segment, sz int32) (HiveService_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[HiveService](l), err
}

const schema_aedf69d9667f51a8 = "x\xda\x12pu`1\xe4\xdd\xcf\xc8\xc0\x14(\xc2\xca" +
	"\xf6\xdf\xd5{\xe1n\xe5\xb4\xd7\x07\x19\x04E\x99\xff\xaf" +
	"\x08\xacO\xbb\x99y\x7f\x1d\x03\x03\xa3\xe1Q.F\xc1" +
	"\xab\xec\x0c\x0c\x82\x17\xd9\x05/\xb23\xe8\xfc\xcf(M" +
	"J,\xc8\xd4\x0ffN-*\xcbLN\xd5KN," +
	"\xc8+\xb0\xf2\xc8,K\x0d\x86\x8800\x0402\x06" +
	"0\xb3\x0602\x02\x02\x00\x00\xff\xffc0\x1f:"

func init() {
	schemas.Register(schema_aedf69d9667f51a8,
		0xc1eb6623bba14b45)
}
