// Code generated by capnpc-go. DO NOT EDIT.

package hubapi

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
	fmt "fmt"
)

const ClientType = uint64(0xa243f969a95afdf3)

// Constants defined in Service.capnp.
const (
	ClientTypeUnauthenticated = "noauth"
	ClientTypeIotDevice       = "iotdevice"
	ClientTypeUser            = "user"
	ClientTypeService         = "service"
)

type CapabilityInfo capnp.Struct

// CapabilityInfo_TypeID is the unique identifier for the type CapabilityInfo.
const CapabilityInfo_TypeID = 0x845bd0aa4f742bca

func NewCapabilityInfo(s *capnp.Segment) (CapabilityInfo, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return CapabilityInfo(st), err
}

func NewRootCapabilityInfo(s *capnp.Segment) (CapabilityInfo, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return CapabilityInfo(st), err
}

func ReadRootCapabilityInfo(msg *capnp.Message) (CapabilityInfo, error) {
	root, err := msg.Root()
	return CapabilityInfo(root.Struct()), err
}

func (s CapabilityInfo) String() string {
	str, _ := text.Marshal(0x845bd0aa4f742bca, capnp.Struct(s))
	return str
}

func (s CapabilityInfo) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapabilityInfo) DecodeFromPtr(p capnp.Ptr) CapabilityInfo {
	return CapabilityInfo(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapabilityInfo) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapabilityInfo) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapabilityInfo) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapabilityInfo) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapabilityInfo) CapabilityName() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s CapabilityInfo) HasCapabilityName() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s CapabilityInfo) CapabilityNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s CapabilityInfo) SetCapabilityName(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s CapabilityInfo) CapabilityArgs() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return capnp.TextList(p.List()), err
}

func (s CapabilityInfo) HasCapabilityArgs() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s CapabilityInfo) SetCapabilityArgs(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(2, v.ToPtr())
}

// NewCapabilityArgs sets the capabilityArgs field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s CapabilityInfo) NewCapabilityArgs(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(2, l.ToPtr())
	return l, err
}
func (s CapabilityInfo) ClientTypes() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return capnp.TextList(p.List()), err
}

func (s CapabilityInfo) HasClientTypes() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s CapabilityInfo) SetClientTypes(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(3, v.ToPtr())
}

// NewClientTypes sets the clientTypes field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s CapabilityInfo) NewClientTypes(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(3, l.ToPtr())
	return l, err
}
func (s CapabilityInfo) ServiceName() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CapabilityInfo) HasServiceName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CapabilityInfo) ServiceNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CapabilityInfo) SetServiceName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// CapabilityInfo_List is a list of CapabilityInfo.
type CapabilityInfo_List = capnp.StructList[CapabilityInfo]

// NewCapabilityInfo creates a new list of CapabilityInfo.
func NewCapabilityInfo_List(s *capnp.Segment, sz int32) (CapabilityInfo_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4}, sz)
	return capnp.StructList[CapabilityInfo](l), err
}

// CapabilityInfo_Future is a wrapper for a CapabilityInfo promised by a client call.
type CapabilityInfo_Future struct{ *capnp.Future }

func (f CapabilityInfo_Future) Struct() (CapabilityInfo, error) {
	p, err := f.Future.Ptr()
	return CapabilityInfo(p.Struct()), err
}

type CapHiveOTService capnp.Client

// CapHiveOTService_TypeID is the unique identifier for the type CapHiveOTService.
const CapHiveOTService_TypeID = 0xe7182cfc5650a2c2

func (c CapHiveOTService) GetCapability(ctx context.Context, params func(CapHiveOTService_getCapability_Params) error) (CapHiveOTService_getCapability_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xe7182cfc5650a2c2,
			MethodID:      0,
			InterfaceName: "hubapi/Service.capnp:CapHiveOTService",
			MethodName:    "getCapability",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 4}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CapHiveOTService_getCapability_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CapHiveOTService_getCapability_Results_Future{Future: ans.Future()}, release
}
func (c CapHiveOTService) ListCapabilities(ctx context.Context, params func(CapHiveOTService_listCapabilities_Params) error) (CapHiveOTService_listCapabilities_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xe7182cfc5650a2c2,
			MethodID:      1,
			InterfaceName: "hubapi/Service.capnp:CapHiveOTService",
			MethodName:    "listCapabilities",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(CapHiveOTService_listCapabilities_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return CapHiveOTService_listCapabilities_Results_Future{Future: ans.Future()}, release
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c CapHiveOTService) String() string {
	return fmt.Sprintf("%T(%v)", c, capnp.Client(c))
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c CapHiveOTService) AddRef() CapHiveOTService {
	return CapHiveOTService(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c CapHiveOTService) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c CapHiveOTService) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c CapHiveOTService) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (CapHiveOTService) DecodeFromPtr(p capnp.Ptr) CapHiveOTService {
	return CapHiveOTService(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c CapHiveOTService) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c CapHiveOTService) IsSame(other CapHiveOTService) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c CapHiveOTService) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c CapHiveOTService) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
} // A CapHiveOTService_Server is a CapHiveOTService with a local implementation.
type CapHiveOTService_Server interface {
	GetCapability(context.Context, CapHiveOTService_getCapability) error

	ListCapabilities(context.Context, CapHiveOTService_listCapabilities) error
}

// CapHiveOTService_NewServer creates a new Server from an implementation of CapHiveOTService_Server.
func CapHiveOTService_NewServer(s CapHiveOTService_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(CapHiveOTService_Methods(nil, s), s, c)
}

// CapHiveOTService_ServerToClient creates a new Client from an implementation of CapHiveOTService_Server.
// The caller is responsible for calling Release on the returned Client.
func CapHiveOTService_ServerToClient(s CapHiveOTService_Server) CapHiveOTService {
	return CapHiveOTService(capnp.NewClient(CapHiveOTService_NewServer(s)))
}

// CapHiveOTService_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func CapHiveOTService_Methods(methods []server.Method, s CapHiveOTService_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xe7182cfc5650a2c2,
			MethodID:      0,
			InterfaceName: "hubapi/Service.capnp:CapHiveOTService",
			MethodName:    "getCapability",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.GetCapability(ctx, CapHiveOTService_getCapability{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xe7182cfc5650a2c2,
			MethodID:      1,
			InterfaceName: "hubapi/Service.capnp:CapHiveOTService",
			MethodName:    "listCapabilities",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.ListCapabilities(ctx, CapHiveOTService_listCapabilities{call})
		},
	})

	return methods
}

// CapHiveOTService_getCapability holds the state for a server call to CapHiveOTService.getCapability.
// See server.Call for documentation.
type CapHiveOTService_getCapability struct {
	*server.Call
}

// Args returns the call's arguments.
func (c CapHiveOTService_getCapability) Args() CapHiveOTService_getCapability_Params {
	return CapHiveOTService_getCapability_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c CapHiveOTService_getCapability) AllocResults() (CapHiveOTService_getCapability_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapHiveOTService_getCapability_Results(r), err
}

// CapHiveOTService_listCapabilities holds the state for a server call to CapHiveOTService.listCapabilities.
// See server.Call for documentation.
type CapHiveOTService_listCapabilities struct {
	*server.Call
}

// Args returns the call's arguments.
func (c CapHiveOTService_listCapabilities) Args() CapHiveOTService_listCapabilities_Params {
	return CapHiveOTService_listCapabilities_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c CapHiveOTService_listCapabilities) AllocResults() (CapHiveOTService_listCapabilities_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapHiveOTService_listCapabilities_Results(r), err
}

// CapHiveOTService_List is a list of CapHiveOTService.
type CapHiveOTService_List = capnp.CapList[CapHiveOTService]

// NewCapHiveOTService creates a new list of CapHiveOTService.
func NewCapHiveOTService_List(s *capnp.Segment, sz int32) (CapHiveOTService_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[CapHiveOTService](l), err
}

type CapHiveOTService_getCapability_Params capnp.Struct

// CapHiveOTService_getCapability_Params_TypeID is the unique identifier for the type CapHiveOTService_getCapability_Params.
const CapHiveOTService_getCapability_Params_TypeID = 0x997ee5f837c3dfef

func NewCapHiveOTService_getCapability_Params(s *capnp.Segment) (CapHiveOTService_getCapability_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return CapHiveOTService_getCapability_Params(st), err
}

func NewRootCapHiveOTService_getCapability_Params(s *capnp.Segment) (CapHiveOTService_getCapability_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return CapHiveOTService_getCapability_Params(st), err
}

func ReadRootCapHiveOTService_getCapability_Params(msg *capnp.Message) (CapHiveOTService_getCapability_Params, error) {
	root, err := msg.Root()
	return CapHiveOTService_getCapability_Params(root.Struct()), err
}

func (s CapHiveOTService_getCapability_Params) String() string {
	str, _ := text.Marshal(0x997ee5f837c3dfef, capnp.Struct(s))
	return str
}

func (s CapHiveOTService_getCapability_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapHiveOTService_getCapability_Params) DecodeFromPtr(p capnp.Ptr) CapHiveOTService_getCapability_Params {
	return CapHiveOTService_getCapability_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapHiveOTService_getCapability_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapHiveOTService_getCapability_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapHiveOTService_getCapability_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapHiveOTService_getCapability_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapHiveOTService_getCapability_Params) ClientID() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CapHiveOTService_getCapability_Params) HasClientID() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CapHiveOTService_getCapability_Params) ClientIDBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CapHiveOTService_getCapability_Params) SetClientID(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s CapHiveOTService_getCapability_Params) ClientType() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s CapHiveOTService_getCapability_Params) HasClientType() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s CapHiveOTService_getCapability_Params) ClientTypeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s CapHiveOTService_getCapability_Params) SetClientType(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s CapHiveOTService_getCapability_Params) CapabilityName() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s CapHiveOTService_getCapability_Params) HasCapabilityName() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s CapHiveOTService_getCapability_Params) CapabilityNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s CapHiveOTService_getCapability_Params) SetCapabilityName(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s CapHiveOTService_getCapability_Params) Args() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return capnp.TextList(p.List()), err
}

func (s CapHiveOTService_getCapability_Params) HasArgs() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s CapHiveOTService_getCapability_Params) SetArgs(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(3, v.ToPtr())
}

// NewArgs sets the args field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s CapHiveOTService_getCapability_Params) NewArgs(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(3, l.ToPtr())
	return l, err
}

// CapHiveOTService_getCapability_Params_List is a list of CapHiveOTService_getCapability_Params.
type CapHiveOTService_getCapability_Params_List = capnp.StructList[CapHiveOTService_getCapability_Params]

// NewCapHiveOTService_getCapability_Params creates a new list of CapHiveOTService_getCapability_Params.
func NewCapHiveOTService_getCapability_Params_List(s *capnp.Segment, sz int32) (CapHiveOTService_getCapability_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4}, sz)
	return capnp.StructList[CapHiveOTService_getCapability_Params](l), err
}

// CapHiveOTService_getCapability_Params_Future is a wrapper for a CapHiveOTService_getCapability_Params promised by a client call.
type CapHiveOTService_getCapability_Params_Future struct{ *capnp.Future }

func (f CapHiveOTService_getCapability_Params_Future) Struct() (CapHiveOTService_getCapability_Params, error) {
	p, err := f.Future.Ptr()
	return CapHiveOTService_getCapability_Params(p.Struct()), err
}

type CapHiveOTService_getCapability_Results capnp.Struct

// CapHiveOTService_getCapability_Results_TypeID is the unique identifier for the type CapHiveOTService_getCapability_Results.
const CapHiveOTService_getCapability_Results_TypeID = 0xd96dc59a976956f3

func NewCapHiveOTService_getCapability_Results(s *capnp.Segment) (CapHiveOTService_getCapability_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapHiveOTService_getCapability_Results(st), err
}

func NewRootCapHiveOTService_getCapability_Results(s *capnp.Segment) (CapHiveOTService_getCapability_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapHiveOTService_getCapability_Results(st), err
}

func ReadRootCapHiveOTService_getCapability_Results(msg *capnp.Message) (CapHiveOTService_getCapability_Results, error) {
	root, err := msg.Root()
	return CapHiveOTService_getCapability_Results(root.Struct()), err
}

func (s CapHiveOTService_getCapability_Results) String() string {
	str, _ := text.Marshal(0xd96dc59a976956f3, capnp.Struct(s))
	return str
}

func (s CapHiveOTService_getCapability_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapHiveOTService_getCapability_Results) DecodeFromPtr(p capnp.Ptr) CapHiveOTService_getCapability_Results {
	return CapHiveOTService_getCapability_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapHiveOTService_getCapability_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapHiveOTService_getCapability_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapHiveOTService_getCapability_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapHiveOTService_getCapability_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapHiveOTService_getCapability_Results) Cap() capnp.Client {
	p, _ := capnp.Struct(s).Ptr(0)
	return p.Interface().Client()
}

func (s CapHiveOTService_getCapability_Results) HasCap() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CapHiveOTService_getCapability_Results) SetCap(c capnp.Client) error {
	if !c.IsValid() {
		return capnp.Struct(s).SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().AddCap(c))
	return capnp.Struct(s).SetPtr(0, in.ToPtr())
}

// CapHiveOTService_getCapability_Results_List is a list of CapHiveOTService_getCapability_Results.
type CapHiveOTService_getCapability_Results_List = capnp.StructList[CapHiveOTService_getCapability_Results]

// NewCapHiveOTService_getCapability_Results creates a new list of CapHiveOTService_getCapability_Results.
func NewCapHiveOTService_getCapability_Results_List(s *capnp.Segment, sz int32) (CapHiveOTService_getCapability_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[CapHiveOTService_getCapability_Results](l), err
}

// CapHiveOTService_getCapability_Results_Future is a wrapper for a CapHiveOTService_getCapability_Results promised by a client call.
type CapHiveOTService_getCapability_Results_Future struct{ *capnp.Future }

func (f CapHiveOTService_getCapability_Results_Future) Struct() (CapHiveOTService_getCapability_Results, error) {
	p, err := f.Future.Ptr()
	return CapHiveOTService_getCapability_Results(p.Struct()), err
}
func (p CapHiveOTService_getCapability_Results_Future) Cap() capnp.Client {
	return p.Future.Field(0, nil).Client()
}

type CapHiveOTService_listCapabilities_Params capnp.Struct

// CapHiveOTService_listCapabilities_Params_TypeID is the unique identifier for the type CapHiveOTService_listCapabilities_Params.
const CapHiveOTService_listCapabilities_Params_TypeID = 0xee77ffeedea2ce26

func NewCapHiveOTService_listCapabilities_Params(s *capnp.Segment) (CapHiveOTService_listCapabilities_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapHiveOTService_listCapabilities_Params(st), err
}

func NewRootCapHiveOTService_listCapabilities_Params(s *capnp.Segment) (CapHiveOTService_listCapabilities_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapHiveOTService_listCapabilities_Params(st), err
}

func ReadRootCapHiveOTService_listCapabilities_Params(msg *capnp.Message) (CapHiveOTService_listCapabilities_Params, error) {
	root, err := msg.Root()
	return CapHiveOTService_listCapabilities_Params(root.Struct()), err
}

func (s CapHiveOTService_listCapabilities_Params) String() string {
	str, _ := text.Marshal(0xee77ffeedea2ce26, capnp.Struct(s))
	return str
}

func (s CapHiveOTService_listCapabilities_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapHiveOTService_listCapabilities_Params) DecodeFromPtr(p capnp.Ptr) CapHiveOTService_listCapabilities_Params {
	return CapHiveOTService_listCapabilities_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapHiveOTService_listCapabilities_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapHiveOTService_listCapabilities_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapHiveOTService_listCapabilities_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapHiveOTService_listCapabilities_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapHiveOTService_listCapabilities_Params) ClientType() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CapHiveOTService_listCapabilities_Params) HasClientType() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CapHiveOTService_listCapabilities_Params) ClientTypeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CapHiveOTService_listCapabilities_Params) SetClientType(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// CapHiveOTService_listCapabilities_Params_List is a list of CapHiveOTService_listCapabilities_Params.
type CapHiveOTService_listCapabilities_Params_List = capnp.StructList[CapHiveOTService_listCapabilities_Params]

// NewCapHiveOTService_listCapabilities_Params creates a new list of CapHiveOTService_listCapabilities_Params.
func NewCapHiveOTService_listCapabilities_Params_List(s *capnp.Segment, sz int32) (CapHiveOTService_listCapabilities_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[CapHiveOTService_listCapabilities_Params](l), err
}

// CapHiveOTService_listCapabilities_Params_Future is a wrapper for a CapHiveOTService_listCapabilities_Params promised by a client call.
type CapHiveOTService_listCapabilities_Params_Future struct{ *capnp.Future }

func (f CapHiveOTService_listCapabilities_Params_Future) Struct() (CapHiveOTService_listCapabilities_Params, error) {
	p, err := f.Future.Ptr()
	return CapHiveOTService_listCapabilities_Params(p.Struct()), err
}

type CapHiveOTService_listCapabilities_Results capnp.Struct

// CapHiveOTService_listCapabilities_Results_TypeID is the unique identifier for the type CapHiveOTService_listCapabilities_Results.
const CapHiveOTService_listCapabilities_Results_TypeID = 0xb85b7168b73532f9

func NewCapHiveOTService_listCapabilities_Results(s *capnp.Segment) (CapHiveOTService_listCapabilities_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapHiveOTService_listCapabilities_Results(st), err
}

func NewRootCapHiveOTService_listCapabilities_Results(s *capnp.Segment) (CapHiveOTService_listCapabilities_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CapHiveOTService_listCapabilities_Results(st), err
}

func ReadRootCapHiveOTService_listCapabilities_Results(msg *capnp.Message) (CapHiveOTService_listCapabilities_Results, error) {
	root, err := msg.Root()
	return CapHiveOTService_listCapabilities_Results(root.Struct()), err
}

func (s CapHiveOTService_listCapabilities_Results) String() string {
	str, _ := text.Marshal(0xb85b7168b73532f9, capnp.Struct(s))
	return str
}

func (s CapHiveOTService_listCapabilities_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CapHiveOTService_listCapabilities_Results) DecodeFromPtr(p capnp.Ptr) CapHiveOTService_listCapabilities_Results {
	return CapHiveOTService_listCapabilities_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CapHiveOTService_listCapabilities_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CapHiveOTService_listCapabilities_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CapHiveOTService_listCapabilities_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CapHiveOTService_listCapabilities_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CapHiveOTService_listCapabilities_Results) InfoList() (CapabilityInfo_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return CapabilityInfo_List(p.List()), err
}

func (s CapHiveOTService_listCapabilities_Results) HasInfoList() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CapHiveOTService_listCapabilities_Results) SetInfoList(v CapabilityInfo_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewInfoList sets the infoList field to a newly
// allocated CapabilityInfo_List, preferring placement in s's segment.
func (s CapHiveOTService_listCapabilities_Results) NewInfoList(n int32) (CapabilityInfo_List, error) {
	l, err := NewCapabilityInfo_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return CapabilityInfo_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// CapHiveOTService_listCapabilities_Results_List is a list of CapHiveOTService_listCapabilities_Results.
type CapHiveOTService_listCapabilities_Results_List = capnp.StructList[CapHiveOTService_listCapabilities_Results]

// NewCapHiveOTService_listCapabilities_Results creates a new list of CapHiveOTService_listCapabilities_Results.
func NewCapHiveOTService_listCapabilities_Results_List(s *capnp.Segment, sz int32) (CapHiveOTService_listCapabilities_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[CapHiveOTService_listCapabilities_Results](l), err
}

// CapHiveOTService_listCapabilities_Results_Future is a wrapper for a CapHiveOTService_listCapabilities_Results promised by a client call.
type CapHiveOTService_listCapabilities_Results_Future struct{ *capnp.Future }

func (f CapHiveOTService_listCapabilities_Results_Future) Struct() (CapHiveOTService_listCapabilities_Results, error) {
	p, err := f.Future.Ptr()
	return CapHiveOTService_listCapabilities_Results(p.Struct()), err
}

const schema_aedf69d9667f51a8 = "x\xda\x9c\x94_h\x1cU\x14\xc6\xcfw\xef\xdcL\x1f" +
	"6mn'\x81\xf4A\x82\xa1\x14\xad\xd6\xfeC\x84 " +
	"lj\xfb`\x8a\xb6{3m\x85\x14\xc5\xc9\xf6\xa6{" +
	"a\xb3;\xdd\x99\xad$X\x8b(j\xa5\x95\x16\x94Z" +
	"\xa1\x0f\x86\x08F\xd0\x17Q\x8b\xf8\xe4\x9f\x17\x1f\xaa\xe0" +
	"S\x05-\x08\xda\x17\xa9\xd4>\x98\x8a2r73\xd9" +
	"\xddl\xc2J\xdf\x869\xe7|\xf7;\xbfs8;\xfe" +
	"\xc2\xa8\xb3\xb3w\xbb \xa6\x1e\x15=\xc9\xb7\x0f\xc4\x07" +
	"?\xf8\xfe\xe8\xcb$\x07\x90\xbc\xafNO]3\xd7?" +
	"\"\xe1\xb8D\xbbO\xb1ax\xe7\x98K\xe4\x9da7" +
	"\x08\xc9\x8e\xef.\x96~{z\xdb+$\x07\x9cf2" +
	"a\xf79>\x0c\xef2w\x89\xfc\xb79\x87?\xcf\x19" +
	"\x88\x92?\xae\x7f\xf5\xc8\xe2\xaf/\\\"\xb9\x05\x94\x8a" +
	"^\xe2?\x82\xe0}\xc8\xad\xe0\xed\x7f'\x16\xcc\x9d\xbd" +
	"sta@\xb06\xc5\xcb\x0e\x83\xb7`+\xfcy\x87" +
	"\x83\x90\xdc\xd9\xf5\xf0g\xa5\x13G\xaf\xa4b\xb0bo" +
	"9\x7f[\xb1\x05'OH>\xfe\xfa\xa5\xc57\xde<" +
	"\xffy\x87\xbb\x9f\x9c\xfd\xf0n5\xb4~w8\xfcE" +
	"\xa7\xe1n\xd3\xd9\x9eS/>e\xaev\xe4\xdfrf" +
	"\xe1\x09\xe1\x12\x8d\x0b\x0e?'\x1a\xe9\x9f~2\xfb\xc5" +
	"3W\xde\xfd\xa1#\x1db\x04\x9e\xb4\xe9~\xce\xe6\x0f" +
	".\xe5\xdf>b.\xbe\xf3\xcd\xf4\xb5V\xbf\xbd\xe2\x17" +
	"\xeb\xf7^a\xfd~9W8\xf2\xcf\x83\x837H\x0e" +
	"\xf06\xc1=b\x17<e\x05\xbd'\xc5\xab\xde\x82\xfd" +
	"J\xb6\\\x9d\xfb\xf9f\xf2\xdc\xcdV\xb9\x0b\xe2O+" +
	"\xf7\x9e\xc8\xd3\xb6\xa4T\x9f\x0cB\xb3\xdd\xe7\xbav\xd2" +
	"\x14\xf5C\xc5 \xac\x84#{\x830\x984e\x13\xcf" +
	"\x8c\xb9\x95\xa9j\x01P}\xdc\x01w@$\x83I\"" +
	"\xf5,\x87*3\xf4\xa1\x1f\xf6\x9f\x99%R%\x0e\x15" +
	"3H\xb0~0\"y\xc2\xfe\x0c9\xd4Y\x06\xc9x" +
	"?8\x91<c\xab_\xe3P\xf3\x0cI\xb4\xf4\xea\x01" +
	"r\x83i\x8d\x1c1\xe4\x08I1}\x9d\xf2\xf1\xcc\x81" +
	"\xb5\x02{j\xc7#\xac'\x148\x1a\xf1\xf56^6" +
	"\xba\x12\x1f\x9a!7\xd4\x1d\xc1\xd5;\xcdJB}\xd8" +
	"\x8dt\xad\x00\xa4\xaf\x91\xc4\xd6\x0d\xf5H\xd7\x96\x0b{" +
	"V\"z\xdc\x9c\xd4\x07\x0f\xf9\xe9\xef\xe3:nb\xdb" +
	"\\\x08j\x01\x9f\x8e,6\xa2%l\xfb\x9b\xd8$2" +
	"n\x13-\xdc\xd8Jn\xcf3H\x9er\x9b\xd9J\xa4" +
	"b\x0eu\x9ee\x8d\x8e\xed#\xa2&\x9c\xacy\x1ev" +
	"G\xb9!X\x05_7B\x94\xd2\xf9\xbfD\xca&j" +
	"\"1:\xda<\x9e\xd7Q\xbd\x1cG\xcaY\xa6\xd2k" +
	"\xa9\xe48\xd4}\x0c\x89\xa9LU\x9f0Ql\xdbJ" +
	"\xbd\xf55o\x0d\xa1\xcd\xa5\xb3\x86\xcb\xb1j\xbcO\xdb" +
	"\x08Q\xdb4\xc7\x13S\x8d\x8f\xd9\x08AwU9\\" +
	"\x09\xeaqIW\xe2\xbc)\x06\xb1>\xd6&5\x92\xaf" +
	"Tm\xb8+1?\xbf\x14h\xab~\xect\xba\xf6w" +
	"\xb7Y\xe3:\xaa\xbb+ \x0e\x13\xa9u\x1c\xaa\x9f\xc1" +
	"-\x06!6:\x9c\x80\x8dk\xce\xb4\xe5\x89\xa1\xcc\xa0" +
	"Z\xc7E\xcb\xf5Ev\x89\xe4\xce\x1a1y\xbf\x0b," +
	"_\x13dWU\xde\xf3:1\xb9\xc9M2\x8b4\xd4" +
	"09\x8a$\x1b>\xb2\xe9\x13\x8d\xa2\x00\xdc\xf5\xf2\x14" +
	"\x86\x82Z0\xdd\xd6\xf6D\xba;\x83l\xf5\xf5\xff/" +
	"\x00\x00\xff\xffI\x1e\xe8\xf8"

func init() {
	schemas.Register(schema_aedf69d9667f51a8,
		0x845bd0aa4f742bca,
		0x862d5de66897cf30,
		0x997ee5f837c3dfef,
		0xa243f969a95afdf3,
		0xb85b7168b73532f9,
		0xba90948ef883c4b3,
		0xce6957817d068c19,
		0xd3a1b85ebc7ab5b6,
		0xd96dc59a976956f3,
		0xe7182cfc5650a2c2,
		0xee77ffeedea2ce26)
}
